import assert from'node:assert/strict';import{mkdirSync,writeFileSync}from'node:fs';import{preset,compile,copy,isSpinner,identity,v,decodeBuild,encodeBuild,RULES}from'../src/model';import{scratchBuild,installKit,inspectBuild,templateParts,partKit,partDimensions,addStructuralPart}from'../src/builder-workshop';import{Simulation,initializePhysics,neutral,Tournament}from'../src/sim';
await initializePhysics();mkdirSync('browser-evidence',{recursive:true});const evidence=[];
for(let i=0;i<11;i++){const c=preset(i),check=inspectBuild(c);assert(!check.issues.some(e=>e.severity==='error'),JSON.stringify({i,issues:check.issues}));for(const p of templateParts(i)){const d=partDimensions(p);assert(Number.isFinite(p.mass)&&[d.x,d.y,d.z].every(Number.isFinite));const kind=partKit(p);if(kind){const installed=installKit(c,kind,i);const model=compile(installed,true);assert.equal(model.errors.length,0,JSON.stringify({i,part:p.id,errors:model.errors}));}}const sim=new Simulation([c,preset((i+1)%11)],{practice:true,hazards:false,ai:[false,false],autoUnstick:false,recordVisuals:false});try{for(let tick=0;tick<240;tick++)sim.step([{...neutral(),left:.3,right:.3,weapon:tick===48},neutral()]);assert.equal(sim.fault,undefined);assert(sim.bots.every(b=>Number.isFinite(b.energy)&&Number.isFinite(b.rpm)));}finally{sim.dispose();}evidence.push({template:i,parts:templateParts(i).length,functionalKits:true});}
const reframed=installKit(preset(1),'chassis',0);assert.equal(reframed.chassis.profile,'tombstone');for(const role of ['weapon','drive','selfRight','battery','armour'] as const)assert.equal(reframed.components?.[role],'minotaur');assert.equal(reframed.weapon.type,'drum');
const hydraKit=installKit(scratchBuild(),'weapon',2);if(hydraKit.weapon.type==='flipper')hydraKit.weapon.width=.18;assert(!compile(hydraKit,true).errors.some(e=>e.field==='weapon.mount'),JSON.stringify(compile(hydraKit,true).errors));
const folding=installKit(scratchBuild(),'selfRight',5);if(folding.selfRight.type==='roll_arm')folding.selfRight.mount.x=-.15;assert(!compile(folding,true).errors.some(e=>e.field==='selfRight.mount'),JSON.stringify(compile(folding,true).errors));
const recoverySim=new Simulation([folding,preset(10)],{practice:true,hazards:false,ai:[false,false],recordVisuals:false});try{for(let tick=0;tick<600;tick++)recoverySim.step([{...neutral(),selfRight:tick===24},neutral()]);assert.equal(recoverySim.fault,undefined);}finally{recoverySim.dispose();}
const scratch=scratchBuild();assert.equal(inspectBuild(scratch).issues.filter(i=>i.severity==='error').length,0);assert.equal(compile(scratch,true).errors.length,0);assert(compile(scratch).errors.some(e=>e.field==='weapon.type'));const invalid=preset(0);if(isSpinner(invalid.weapon))invalid.weapon.mount.y=-.25;assert(inspectBuild(invalid).issues.some(e=>/floor/i.test(e.message)));const attachment=templateParts(0).find(p=>!partKit(p)&&p.body==='chassis'&&p.collides)!;const attached=addStructuralPart(scratch,0,attachment.id);const p=compile(attached,true).parts.find(p=>p.id.startsWith('addon_'));assert(p&&p.mass>0&&p.collides);assert.deepEqual(decodeBuild(encodeBuild(attached)).attachments,attached.attachments);
const mixed=installKit(preset(0),'weapon',1);if(isSpinner(mixed.weapon)){mixed.weapon.mount.y=.08;mixed.weapon.mount.z=-.52;}mixed.chassis.equipmentMassKg=0;const mixedReport=inspectBuild(mixed);assert(!mixedReport.issues.some(i=>i.severity==='error'),JSON.stringify(mixedReport.issues));const sim=new Simulation([mixed,preset(10)],{practice:true,hazards:false,ai:[true,true],seed:202612,recordVisuals:false});try{for(let i=0;i<1200;i++)sim.step();assert.equal(sim.fault,undefined);}finally{sim.dispose();}const tournament=new Tournament(mixed,false,8022);assert.equal(tournament.entries.length,8);assert.equal(tournament.playerConfigs()[0].components?.weapon,'minotaur');tournament.dispose();
writeFileSync('browser-evidence/builder-functional.json',JSON.stringify({status:'passed',source:process.env.GITHUB_SHA,evidence,scratch:true,geometryWarnings:true,attachmentMass:p!.mass,mixedFight:true,mixedTournamentEntry:true},null,2));console.log('PASS all eleven component libraries, stock mechanisms, scratch, warnings, attachments, and a mixed custom fight');