import assert from 'node:assert/strict';
import * as THREE from 'three';
import {mkdirSync,writeFileSync} from 'node:fs';
import {preset,compile,rng,tournamentTemplates,freshTournamentSeed,MATERIALS,SLOTS} from '../src/model';
import {Tournament,Simulation,initializePhysics} from '../src/sim';
import {FollowCamera,StableTrackingPose,CAMERA_STABILITY} from '../src/follow-camera';
import {DamageDebris,DAMAGE_DEBRIS,fragmentCount} from '../src/damage-debris';
await initializePhysics();
const rosters=new Set<string>();for(let seed=1;seed<=32;seed++){const t=new Tournament(preset(0),false,seed),same=new Tournament(preset(0),false,seed),profiles=t.entries.slice(1).map(e=>e.config.chassis.profile);assert.equal(new Set(profiles).size,7);assert(!profiles.includes('tombstone'));assert.deepEqual(t.entries,same.entries);rosters.add(profiles.join('/'));t.dispose();same.dispose();}assert(rosters.size>28);assert(new Set(Array.from({length:16},freshTournamentSeed)).size>1);const online=tournamentTemplates(rng(841));assert.equal(new Set(online.slice(0,7)).size,7);
const quantum=compile(preset(10)),other=compile(preset(0));for(const slot of ['chassis','drive_left','drive_right','weapon','weapon_actuator','battery'] as const)assert.equal(quantum.modules[slot].max,other.modules[slot].max,slot);assert.equal(quantum.modules.drive_left.max,400);assert.equal(quantum.modules.weapon.max,500);
const sim=new Simulation([preset(10),preset(0)],{hazards:false,ai:[false,false],recordVisuals:false});for(const id of[0,1]){sim.damage(id,'weapon',100*MATERIALS[sim.bots[id].modules.weapon.material].resistance);assert.equal(sim.bots[id].modules.weapon.hp,400);}const armor=sim.bots[0].modules.armour_left;sim.damage(0,'armour_left',(armor.hp+.01)*MATERIALS[armor.material].resistance);assert(sim.debris.length>0);assert(sim.debris.every(d=>d.part.module==='armour_left'));for(let i=0;i<120;i++)sim.step();for(const b of sim.bots)assert(Object.values(b.chassis.translation()).every(Number.isFinite));assert(!sim.fault);sim.dispose();
for(const reduced of[false,true])for(let index=0;index<11;index++){const c=preset(index),rig=new FollowCamera(),camera=new THREE.PerspectiveCamera(),p=new THREE.Vector3(0,.2,0),q=new THREE.Quaternion();rig.update(camera,p,q,c,compile(c).envelope,'bot',1/60,reduced);const baseline=camera.position.clone();for(let i=0;i<90;i++){const tilt=new THREE.Quaternion().setFromAxisAngle(new THREE.Vector3(1,0,0),Math.sin(i*.3)*1.55);rig.update(camera,p,tilt,c,compile(c).envelope,'bot',1/60,reduced);}assert(camera.position.distanceTo(baseline)<.001,'Pitch must not shake the follow camera');p.y+=.5;const before=camera.position.clone();rig.update(camera,p,q,c,compile(c).envelope,'bot',1/60,reduced);assert(camera.position.distanceTo(before)<.06);for(let i=0;i<180;i++)rig.update(camera,p,q,c,compile(c).envelope,'bot',1/60,reduced);assert(camera.position.y>before.y+.45);assert.equal(camera.up.y,1);assert.equal(camera.up.x,0);assert.equal(camera.up.z,0);}
const pose=new StableTrackingPose(),c=preset(0),p=new THREE.Vector3(),q=new THREE.Quaternion();pose.update(p,q,c,'pov',1/60);const shock=pose.update(new THREE.Vector3(.5,.5,0),new THREE.Quaternion().setFromAxisAngle(new THREE.Vector3(0,1,0),2.5),c,'pov',1/60);assert(shock.position.x<.07&&shock.position.y<.04);assert(Math.abs(shock.yaw)<=CAMERA_STABILITY.maxYawRate/60+.0001);
const invertedPose=new StableTrackingPose();invertedPose.update(p,q,c,'inversion',1/60);let inverted;for(let i=0;i<180;i++)inverted=invertedPose.update(p,new THREE.Quaternion().setFromAxisAngle(new THREE.Vector3(1,0,0),Math.PI),c,'inversion',1/60);assert(Math.abs(Math.abs(inverted!.yaw)-Math.PI)<.05,'An inverted robot must retain its real front direction after the camera settles');
const d=new DamageDebris(),source=()=>({position:new THREE.Vector3(0,.3,0),center:new THREE.Vector3(),size:.3,color:'#8899aa',part:'wheel_-1_0'});d.observe(0,'drive_left',400,400,source,0);d.observe(0,'drive_left',380,400,source,.01);d.observe(0,'drive_left',380,400,source,.02);d.observe(0,'drive_left',350,400,source,.03);assert(d.count>0);assert(d.root.children.every(o=>o.userData.module==='drive_left'&&o.userData.fragmentKind==='tire'));d.observe(0,'weapon',500,500,source,.03);d.observe(0,'weapon',0,500,source,.04);assert(d.root.children.some(o=>o.userData.fragmentKind==='tooth'));for(let bot=1;bot<30;bot++){d.observe(bot,'battery',350,350,source,.1);d.observe(bot,'battery',0,350,source,.2);}assert.equal(d.count,DAMAGE_DEBRIS.capacity);assert(fragmentCount(1,1200)===0);d.step(4);assert.equal(d.count,0);d.observe(99,'weapon',500,500,source,4,true);d.observe(99,'weapon',0,500,source,4.1,true);assert.equal(d.count,0);d.dispose();
const cup=new Tournament(preset(0),false,31);for(let round=0;round<3;round++){const fight=new Simulation(cup.playerConfigs(),{hazards:false,ai:[false,false],recordVisuals:false});fight.finish('Judges’ decision',0);cup.recordPlayer(fight.result!,fight.bots[0].modules);fight.dispose();if(round<2){cup.quickResolveComputerMatches();cup.advance();}}assert(cup.champion?.player,'A final win must declare the champion without another action');cup.dispose();
mkdirSync('browser-evidence',{recursive:true});writeFileSync('browser-evidence/combat-visibility.json',JSON.stringify({source:process.env.GITHUB_SHA,status:'passed',uniqueRosters:rosters.size,quantum:{chassis:1200,drive:400,weapon:500},stableCameras:22,physicalArmorDebris:true,componentFragments:true,boundedFragments:48,automaticChampion:true},null,2));console.log('PASS randomized entrants, equal durability, physical damage, stable cameras, component fragments, and automatic champion');
