import assert from 'node:assert/strict';import {mkdir,writeFile} from 'node:fs/promises';import {pathToFileURL} from 'node:url';
const {chromium}=await import(pathToFileURL(process.env.RUNNER_TEMP+'/browser/node_modules/playwright/index.mjs').href);const base=process.env.ARENA_URL??'http://127.0.0.1:4173/';await mkdir('browser-evidence',{recursive:true});const browser=await chromium.launch({headless:true,args:['--use-angle=swiftshader','--enable-unsafe-swiftshader','--disable-gpu-sandbox']}),errors=[];let p;
try{
 if(!process.env.ARENA_URL){p=await browser.newPage({viewport:{width:1280,height:800}});p.on('pageerror',e=>errors.push(String(e)));await p.goto(base+'follow-fixture.html');await p.waitForFunction(()=>window.fixtureReady,undefined,{timeout:90000});const report=await p.evaluate(async()=>{
  const m=window.fixture;await m.initializePhysics();document.querySelector('#fixture-root').innerHTML='<main class="shell" style="height:760px"><section class="arena-wrap"><div id="scene"></div><div id="hud"></div></section></main>';
  const sim=new m.Simulation([m.preset(0),m.preset(1)],{practice:true,hazards:false,ai:[false,false],recordVisuals:false}),renderer=new m.ArenaRenderer(document.querySelector('#scene'),()=>{},()=>{});renderer.setQuality('low');renderer.reduced=true;renderer.mode='match';renderer.cameraMode='chase';renderer.attach(sim);renderer.mode='match';const hud=document.querySelector('#hud');hud.innerHTML=m.OPPONENT_HUD_MARKUP;window.followTest={sim,renderer};
  const cases=[];for(const side of[0,1]){renderer.viewerBotId=side;renderer.update(sim,0,1);renderer.draw(sim,1/60);m.updateOpponentHud(hud,renderer,sim);const target=1-side;cases.push({side,target:document.querySelector('#opponent-floating-hp').dataset.target,name:document.querySelector('#opponent-floating-name').textContent,camera:renderer.camera.position.toArray(),onScreen:renderer.opponentIndicator(sim).onScreen});
   const own=renderer.bodyGroups.get('b'+side+':chassis'),other=renderer.bodyGroups.get('b'+target+':chassis');const original=other.position.clone(),before=renderer.camera.position.clone();own.position.x+=.45;renderer.draw(sim,1/60);cases.push({cameraMovement:renderer.camera.position.clone().sub(before).toArray()});const facing=renderer.camera.getWorldDirection(own.position.clone());other.position.copy(renderer.camera.position).addScaledVector(facing,-3);renderer.draw(sim,1/60);m.updateOpponentHud(hud,renderer,sim);const point=renderer.opponentIndicator(sim);cases.push({behind:point.behind,x:point.x,y:point.y,indicatorVisible:!document.querySelector('#opponent-pointer').classList.contains('hidden'),edgeHP:document.querySelector('#opponent-edge-hp').textContent});other.position.copy(original);sim.bots[target].modules.chassis.hp=432.4;m.updateOpponentHud(hud,renderer,sim);cases.push({hp:document.querySelector('#opponent-hp-value').textContent,target:document.querySelector('#opponent-floating-hp').dataset.target});
  }return cases;
 });for(const c of report){if(c.side!==undefined){assert.equal(Number(c.target),1-c.side);assert.equal(c.name,c.side?'Tombstone':'Minotaur');assert(c.camera.every(Number.isFinite));}if(c.behind!==undefined){assert(c.behind);assert(c.indicatorVisible);assert(c.x>=8&&c.x<=92);assert(c.y>=18&&c.y<=76);}if(c.hp)assert(c.hp.startsWith('432 /'));}await p.screenshot({path:'browser-evidence/follow-fixture.png',timeout:90000});await p.evaluate(()=>{window.followTest.renderer.dispose();window.followTest.sim.dispose();});await p.close();await writeFile('browser-evidence/follow-renderer.json',JSON.stringify({source:process.env.GITHUB_SHA,report},null,2));}
 p=await browser.newPage({viewport:{width:1440,height:900}});p.on('pageerror',e=>errors.push(String(e)));await p.addInitScript(()=>{localStorage.setItem('cra.preferences',JSON.stringify({quality:'low',reduced:true,cameraMode:'chase'}));window.__arenaTools=new Map();Object.defineProperty(document,'modelContext',{value:{registerTool:t=>window.__arenaTools.set(t.name,t)},configurable:true});});await p.goto(base,{waitUntil:'domcontentloaded',timeout:90000});await p.waitForFunction(()=>window.__arenaTools.has('read_arena_status'),undefined,{timeout:90000,polling:100});await p.locator('#open-settings').click();assert.equal(await p.locator('#camera-mode option').count(),3);assert.equal(await p.locator('#camera-mode').inputValue(),'chase');await p.locator('#close-settings').click();await p.evaluate(()=>window.__arenaTools.get('start_robot_practice').execute({}));await p.waitForFunction(()=>document.querySelector('#camera-button')?.textContent.includes('Third person'),undefined,{timeout:30000,polling:100});await p.waitForFunction(()=>!document.querySelector('#opponent-pointer')?.classList.contains('hidden'),undefined,{timeout:30000,polling:100});assert.equal(await p.locator('#opponent-floating-hp').getAttribute('data-target'),'1');assert(/1200/.test(await p.locator('#opponent-hp-value').textContent()));await p.screenshot({path:'browser-evidence/third-person-practice.png',timeout:90000});await p.locator('#camera-button').click();assert(/Robot POV/.test(await p.locator('#camera-button').textContent()));await p.locator('#camera-button').click();assert(/Tactical/.test(await p.locator('#camera-button').textContent()));await p.locator('#camera-button').click();assert(/Third person/.test(await p.locator('#camera-button').textContent()));await p.locator('#fight-menu').click();await p.reload({waitUntil:'domcontentloaded',timeout:90000});await p.waitForFunction(()=>window.__arenaTools.has('read_arena_status'),undefined,{timeout:90000,polling:100});await p.locator('#open-settings').click();assert.equal(await p.locator('#camera-mode').inputValue(),'chase');assert.deepEqual(errors,[]);await writeFile('browser-evidence/follow-browser.json',JSON.stringify({status:'passed',source:process.env.TESTED_SOURCE??process.env.GITHUB_SHA,url:base,thirdPerson:true,indicator:true,health:true,cycle:true,persistence:true,errors},null,2));console.log('PASS third-person UI, opponent health and indicator, camera cycle, and saved preference');
}catch(error){await writeFile('browser-evidence/follow-browser-failure.json',JSON.stringify({error:String(error),errors,body:await p?.locator('body').textContent().catch(()=>null)},null,2));throw error;}finally{await browser.close();}
