import assert from 'node:assert/strict';
import {writeFileSync} from 'node:fs';
import * as THREE from 'three';
import {Simulation,initializePhysics,neutral} from '../src/sim';
import {preset,compile,ROSTER,RULES,bodyOrigin,armOffset,isSpinner,axisQ,rotate,quatMul,add,sub,mul,dot,length,v,identity,driveMotorStep,partProperties} from '../src/model';
import {contactSparkDirection,sparkParticle,sparkProfile,writeSparkTrail,SPARK_CAPACITY,SPARK_TRAIL_FLOATS} from '../src/impact-sparks';
import {sparkSoundSamples} from '../src/audio';
import {ArenaRenderer} from '../src/render';
import {randomRobot} from '../src/match-presentation';
import {TireEffects,skidStrength} from '../src/tire-effects';
const results:any[]=[];
async function test(name:string,fn:()=>unknown){if(process.env.CASE&&!name.includes(process.env.CASE))return;try{const detail=await fn();results.push({name,status:'passed',detail});console.log('PASS',name,JSON.stringify(detail));}catch(e){results.push({name,status:'failed',error:String(e)});console.log('FAIL',name,String(e));process.exitCode=1;}writeFileSync('docs/handling-effects-update-results.json',JSON.stringify(results,null,2)+'\n');}
await initializePhysics();
function make(a=7,b=0,practice=true){return new Simulation([preset(a),preset(b)],{practice,hazards:false,ai:[false,false],autoUnstick:false});}
function pose(s:Simulation,id:number,p:ReturnType<typeof v>,q=identity){const b=s.bots[id];for(const[key,body]of b.bodies){body.setRotation(q,true);body.setTranslation(add(p,rotate(bodyOrigin(b.compiled.config,key),q)),true);body.setLinvel(v(),true);body.setAngvel(v(),true);}s.world.propagateModifiedBodyPositionsToColliders();}
const relativeAngle=(s:Simulation,id:number,axis:'x'|'z'='z')=>{const b=s.bots[id],q=b.chassis.rotation(),r=b.roll!.rotation(),rel=quatMul({x:-q.x,y:-q.y,z:-q.z,w:q.w},r);return 2*Math.atan2(rel[axis],rel.w);};
await test('All eleven builds stay legal and HUGE keeps 20 mm blade clearance',()=>{const rows=ROSTER.map((r,i)=>{const c=compile(preset(i));assert.deepEqual(c.errors,[],r.name);return{name:r.name,massKg:c.mass};});const c=preset(7);assert(isSpinner(c.weapon));assert.equal(c.weapon.radius,.46);assert(Math.abs(c.drive.radius-c.weapon.radius-.02)<1e-8);c.weapon.radius=.479;c.weapon.rpm=2200;assert(compile(c).errors.some(e=>e.field==='weapon.radius'));return{robots:rows,hugeBladeDiameterM:.92,wheelDiameterM:.96,clearanceMm:20};});
await test('HUGE body stays level during forward, reverse, and turning with its blade running',()=>{const s=make();try{pose(s,0,v(0,.49,2));pose(s,1,v(5,.21,-4));const b=s.bots[0];b.weaponOn=true;let tilt=0,minClearance=1,forward=0,reverse=0;for(let i=0;i<1600;i++){const phase=Math.floor(i/400),l=phase===0?.7:phase===1?-.7:phase===2?.35:0,r=phase===2?-.35:l;s.step([{...neutral(),left:l,right:r},neutral()]);if(i>100){tilt=Math.max(tilt,Math.acos(Math.min(1,Math.abs(s.axis(b,v(0,1,0)).y)))*180/Math.PI);minClearance=Math.min(minClearance,b.rotor!.translation().y-(b.compiled.config.weapon as any).radius);}const speed=dot(b.chassis.linvel(),s.forward(b));forward=Math.max(forward,speed);reverse=Math.max(reverse,-speed);}assert.equal(s.fault,undefined);assert(tilt<15,JSON.stringify({tilt,minClearance}));assert(minClearance>.009);assert(forward>1.5&&reverse>1.5);assert(Math.abs(b.colliders.get('wheel_-1_0_contact')!.friction()-2.10)<1e-6);return{maxTiltDegrees:tilt,minBladeClearanceMm:minClearance*1000,forwardMps:forward,reverseMps:reverse};}finally{s.dispose();}});
await test('HUGE blade makes a real weapon contact with every opposing template',()=>{const rows=[];for(let i=0;i<ROSTER.length;i++){const s=make(7,i);try{pose(s,0,v(0,.49,3));const c=s.bots[1].compiled.config;pose(s,1,v(i===7?.445:0,c.chassis.height/2+c.chassis.clearance+.009,2.12));const b=s.bots[0];b.weaponOn=true;b.rotor!.setAngvel(v(2300*Math.PI/30,0,0),true);for(const body of b.bodies.values())body.setLinvel(v(0,0,-2),true);for(let t=0;t<240;t++)s.step([{...neutral(),left:.45,right:.45},neutral()]);const hits=s.events.filter(e=>e.cause==='weapon'&&e.attacker===0&&e.target===1);assert(hits.length>0,ROSTER[i].name);assert.equal(s.fault,undefined);rows.push({opponent:ROSTER[i].name,bladeHits:hits.length});}finally{s.dispose();}}return rows;});
await test('Gigabyte remains stable and its folded arm stays latched through drive and impact',()=>{const s=make(5);try{const b=s.bots[0];pose(s,0,v(0,.085,3));pose(s,1,v(5,.22,-4));b.weaponOn=true;let tilt=0,arm=0;for(let i=0;i<1800;i++){const phase=Math.floor(i/450),l=phase===0?.45:phase===1?-.45:phase===2?.3:0,r=phase===2?-.3:l;if(i===700)b.roll!.applyTorqueImpulse(v(0,0,.3),true);s.step([{...neutral(),left:l,right:r},neutral()]);if(i>100){tilt=Math.max(tilt,Math.acos(Math.min(1,s.axis(b,v(0,1,0)).y))*180/Math.PI);arm=Math.max(arm,Math.abs(relativeAngle(s,0)));}}assert.equal(s.fault,undefined);assert(tilt<18,JSON.stringify({tilt,arm}));assert(arm<.025,JSON.stringify({arm}));return{maxTiltDegrees:tilt,maxArmMotionDegrees:arm*180/Math.PI,floorAttractionN:180};}finally{s.dispose();}});
await test('Gigabyte unlocks its arm only for deliberate self-righting and stows it again',()=>{const s=make(5);try{const b=s.bots[0],c=b.compiled.config;pose(s,0,v(0,.41,2),axisQ(v(0,0,1),Math.PI));for(let i=0;i<200;i++)s.step();assert(s.requestSelfRight(b));let maxArm=0;for(let i=0;i<2400;i++){s.step();maxArm=Math.max(maxArm,Math.abs(relativeAngle(s,0)));}assert.equal(s.fault,undefined);assert(maxArm>.8);assert(s.axis(b,v(0,1,0)).y>.85,JSON.stringify({up:s.axis(b,v(0,1,0)).y,arm:relativeAngle(s,0),rollStart:b.rollStart}));assert(Math.abs(relativeAngle(s,0))<.06);return{maxArmDegrees:maxArm*180/Math.PI,finalArmDegrees:relativeAngle(s,0)*180/Math.PI,up:s.axis(b,v(0,1,0)).y};}finally{s.dispose();}});
await test('SawBlaze has a rear saw guard and a full 180 degree arm sweep',()=>{const c=preset(8),b=compile(c),s=make(8);try{assert(c.weapon.type==='hammer_saw');const guards=b.parts.filter(p=>p.id.startsWith('saw_guard_'));assert.equal(guards.length,24);assert(guards.every(p=>p.collides&&p.body==='weapon_arm'));const j=s.bots[0].joints.get('weapon_arm') as any;assert(Math.abs(j.limitsMax()-j.limitsMin()-Math.PI)<1e-6);return{guardSegments:guards.length,sweepDegrees:(j.limitsMax()-j.limitsMin())*180/Math.PI};}finally{s.dispose();}});
await test('SawBlaze floating forks get below the opponent and lift it',()=>{const s=make(8,10);try{pose(s,0,v(0,.096,2));pose(s,1,v(0,.09,.55));s.bots[1].energy=0;for(let i=0;i<240;i++)s.step();const b=s.bots[0],target=s.bots[1],start=target.chassis.translation().y;let lift=0,support=0;for(let i=0;i<1000;i++){s.step([{...neutral(),left:.45,right:.45},neutral()]);lift=Math.max(lift,target.chassis.translation().y-start);for(const[id,col]of b.colliders)if(id.startsWith('saw_fork_'))s.world.contactPairsWith(col,other=>{if(s.meta.get(other.handle)?.bot===1)s.world.contactPair(col,other,m=>{if(m.numSolverContacts()&&Math.abs(m.normal().y)>.2)support++;});});}assert.equal(s.fault,undefined);assert(support>0&&lift>.005,JSON.stringify({support,lift}));return{supportContacts:support,liftMm:lift*1000};}finally{s.dispose();}});
await test('Quantum has more tyre grip and motor torque, with 60 percent less release throttle',()=>{const c=preset(10),s=make(10);try{const b=s.bots[0],newTorque=driveMotorStep(c.drive.ratio,0,1,1,c.drive.motor).torque,oldTorque=driveMotorStep(12,0,1,1,'drive48').torque;assert(newTorque>oldTorque*1.5);assert(Math.abs(b.colliders.get('wheel_-1_0')!.friction()-1.8)<1e-6);b.gripRelease={tick:s.tick,p:{...b.chassis.translation()},back:mul(s.forward(b),-1),distance:2*b.compiled.envelope.z};(s as any).observeAI();(s as any).decide(b);assert.equal(b.ai.state,'release');assert(Math.abs((b.command.left+b.command.right)/2+.34)<1e-8);return{oldTorqueNm:oldTorque,newTorqueNm:newTorque,increasePercent:(newTorque/oldTorque-1)*100,oldReleaseThrottle:.85,newReleaseThrottle:.34,gripCoefficient:1.8};}finally{s.dispose();}});
await test('A robot thrown over the wall loses by ring-out, while ground rams remain inside',()=>{const rows=[];for(const high of[false,true]){const s=make(0,1,false);try{pose(s,0,v(6.3,high?3.5:.22,3));const b=s.bots[0];for(const body of b.bodies.values())body.setLinvel(v(11,0,0),true);for(let i=0;i<180&&!s.result;i++)s.step();assert.equal(s.fault,undefined);if(high){assert.equal(s.result?.reason,'Out of arena');assert.equal(s.result?.winner,1);}else{assert(!s.outOfArena(b));assert.notEqual(s.result?.reason,'Out of arena');}rows.push({thrown:high,x:b.chassis.translation().x,y:b.chassis.translation().y,result:s.result?.reason??'continues'});}finally{s.dispose();}}return rows;});
await test('Final motion preserves HP, winner and match clock while recording the last hit',()=>{const s=make(0,1,false);try{for(let i=0;i<60;i++)s.step();const b=s.bots[1];b.chassis.setLinvel(v(0,3,0),true);s.events.push({id:1,tick:s.tick,episode:'qa',source:'Tombstone',attacker:0,target:1,module:'chassis',energy:1000,impulse:20,closing:2,point:v(),rotorBefore:[100,0],rotorAfter:[0,0],allocations:[{bot:1,module:'chassis',energy:1000,hp:100}],cause:'weapon'});s.finish('Structural KO',0);const hp=s.bots.map(b=>b.modules.chassis.hp),remaining=s.remaining,y=b.chassis.translation().y;for(let i=0;i<120;i++)s.stepAfterFinish();assert.deepEqual(s.bots.map(b=>b.modules.chassis.hp),hp);assert.equal(s.result?.winner,0);assert.equal(s.remaining,remaining);assert.notEqual(b.chassis.translation().y,y);assert(s.frames.some(f=>f.hits?.some(h=>h.hp===100)));return{frames:s.frames.length,resultTick:s.result?.tick,animationTick:s.tick};}finally{s.dispose();}});
await test('Sparks follow the contact and launch direction with varied lengths and forks',()=>{const direction=contactSparkDirection(v(2,4,0),v(1,1,0),v(4,7,0)),lengths=new Set(),sizes=new Set();let forks=0,minAlignment=1;const positions=new Float32Array(SPARK_CAPACITY*SPARK_TRAIL_FLOATS),colors=positions.slice();for(let i=0;i<260;i++){const p=sparkParticle(40000,direction,i,19),alignment=dot(p.velocity,direction)/length(p.velocity);minAlignment=Math.min(minAlignment,alignment);lengths.add(p.trail.toFixed(5));sizes.add(p.size.toFixed(4));if(p.branch)forks++;writeSparkTrail(positions,colors,i,0,1,0,p.velocity.x,p.velocity.y,p.velocity.z,p.trail,.8,p.branch);}assert(minAlignment>.84);assert(lengths.size>100&&sizes.size>100&&forks>10);assert([...positions,...colors].every(Number.isFinite));return{particles:260,minDirectionAlignment:minAlignment,trailLengths:lengths.size,headSizes:sizes.size,forkedSparks:forks};});
await test('Spark sounds have three short bounded noise envelopes',()=>{return[0,1,2].map(level=>{const data=sparkSoundSamples(48000,level),peak=data.reduce((m,x)=>Math.max(m,Math.abs(x)),0),a=data.slice(0,500).reduce((m,x)=>m+x*x,0),z=data.slice(-500).reduce((m,x)=>m+x*x,0);assert(peak>0&&peak<=1);assert(z<a*.05);return{level,durationMs:data.length/48,peak};});});
await test('Deep Six has two swept hooked blades within its original 570 mm radius',()=>{const c=compile(preset(9)),tips=c.parts.filter(p=>p.id.startsWith('tooth_')),blade=c.parts.filter(p=>p.id.startsWith('vertical_bar_')&&p.id!=='vertical_hub');assert.deepEqual(c.errors,[]);assert.equal(tips.length,2);for(const section of['root','sweep','tip','spur'])assert.equal(blade.filter(p=>p.id.startsWith(`vertical_bar_${section}_`)).length,2);let max=0;for(const p of [...tips,...blade]){assert(p.shape.kind==='hull');for(let i=0;i<p.shape.vertices.length;i+=3)max=Math.max(max,Math.hypot(p.shape.vertices[i+1],p.shape.vertices[i+2]));}assert(max<=.57,`blade radius ${max}`);return{tips:2,sweptSections:blade.length,bladeRadiusM:max,maximumRadiusM:.57};});
await test('A corner hammer strike no longer knocks out Quantum through the floor',()=>{const s=new Simulation([preset(10),preset(0)],{practice:false,hazards:true,ai:[false,false],autoUnstick:false});try{const c=s.bots[0].compiled.config;pose(s,0,v(-5.7,c.chassis.height/2+c.chassis.clearance+.009,-5.6));pose(s,1,v(4,.21,3));s.tick=1155;for(let i=0;i<330&&!s.result&&!s.fault;i++)s.step([neutral(),neutral()]);const hammerHits=s.events.filter(e=>e.source.startsWith('Corner Hammer')&&e.target===0);assert(hammerHits.length>0);assert(hammerHits.every(e=>e.energy<=3500));assert([...s.hammerFloorWork.values()].every(energy=>energy<=3500));assert(s.bots[0].modules.chassis.hp>1050);assert.equal(s.result,undefined);assert.equal(s.fault,undefined);return{hammerHits:hammerHits.length,chassisHp:s.bots[0].modules.chassis.hp,hammerFloorEnergyJ:[...s.hammerFloorWork.values()]};}finally{s.dispose();}});
await test('Skid marks get stronger with speed, turning and braking',()=>{const slip=1.3,slow=skidStrength(slip,.3,0,0,2),fast=skidStrength(slip,5,0,0,2),corner=skidStrength(slip,5,3,0,2),brake=skidStrength(slip,5,3,1,2),effects=new TireEffects();assert.equal(skidStrength(.25,5,3,1,2),0);assert(0<slow&&slow<fast&&fast<corner&&corner<brake);const markOpacity=(effects.marks.material as THREE.MeshBasicMaterial).opacity;assert(markOpacity<=.35);effects.marks.geometry.dispose();(effects.marks.material as THREE.MeshBasicMaterial).dispose();(effects.smoke.material as THREE.PointsMaterial).dispose();effects.smoke.geometry.dispose();return{slow,fast,corner,brake,markOpacity};});
await test('Repeated material updates are skipped when damage has not changed',()=>{const renderer=Object.create(ArenaRenderer.prototype),mesh=new THREE.Mesh(new THREE.BoxGeometry(),new THREE.MeshStandardMaterial());mesh.userData={module:'chassis',material:'hardox',baseColor:0x999999,baseRoughness:.4};let calls=0;const material=mesh.material,original=material.color.setHex.bind(material.color);material.color.setHex=(n:any)=>{calls++;return original(n);};for(let i=0;i<120;i++)renderer.applyHealth(mesh,1);assert.equal(calls,1);renderer.applyHealth(mesh,.5);assert.equal(calls,2);mesh.geometry.dispose();material.dispose();return{frames:120,materialUpdates:1,skippedPercent:119/120*100};});
await test('Random selection covers every alternative and excludes invalid indices',()=>{for(let current=0;current<ROSTER.length;current++){const picks=new Set(Array.from({length:10},(_,i)=>randomRobot(current,()=>i/10)));assert.equal(picks.size,10);assert(!picks.has(current));assert([...picks].every(i=>i>=0&&i<ROSTER.length));}return{currentRobots:11,alternativesEach:10};});

await test('SawBlaze self-rights with the guarded arm and returns to its driving pose',()=>{const s=make(8);try{pose(s,0,v(0,.92,3),axisQ(v(0,0,1),Math.PI));for(let i=0;i<480;i++)s.step();const b=s.bots[0];assert(s.requestSelfRight(b));let recovered=-1;for(let i=0;i<1600;i++){s.step();if(recovered<0&&s.axis(b,v(0,1,0)).y>.9)recovered=i/RULES.hz;}assert.equal(s.fault,undefined);assert(recovered>=0&&recovered<4,JSON.stringify({recovered,up:s.axis(b,v(0,1,0)).y,angle:b.flipAngle}));assert(s.axis(b,v(0,1,0)).y>.95,JSON.stringify({recovered,up:s.axis(b,v(0,1,0)).y,angle:b.flipAngle,rollStart:b.rollStart,work:b.rollWork,p:b.chassis.translation()}));assert(Math.abs(b.flipAngle)<.08,JSON.stringify({angle:b.flipAngle,up:s.axis(b,v(0,1,0)).y,rollStart:b.rollStart,settling:b.rollSettling,work:b.rollWork}));return{recoveredSeconds:recovered,finalArmAngle:b.flipAngle};}finally{s.dispose();}});
await test('SawBlaze rear guard meets the floor before the spinning teeth',()=>{const s=make(8);try{
 const b=s.bots[0],w=b.compiled.config.weapon;assert(w.type==='hammer_saw');
 // Drop the rearward saw onto the floor with the hinge held at its end stop.
 // This checks the guard itself, independently of automatic recovery stowing.
 const angle=Math.PI-(w.armTravel??1.12),q=axisQ(v(1,0,0),angle),base=v(0,.19,3),pivot=add(base,w.mount);
 pose(s,0,base);b.arm!.setRotation(q,true);b.arm!.setTranslation(pivot,true);b.rotor!.setRotation(q,true);b.rotor!.setTranslation(add(pivot,rotate(armOffset(w),q)),true);b.rotor!.setAngvel(v(150,0,0),true);
 (b.joints.get('weapon_arm') as any).setLimits(angle-.001,angle);s.world.propagateModifiedBodyPositionsToColliders();
 let bladeFloor=0,guardFloor=0;for(let i=0;i<180;i++){s.world.step();for(const[id,col]of b.colliders)if(id.startsWith('saw_guard_')||id.startsWith('tooth_'))s.world.contactPairsWith(col,other=>{if(s.bodyIds.get(other.parent()!.handle)==='floor')s.world.contactPair(col,other,m=>{if(m.numSolverContacts()){if(id.startsWith('saw_guard_'))guardFloor++;else bladeFloor++;}});});}
 assert.equal(bladeFloor,0);assert(guardFloor>0);return{guardFloorContacts:guardFloor,toothFloorContacts:bladeFloor};
}finally{s.dispose();}});
await test('Slow-motion transforms interpolate between saved frames',()=>{const renderer=Object.create(ArenaRenderer.prototype);renderer.replayGroups=new Map([['b0:chassis',new THREE.Group()]]);renderer.reduced=false;const base:any={tick:0,transforms:[{id:'b0:chassis',p:v(),q:identity}],health:[Array(12).fill(1),Array(12).fill(1)],effects:[]},next={...base,tick:4,transforms:[{id:'b0:chassis',p:v(4,2,0),q:axisQ(v(0,1,0),Math.PI/2)}]};renderer.replayFrame(base,next,.5);const g=renderer.replayGroups.get('b0:chassis');assert.equal(g.position.x,2);assert.equal(g.position.y,1);assert(Math.abs(new THREE.Euler().setFromQuaternion(g.quaternion).y-Math.PI/4)<1e-6);return{interpolatedX:2,interpolatedYawDegrees:45};});
await test('The decisive hit remains available after a ten-second count-out delay',()=>{const s=make(0,1);try{for(let i=0;i<120;i++)s.step();const hitTick=s.tick;s.events.push({id:1,tick:hitTick,episode:'ko',source:'Tombstone',attacker:0,target:1,module:'drive_left',energy:18000,impulse:100,closing:10,point:v(),rotorBefore:[100,0],rotorAfter:[0,0],allocations:[{bot:1,module:'drive_left',energy:18000,hp:180}],cause:'weapon'});for(let i=0;i<11*RULES.hz;i++)s.step();s.finish('Count-out',0);const clip=s.lastHitReplay();assert(clip.length>20&&clip.length<100);assert(clip[0].tick<hitTick);assert(clip.at(-1)!.tick>hitTick+.5*RULES.hz);assert(clip.some(f=>f.hits?.some(h=>h.hp===180)));assert(s.frames[0].tick>clip.at(-1)!.tick);return{savedFrames:clip.length,delaySeconds:(s.result!.tick-hitTick)/RULES.hz,damageHP:180};}finally{s.dispose();}});
await test('Quantum retains physical self-righting with its stronger drive hardware',()=>{const rows=[];for(const[axis,angle]of[[v(0,0,1),Math.PI],[v(0,0,1),Math.PI/2],[v(0,0,1),-Math.PI/2],[v(1,0,0),Math.PI]]as const){const s=make(10);try{pose(s,0,v(0,.8,3),axisQ(axis,angle));for(let i=0;i<240;i++)s.step();const b=s.bots[0];assert(s.requestSelfRight(b));let recovered=-1;for(let i=0;i<2400;i++){s.step();if(recovered<0&&s.axis(b,v(0,1,0)).y>.9&&b.grounded)recovered=i/RULES.hz;}assert.equal(s.fault,undefined);assert(recovered>=0&&recovered<6);assert(s.axis(b,v(0,1,0)).y>.95);rows.push({axis,angle,recoveredSeconds:recovered});}finally{s.dispose();}}return rows;});
