import assert from 'node:assert/strict';
import {writeFileSync} from 'node:fs';
import {JSDOM} from 'jsdom';
import * as THREE from 'three';
import {ArenaRenderer} from '../src/render';
import {Simulation,initializePhysics,neutral} from '../src/sim';
import {preset,compile,ROSTER,RULES,bodyOrigin,axisQ,rotate,add,sub,dot,mul,v,isSpinner,strikeMultiplier,MATERIALS} from '../src/model';
import {damageStatus} from '../src/combat-damage';
import {podium} from '../src/result-view';
import {ROBOT_PORTRAITS} from '../src/robot-portraits';
const results:any[]=[];
async function test(name:string,fn:()=>unknown){if(process.env.CASE&&!name.includes(process.env.CASE))return;try{const detail=await fn();results.push({name,status:'passed',detail});console.log('PASS',name,JSON.stringify(detail));}catch(e){results.push({name,status:'failed',error:String(e)});console.log('FAIL',name,String(e));process.exitCode=1;}writeFileSync('docs/huge-control-update-results.json',JSON.stringify(results,null,2)+'\n');}
await initializePhysics();
function make(){return new Simulation([preset(7),preset(0)],{practice:true,hazards:false,ai:[false,false],autoUnstick:false});}
function pose(s:Simulation,pitch=0){const b=s.bots[0],q=axisQ(v(1,0,0),pitch);for(const[key,body]of b.bodies){body.setRotation(q,true);body.setTranslation(add(v(0,.49,3),rotate(bodyOrigin(b.compiled.config,key),q)),true);body.setLinvel(v(),true);body.setAngvel(v(),true);}s.world.propagateModifiedBodyPositionsToColliders();}
await test('HUGE uses two continuous wheel contacts while retaining its exact mass',()=>{const s=make();try{const b=s.bots[0],contacts=[...b.colliders].filter(([id])=>id.endsWith('_contact'));assert.equal(contacts.length,2);for(const[id,c]of b.colliders)if(id.startsWith('wheel_'))assert.equal(c.collisionGroups()!==0,id.endsWith('_contact'));assert(Math.abs(s.totalMass(b)-b.compiled.mass)<.001);return{continuousContacts:contacts.length,massKg:s.totalMass(b)};}finally{s.dispose();}});
await test('HUGE controls stay consistent across four body pitch orientations',()=>{const rows=[];for(const pitch of[0,Math.PI/2,Math.PI,-Math.PI/2])for(const direction of[-1,1]){const s=make();try{pose(s,pitch);const b=s.bots[0];for(let i=0;i<240;i++)s.step();const start={...b.chassis.translation()};let wrong=0;for(let i=0;i<240;i++){s.step([{...neutral(),left:.65*direction,right:.65*direction},neutral()]);if(b.driveSign!==1)wrong++;}const progress=dot(sub(b.chassis.translation(),start),v(0,0,-1))*direction;assert.equal(wrong,0);assert(progress>.2,JSON.stringify({pitch,direction,progress}));assert.equal(s.fault,undefined);rows.push({pitch,direction,progressM:progress});}finally{s.dispose();}}return rows;});
await test('Wheel damage and body rotation do not reverse or derate HUGE weapon power',()=>{const s=make();try{pose(s,Math.PI);const b=s.bots[0];b.weaponOn=true;for(let i=0;i<12*RULES.hz;i++)s.step();assert(b.rpm>1200);const before=b.rpm,weaponHP=b.modules.weapon.hp,bodyHP=b.modules.chassis.hp;for(const slot of['drive_left','drive_right']as const){const part=b.compiled.parts.find(p=>p.body.startsWith('wheel_')&&p.module===slot)!;s.damage(0,slot,1e6,undefined,part);assert(!b.modules[slot].functional);}for(let i=0;i<3*RULES.hz;i++){s.step();assert.equal(b.spinDirection,1);assert(b.weaponOn);}assert(b.rpm>before*.95);assert.equal(b.modules.weapon.hp,weaponHP);assert.equal(b.modules.chassis.hp,bodyHP);assert.equal(damageStatus(b.modules).weaponOutput,1);assert.equal(s.fault,undefined);return{beforeRPM:before,afterRPM:b.rpm,weaponOutput:1};}finally{s.dispose();}});
await test('Deep Six has the highest stock full-speed strike energy rating',()=>{const values=ROSTER.map((r,i)=>{const c=preset(i),b=compile(c);assert.equal(b.errors.length,0);return{name:r.name,rating:isSpinner(c.weapon)?.5*b.rotorInertia*(c.weapon.rpm*Math.PI/30)**2*strikeMultiplier(c):0,multiplier:strikeMultiplier(c)};});const strongest=values[9];assert.equal(strongest.multiplier,4);assert(values.every((v,i)=>i===9||strongest.rating>v.rating));return values.sort((a,b)=>b.rating-a.rating);});
// Momentum and energy budgets are covered by engagement-update.ts.
await test('All eleven result photos are embedded and mapped to both podium positions',()=>{for(let i=0;i<ROSTER.length;i++)for(const winner of[0,1]){const d=new JSDOM(podium([preset(i),preset((i+1)%11)],winner)).window.document;const images=[...d.querySelectorAll<HTMLImageElement>('.podium-portrait img')];assert.equal(images.length,2);for(const [j,img]of images.entries()){const index=[winner,1-winner][j]===0?i:(i+1)%11,profile=ROSTER[index].profile;assert.equal(img.dataset.robotPortrait,profile);assert.equal(img.getAttribute('src'),ROBOT_PORTRAITS[profile]);const bytes=Buffer.from(img.src.split(',')[1],'base64');assert.equal(bytes.subarray(0,4).toString(),'RIFF');assert.equal(bytes.subarray(8,12).toString(),'WEBP');assert(bytes.length>1000);}}return{photos:11,podiumCombinations:22};});

await test('HUGE turns in the requested direction upright and inverted',()=>{const rows=[];for(const pitch of[0,Math.PI])for(const direction of[-1,1]){const s=make();try{pose(s,pitch);for(let i=0;i<240;i++)s.step();for(let i=0;i<96;i++)s.step([{...neutral(),left:direction*.6,right:-direction*.6},neutral()]);const forward=s.forward(s.bots[0]);assert(forward.x*direction>.1,JSON.stringify({pitch,direction,forward}));assert.equal(s.fault,undefined);rows.push({pitch,direction,headingX:forward.x});}finally{s.dispose();}}return rows;});
await test('HUGE reverses away from both end walls without wheel interlocking',()=>{const rows=[];for(const end of[-1,1]){const s=make();try{const b=s.bots[0],q=axisQ(v(0,1,0),end<0?0:Math.PI);for(const[key,body]of b.bodies){body.setRotation(q,true);body.setTranslation(add(v(3,.49,end*6.3),rotate(bodyOrigin(b.compiled.config,key),q)),true);body.setLinvel(v(),true);body.setAngvel(v(),true);}s.world.propagateModifiedBodyPositionsToColliders();for(let i=0;i<300;i++)s.step([{...neutral(),left:.7,right:.7},neutral()]);const contact=b.chassis.translation().z;for(let i=0;i<300;i++)s.step([{...neutral(),left:-.7,right:-.7},neutral()]);const escaped=(contact-b.chassis.translation().z)*end;assert(escaped>.5,JSON.stringify({end,contact,escaped,p:b.chassis.translation(),up:s.axis(b,v(0,1,0)),forward:s.forward(b),grounded:b.grounded,energy:b.energy,hp:[b.modules.drive_left.hp,b.modules.drive_right.hp],wheels:[...b.bodies].filter(([id])=>id.startsWith('wheel_')).map(([id,body])=>({id,p:body.translation(),velocity:body.linvel(),omega:body.angvel()}))}));assert.equal(s.fault,undefined);rows.push({wall:end,escapeM:escaped});}finally{s.dispose();}}return rows;});

await test('HUGE POV follows the drive heading instead of body pitch',()=>{const s=make(),renderer=Object.create(ArenaRenderer.prototype),camera=new THREE.PerspectiveCamera();renderer.bodyGroups=new Map();renderer.replay=false;try{for(const pitch of[0,Math.PI/2,Math.PI,-Math.PI/2]){pose(s,pitch);renderer.positionPOVCamera(camera,s);const f=camera.getWorldDirection(new THREE.Vector3());assert(f.z<-.98);assert(camera.up.y>.99);assert(camera.position.y>.8);}return{pitchOrientations:4};}finally{s.dispose();}});
await test('A real HUGE blade hit scales damage by engagement and records rotor energy loss',()=>{const s=new Simulation([preset(7),preset(1)],{practice:true,hazards:false,ai:[false,false],autoUnstick:false});try{pose(s);const target=s.bots[1];for(const[key,body]of target.bodies){body.setRotation(axisQ(v(0,1,0),0),true);body.setTranslation(add(v(0,.18,2.15),bodyOrigin(target.compiled.config,key)),true);body.setLinvel(v(),true);body.setAngvel(v(),true);}const b=s.bots[0];b.weaponOn=true;b.rotor!.setAngvel(v(2400*Math.PI/30,0,0),true);for(const body of b.bodies.values())body.setLinvel(v(0,0,-2),true);s.world.propagateModifiedBodyPositionsToColliders();for(let i=0;i<120;i++)s.step();const hits=s.events.filter(e=>e.cause==='weapon'&&e.attacker===0&&e.allocations.some(a=>a.bot===1&&a.hp>0));assert(hits.length>0);assert(hits.every(e=>e.damageScale!>0&&e.damageScale!<=3));assert(hits.some(e=>e.rotorAfter[0]<e.rotorBefore[0]));assert.equal(s.fault,undefined);return{hits:hits.length,maximumDamageScale:Math.max(...hits.map(e=>e.damageScale!))};}finally{s.dispose();}});
