import {preset,v,add,sub,rotate,quatMul,axisQ,dot,length,MATERIALS,copy} from '../src/model';
import {Simulation,initializePhysics,neutral,RAPIER} from '../src/sim';
import {mkdirSync,writeFileSync} from 'node:fs';
await initializePhysics();mkdirSync('browser-evidence',{recursive:true});const rows:any[]=[];
for(const [label,ratio,motor,hub,grip]of [['stock',14,'drive48',false,false],['ratio-6.5',6.5,'drive48',false,false],['sport-8',8,'drive48sport',false,false],['sport-6.5',6.5,'drive48sport',false,false],['steel-hub-8',8,'drive48sport',true,false],['steel-hub-6.5',6.5,'drive48sport',true,false],['steel-hub-8-grip',8,'drive48sport',true,true]] as const){
 const config=preset(2);config.drive.ratio=ratio;config.drive.motor=motor;const hubMass=Math.PI*.040**2*.034*MATERIALS.hardox.density;if(hub)config.chassis.equipmentMassKg!-=hubMass*4;
 for(const mode of['forward','reverse','turn'] as const){const s=new Simulation([config,preset(0)],{practice:true,hazards:false,ai:[false,false],autoUnstick:false,recordVisuals:false,seed:42673});try{
  for(const id of[0,1]){const b=s.bots[id],origin=b.chassis.translation(),old=b.chassis.rotation(),inv={x:-old.x,y:-old.y,z:-old.z,w:old.w},q=axisQ(v(0,1,0),0),position=id===0?v(0,config.chassis.height/2+config.chassis.clearance+.008,mode==='reverse'?-3:3):v(5,.2,4);for(const body of b.bodies.values()){body.setTranslation(add(position,rotate(rotate(sub(body.translation(),origin),inv),q)),true);body.setRotation(quatMul(q,quatMul(inv,body.rotation())),true);body.setLinvel(v(),true);body.setAngvel(v(),true);}}
  const b=s.bots[0];for(const[id,body]of b.bodies)if(id.startsWith('wheel_')){if(hub)s.world.createCollider(RAPIER.ColliderDesc.cylinder(.034/2,.040).setRotation(axisQ(v(0,0,1),Math.PI/2)).setMass(hubMass).setSensor(true).setCollisionGroups(0),body);const I=body.principalInertia(),q=body.principalInertiaLocalFrame(),a=rotate(v(1,0,0),{x:-q.x,y:-q.y,z:-q.z,w:q.w}),wheel=I.x*a.x*a.x+I.y*a.y*a.y+I.z*a.z*a.z;b.driveInertia.set(id,1/(1/wheel+1/b.compiled.inertia.x));if(grip)b.colliders.get(id)!.setFrictionCombineRule(RAPIER.CoefficientCombineRule.Max);}
  s.world.propagateModifiedBodyPositionsToColliders();for(let i=0;i<240;i++)s.step();const start={...b.chassis.translation()},samples:any[]=[];let contacts=0,peak=0,turn=0;
  for(let i=0;i<480;i++){const command=mode==='forward'?{left:1,right:1}:mode==='reverse'?{left:-1,right:-1}:{left:1,right:-1};s.step([{...neutral(),...command},neutral()]);if(s.fault)throw Error(s.fault);const speed=Math.hypot(b.chassis.linvel().x,b.chassis.linvel().z);peak=Math.max(peak,speed);turn+=dot(b.chassis.angvel(),s.axis(b,v(0,1,0)))/240;let support=0;for(const[id,col]of b.colliders)if(/^wheel_-?1_\d$/.test(id))s.world.contactPairsWith(col,other=>{if(s.meta.get(other.handle)?.bot===null)support++;});contacts+=support;if(i%120===119)samples.push({seconds:(i+1)/240,speed,yaw:dot(b.chassis.angvel(),s.axis(b,v(0,1,0))),wheelSupport:support,height:b.chassis.translation().y,up:s.axis(b,v(0,1,0)).y,wheelOmega:[...b.bodies].filter(([id])=>id.startsWith('wheel_')).map(([,body])=>dot(sub(body.angvel(),b.chassis.angvel()),s.axis(b,v(1,0,0))))});}
  const row={label,mode,ratio,motor,hub,grip,mass:s.totalMass(b),distance:length(sub(b.chassis.translation(),start)),peakSpeed:peak,turnRadians:turn,meanWheelContacts:contacts/480,samples};rows.push(row);console.log(JSON.stringify(row));
 }finally{s.dispose();}}
}
writeFileSync('browser-evidence/hydra-drive-probe.json',JSON.stringify(rows,null,2));
