import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {preset,compile,parseConfig,copy,bodyOrigin,partProperties,v,canonical,encodeBuild,decodeBuild} from '../src/model';
import {hydraSleekWheels,hydraCoreRadius,hydraCoreWidth} from '../src/hydra-wheels';
import {initializePhysics,Simulation} from '../src/sim';
await initializePhysics();const c=preset(2),built=compile(c),before=JSON.parse(readFileSync('browser-evidence/original-mobility.json','utf8')),after=JSON.parse(readFileSync('browser-evidence/restored-mobility.json','utf8'));
assert.equal(c.drive.radius,.060);assert.equal(c.drive.width,.040);assert.equal(c.drive.ratio,8.3);assert.equal(c.drive.hydraTuning,3);assert(hydraSleekWheels(c));assert.deepEqual(built.errors,[]);assert(Math.abs(built.mass-113.2)<1e-6);assert(Math.abs((c.drive.ratio/c.drive.radius)/(before.drive.ratio/before.drive.radius)-1)<.02);
assert.equal(built.parts.filter(p=>/^wheel_-?1_\d+_hub$/.test(p.id)).length,4);assert.equal(built.parts.filter(p=>p.body.startsWith('wheel_')&&p.material==='rubber').length,128);
const origin=bodyOrigin(c,'wheel_1_0'),wheel=built.parts.filter(p=>p.body==='wheel_1_0'),inertia=wheel.reduce((sum,p)=>sum+partProperties(p).about(v(1,0,0),origin),0),originalMass=Math.PI*.1**2*.075*1100,originalInertia=.5*originalMass*.1**2;
assert(Math.abs(inertia/c.drive.radius**2/(originalInertia/.1**2)-1)<.05);assert(wheel.find(p=>p.id.endsWith('_hub'))!.material==='hardox');assert(Math.abs(hydraCoreRadius(c)-.055)<1e-8);assert(Math.abs(hydraCoreWidth(c)-.039)<1e-8);
for(const row of after.rows){console.log(JSON.stringify(row));const old=before.rows.find((r:any)=>r.mode===row.mode);assert(row.minUp>.95,row.mode+' remains upright');assert(row.meanWheelContacts>3.5,row.mode+' retains wheel support');if(row.mode==='forward'||row.mode==='reverse'){assert(row.finalSpeed>=old.finalSpeed*.97,row.mode+' retains speed');assert(row.distance>=old.distance*.95,row.mode+' retains acceleration');assert(row.samples[0].speed>=old.samples[0].speed*.95,row.mode+' retains launch response');assert(Math.abs(row.turnRadians)<.15);}if(row.mode==='left'||row.mode==='right'||row.mode==='arc'){assert(Math.abs(row.turnRadians)>=Math.abs(old.turnRadians)*.95,row.mode+' retains steering response');assert(Math.abs(row.turnRadians)<=Math.abs(old.turnRadians)*1.15,row.mode+' remains predictable');}if(row.mode==='arc')assert(row.finalSpeed>=old.finalSpeed*.95);if(row.mode==='stop')assert(row.finalSpeed<=Math.max(.10,old.finalSpeed+.05));if(row.mode==='transition')assert(row.finalSpeed>=old.finalSpeed*.95);console.log(JSON.stringify({mode:row.mode,largeWheelSpeed:old.finalSpeed,smallWheelSpeed:row.finalSpeed,largeWheelDistance:old.distance,smallWheelDistance:row.distance,largeWheelTurn:old.turnRadians,smallWheelTurn:row.turnRadians}));}
const old=copy(c);Object.assign(old.drive,{radius:.1,width:.075,ratio:14,hydraTuning:2});old.chassis.equipmentMassKg=41.35266615371938;const imported=parseConfig(old);assert.equal(imported.drive.radius,.060);assert.equal(imported.drive.width,.040);assert.equal(imported.drive.ratio,8.3);assert(Math.abs(compile(imported).mass-113.2)<1e-6);const custom=copy(c);Object.assign(custom.drive,{radius:.1,width:.075,ratio:14});assert.equal(parseConfig(custom).drive.radius,.1);assert.equal(parseConfig(custom).drive.ratio,14);assert.equal(canonical(decodeBuild(encodeBuild(custom))),canonical(custom));
const sim=new Simulation([c,preset(0)],{practice:true,hazards:false,ai:[false,false],autoUnstick:false});try{const b=sim.bots[0];assert(Math.abs(sim.totalMass(b)-built.mass)<.002);for(const[id,col]of b.colliders)if(id.endsWith('_contact'))assert.equal(col.mass(),0);for(let i=0;i<240;i++)sim.step();assert.equal(sim.fault,undefined);let anchorError=0;for(const[id,body]of b.bodies)if(id.startsWith('wheel_')){const p=bodyOrigin(c,id),q=b.chassis.rotation(),x=p.x*(1-2*(q.y*q.y+q.z*q.z))+p.y*2*(q.x*q.y-q.w*q.z)+p.z*2*(q.x*q.z+q.w*q.y),y=p.x*2*(q.x*q.y+q.w*q.z)+p.y*(1-2*(q.x*q.x+q.z*q.z))+p.z*2*(q.y*q.z-q.w*q.x),z=p.x*2*(q.x*q.z-q.w*q.y)+p.y*2*(q.y*q.z+q.w*q.x)+p.z*(1-2*(q.x*q.x+q.y*q.y)),root=b.chassis.translation(),actual=body.translation();anchorError=Math.max(anchorError,Math.hypot(actual.x-root.x-x,actual.y-root.y-y,actual.z-root.z-z));}assert(anchorError<.005);console.log(JSON.stringify({wheelInertia:inertia,roadInertia:inertia/c.drive.radius**2,originalRoadInertia:originalInertia/.1**2,stockMass:built.mass,anchorError,contactMassCountedOnce:true}));}finally{sim.dispose();}
