import assert from 'node:assert/strict';
import {writeFileSync} from 'node:fs';
import * as THREE from 'three';
import {preset,compile,parseConfig,copy,bodyOrigin,partProperties,flipEnergy,v,add,sub,rotate,quatMul,axisQ,RULES} from '../src/model';
import {hydraTineSamples} from '../src/hydra-geometry';
import {ArenaRenderer} from '../src/render';
import {initializePhysics,Simulation,RAPIER,colliderDesc,neutral} from '../src/sim';
await initializePhysics();const evidence:any[]=[];
const config=preset(2),built=compile(config),w=config.weapon;assert(w.type==='flipper');assert.deepEqual(built.errors,[]);assert(Math.abs(built.mass-113.2)<1e-6);assert.equal(config.chassis.height,.08);assert.equal(config.chassis.length,.64);assert.equal(config.chassis.width,.58);assert.equal(config.drive.layout,4);assert(!built.parts.some(p=>p.id==='wedge'||p.id==='flipper'||p.body.startsWith('ground_fork_')));assert.equal(built.parts.filter(p=>/^flipper_fang_-?1_\d$/.test(p.id)).length,12);assert.equal(built.parts.filter(p=>p.id.startsWith('flipper_tine_')).length,72);
const tips=[-1,0,1].map(side=>{const p=hydraTineSamples(config,side).at(-1)!;return{side,y:p.y+w.mount.y+config.chassis.height/2+config.chassis.clearance,z:p.z+w.mount.z,thickness:p.thickness};});assert(tips.every(p=>p.y-p.thickness>0&&p.y<.0011));assert(Math.abs(tips[0].z-tips[1].z-.020)<1e-8);evidence.push({geometry:'approved three tines and twelve wedgelets',mass:built.mass,tips,pivot:w.mount});
const world=new RAPIER.World(v());let moments=0;
try{for(const p of built.parts.filter(p=>p.collides)){const body=world.createRigidBody(RAPIER.RigidBodyDesc.dynamic());world.createCollider(colliderDesc(p),body);const props=partProperties(p);assert(Math.hypot(...Object.values(sub(props.centre,body.localCom())))<2e-5,p.id);for(const axis of[v(1,0,0),v(0,1,0),v(0,0,1)]){const q=body.principalInertiaLocalFrame(),a=rotate(axis,{x:-q.x,y:-q.y,z:-q.z,w:q.w}),I=body.principalInertia(),physical=I.x*a.x*a.x+I.y*a.y*a.y+I.z*a.z*a.z;assert(Math.abs(props.about(axis,props.centre)-physical)<Math.max(.00003,physical*.001),p.id);moments++;}world.removeRigidBody(body);}}finally{world.free();}evidence.push({physicalMassMoments:moments});
const context=new Proxy({}, {get:()=>()=>{}});Object.assign(globalThis,{document:{createElement:()=>({width:1,height:1,getContext:()=>context})}});
const renderer=Object.create(ArenaRenderer.prototype) as ArenaRenderer;Object.assign(renderer,{preview:new THREE.Group(),time:0});renderer.showBuilder(config);let triangles=0,tines=0,roofs=0;renderer.preview.traverse(o=>{if(o instanceof THREE.Mesh){const pos=o.geometry.getAttribute('position');assert([...pos.array].every(Number.isFinite));triangles+=(o.geometry.index?.count??pos.count)/3;if(o.name==='hydra-bronze-flipper-tine')tines++;if(o.name==='hydra-flat-snake-roof')roofs++;}});assert.equal(tines,3);assert.equal(roofs,2);assert(triangles<60000);renderer.clear(renderer.preview);evidence.push({renderedTriangles:triangles,tines,roofs});
const idle=new Simulation([config,preset(0)],{practice:true,hazards:false,ai:[false,false],autoUnstick:false,seed:42673});
try{const bot=idle.bots[0],other=idle.bots[1];for(let i=0;i<720;i++)idle.step();assert(bot.rpm<1);assert(!idle.flipOpportunity(bot).ready);const hp=other.modules.chassis.hp;assert(idle.requestFire(bot));assert(!idle.requestFire(bot));let peak=0,maxWork=0,anchorError=0;for(let i=0;i<600;i++){idle.step();assert.equal(idle.fault,undefined);peak=Math.max(peak,bot.flipAngle);maxWork=Math.max(maxWork,bot.flipWork);const anchor=add(bot.chassis.translation(),rotate(w.mount,bot.chassis.rotation()));anchorError=Math.max(anchorError,Math.hypot(...Object.values(sub(anchor,bot.rotor!.translation()))));}assert(peak>.7);assert(Math.abs(bot.flipAngle)<.08);assert.equal(bot.flipStart,-1);assert(maxWork<=flipEnergy(config)+.001);assert(anchorError<.025);assert.equal(other.modules.chassis.hp,hp);assert(Math.abs(idle.totalMass(bot)-built.mass)<.002);evidence.push({emptyCyclePeak:peak,maximumWork:maxWork,anchorError,noProximityDamage:true});}finally{idle.dispose();}
// Place the opponent over the three real tines. All subsequent lift uses contacts.
const contact=new Simulation([config,preset(0)],{practice:true,hazards:false,ai:[false,false],autoUnstick:false,seed:42673});
try{const bot=contact.bots[0],other=contact.bots[1];const place=(id:number,position:ReturnType<typeof v>,q:ReturnType<typeof axisQ>)=>{const b=contact.bots[id],origin=b.chassis.translation(),old=b.chassis.rotation(),inv={x:-old.x,y:-old.y,z:-old.z,w:old.w};for(const body of b.bodies.values()){body.setTranslation(add(position,rotate(rotate(sub(body.translation(),origin),inv),q)),true);body.setRotation(quatMul(q,quatMul(inv,body.rotation())),true);body.setLinvel(v(),true);body.setAngvel(v(),true);}};
 place(0,v(0,config.chassis.height/2+config.chassis.clearance+.008,0),axisQ(v(0,1,0),0));place(1,v(0,.235,-.410),axisQ(v(0,1,0),0));contact.world.propagateModifiedBodyPositionsToColliders();other.energy=0;let ready=false;for(let i=0;i<300;i++){contact.step();if(contact.flipOpportunity(bot).ready){ready=true;break;}}assert(ready,'The tines must produce the supported flip cue.');const before=other.chassis.translation().y;assert(contact.requestFire(bot));let peak=before,maxWork=0;for(let i=0;i<480;i++){contact.step();assert.equal(contact.fault,undefined);peak=Math.max(peak,other.chassis.translation().y);maxWork=Math.max(maxWork,bot.flipWork);}assert(peak>before+.10,'The supported target must rise through physical contact.');assert(maxWork<=flipEnergy(config)+.001);evidence.push({supportedContact:true,targetRise:peak-before,maximumWork:maxWork});}finally{contact.dispose();}
// Fixture placement only. Recovery starts after the inverted robot settles.
const recovery=new Simulation([config,preset(0)],{practice:true,hazards:false,ai:[false,false],autoUnstick:false,seed:42673});
try{const bot=recovery.bots[0],origin=bot.chassis.translation(),q=axisQ(v(0,0,1),Math.PI);for(const body of bot.bodies.values()){body.setTranslation(add(v(0,.45,0),rotate(sub(body.translation(),origin),q)),true);body.setRotation(quatMul(q,body.rotation()),true);}for(let i=0;i<240;i++)recovery.step();assert(recovery.axis(bot,v(0,1,0)).y<-.9);assert(recovery.requestSelfRight(bot));assert(!recovery.requestSelfRight(bot));let maxUp=-1,maxWork=0;const energy=bot.energy;for(let i=0;i<1440;i++){if(i===800)recovery.command(0,{...neutral(),selfRight:true});recovery.step();assert.equal(recovery.fault,undefined);maxUp=Math.max(maxUp,recovery.axis(bot,v(0,1,0)).y);maxWork=Math.max(maxWork,bot.flipWork);}assert(maxUp>.9,'Hydra must recover through its physical flipper.');assert(maxWork<=flipEnergy(config)+.001);assert(bot.energy<energy);evidence.push({physicalSelfRight:true,maxUp,maximumWork:maxWork,energySpent:energy-bot.energy});}finally{recovery.dispose();}
const legacy=copy(config);Object.assign(legacy.chassis,{height:.16,form:'wedge',equipmentMassKg:18.629719642711223});Object.assign(legacy.drive,{radius:.10,width:.075});legacy.weapon={...w,length:.30,thickness:.012,mount:v(0,.101,-.335)};const imported=parseConfig(legacy);assert.equal(imported.chassis.height,.08);assert.equal(imported.weapon.type,'flipper');assert.deepEqual(compile(imported).errors,[]);const custom=copy(config);custom.chassis.length=.70;const parsed=parseConfig(custom);assert.equal(parsed.chassis.length,.70);assert(compile(parsed).mass!==built.mass);evidence.push({legacyStockImport:true,customEditsRetained:true});
const misplaced=copy(config);if(misplaced.weapon.type==='flipper')misplaced.weapon.mount.x=.2;assert(compile(misplaced).errors.some(e=>e.field==='weapon.mount'));evidence.push({customHingeOverlapRejected:true});
writeFileSync('browser-evidence/hydra-physics.json',JSON.stringify({source:process.env.GITHUB_SHA,seed:42673,evidence},null,2));console.log(JSON.stringify(evidence,null,2));
