import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {mkdirSync,writeFileSync} from 'node:fs';
import WebSocket from 'ws';
import {createOnlineServer} from '../server/gateway';
import {preset} from '../src/model';
import {decodeFrame,type OnlineRoom,type OnlineFrame} from '../src/online/protocol';
import {closeStore} from '../server/store';
const delay=(ms:number)=>new Promise(r=>setTimeout(r,ms));
const sites=[createOnlineServer(),createOnlineServer()];const ports:number[]=[];for(const site of sites){await new Promise<void>(r=>site.server.listen(0,'127.0.0.1',r));ports.push((site.server.address() as any).port);}
type Client={socket:WebSocket,guest:string,cookie:string,rooms:OnlineRoom[],frames:OnlineFrame[],errors:string[]};
async function connect(port:number,cookie=''):Promise<Client>{const origin='http://127.0.0.1:'+port,response=await fetch(origin+'/api/online?session=1',{headers:{Origin:origin,...cookie?{Cookie:cookie}:{}}});assert(response.ok);const data=await response.json(),socket=new WebSocket('ws://127.0.0.1:'+port+'/api/online',['arena.v1','ticket.'+data.ticket],{headers:{Origin:origin}}),client:Client={socket,guest:data.guest,cookie:cookie||response.headers.get('set-cookie')!.split(';')[0],rooms:[],frames:[],errors:[]};socket.on('message',(raw,binary)=>{if(binary)client.frames.push(decodeFrame(new Uint8Array(raw as Buffer)));else{const value=JSON.parse(raw.toString());if(value.type==='room')client.rooms.push(value.room);if(value.type==='error')client.errors.push(value.message);}});await new Promise<void>((resolve,reject)=>{socket.once('open',()=>resolve());socket.once('error',reject);});return client;}
async function waitFor(fn:()=>boolean,description:string,ms=15000){const until=Date.now()+ms;while(Date.now()<until){if(fn())return;await delay(25);}throw Error('Timeout: '+description);}
const clients:Client[]=[];
try{const a=await connect(ports[0]),b=await connect(ports[1]);clients.push(a,b);a.socket.send(JSON.stringify({type:'create',mode:'duel',name:'Alice',config:preset(2),hazards:false}));await waitFor(()=>a.rooms.length>0,'created room');const room=a.rooms.at(-1)!;assert(/^[1-9]\d{3}$/.test(room.code));b.socket.send(JSON.stringify({type:'join',code:room.code,name:'Bob',config:preset(0)}));await waitFor(()=>a.rooms.at(-1)?.players.length===2&&b.rooms.length>0,'cross-gateway membership');a.socket.send(JSON.stringify({type:'ready',ready:true}));b.socket.send(JSON.stringify({type:'ready',ready:true}));await waitFor(()=>a.rooms.at(-1)?.players.every(p=>p.ready)===true,'ready state');a.socket.send(JSON.stringify({type:'start'}));await waitFor(()=>a.frames.at(-1)?.phase==='fight'&&b.frames.at(-1)?.phase==='fight','authoritative fight');const first=a.frames.at(-1)!,match=first.match;a.socket.send(JSON.stringify({type:'input',match,seq:1,left:.6,right:.6,actions:[]}));await waitFor(()=>a.frames.at(-1)!.ack[0]>=1,'input acknowledgment');a.socket.send(JSON.stringify({type:'input',match,seq:1,left:-1,right:-1,actions:[]}));await delay(300);assert.equal(a.frames.at(-1)!.ack[0],1);b.socket.send(JSON.stringify({type:'input',match,seq:1,left:0,right:0,actions:[{id:1,kind:'weapon'}]}));await waitFor(()=>b.frames.at(-1)!.actionAck[1]===1,'weapon action acknowledgment');const priorEpoch=a.frames.at(-1)!.epoch,priorTick=a.frames.at(-1)!.tick;a.socket.close(1012,'Network interruption');await delay(300);const resumed=await connect(ports[1],a.cookie);clients.push(resumed);assert.equal(resumed.guest,a.guest);resumed.socket.send(JSON.stringify({type:'join',code:room.code,expectedId:room.id,name:'Alice',config:preset(2)}));await waitFor(()=>resumed.rooms.length>0&&resumed.frames.length>0,'resumed seat and frame');assert.equal(resumed.rooms.at(-1)!.players.length,2);assert.equal(resumed.frames.at(-1)!.match,match);assert(resumed.frames.at(-1)!.tick>=priorTick-2);assert(resumed.frames.at(-1)!.epoch>=priorEpoch);resumed.socket.send(JSON.stringify({type:'input',match,seq:2,left:0,right:0,actions:[]}));await waitFor(()=>resumed.frames.at(-1)!.ack[0]>=2,'resumed controls');assert.deepEqual(resumed.errors,[]);mkdirSync('browser-evidence',{recursive:true});writeFileSync('browser-evidence/online-transport.json',JSON.stringify({source:process.env.GITHUB_SHA,roomDigits:4,independentGateways:2,authoritativeFight:true,duplicateInputIgnored:true,actionAcknowledged:true,resumedGuest:true,seatCount:2,resumedTick:resumed.frames.at(-1)!.tick},null,2));console.log('PASS cross-gateway rooms, controls, action deduplication, and session resumption');}finally{for(const client of clients)client.socket.close();await delay(100);for(const site of sites){await site.gateway.stop();await new Promise<void>(r=>site.server.close(()=>r()));}await closeStore();}
