import assert from 'node:assert/strict';
import {mkdirSync,writeFileSync} from 'node:fs';
import {randomUUID} from 'node:crypto';
import {preset,compile,copy,v,add,sub,rotate,axisQ,quatMul,RULES} from '../src/model';
import {Simulation,initializePhysics,neutral} from '../src/sim';
import {encodeFrame,decodeFrame,validateInput,validRoomCode} from '../src/online/protocol';
import {createRoom,joinRoom,setReady,startRoom,currentMatch,finishMatch,matchPlayers,advanceRepair,autoRepair} from '../server/rooms';
import {redis,key,acquire,renew,release,claimConnection,currentConnection,refreshPresence,closeStore} from '../server/store';
import {saveSimulation,restoreSimulation} from '../server/checkpoint';
import {matchFrame} from '../server/frames';
await initializePhysics();mkdirSync('browser-evidence',{recursive:true});const evidence:any[]=[];
assert(validRoomCode('1000'));assert(validRoomCode('9999'));for(const code of['0001','123','10000','12x4',1234])assert(!validRoomCode(code));
const rooms=await Promise.all(Array.from({length:12},(_,i)=>createRoom(randomUUID(),'duel','Host '+i,preset(i%11),false)));assert.equal(new Set(rooms.map(r=>r.code)).size,12);evidence.push({uniqueFourDigitRooms:12});
const a=randomUUID(),b=randomUUID(),c=randomUUID();let room=await createRoom(a,'duel','Alice',preset(2),false);await joinRoom(b,room.code,'Bob',preset(0));await assert.rejects(()=>joinRoom(c,room.code,'Extra',preset(1)),/full/);await assert.rejects(()=>startRoom(room.id,b),/host/);await assert.rejects(()=>startRoom(room.id,a),/ready/);await setReady(room.id,a,true);await setReady(room.id,b,true);room=await startRoom(room.id,a);assert.equal(room.entrants.length,2);assert.equal(currentMatch(room)!.status,'active');evidence.push({duelCapacity:true,hostStart:true,readyRequired:true});
const match=currentMatch(room)!,lease=await acquire(match.id);assert(lease);assert.equal(await acquire(match.id),undefined);assert(await renew(match.id,lease.token));assert(!await renew(match.id,'wrong'));const epoch1=await claimConnection(room.id,a),epoch2=await claimConnection(room.id,a);assert(!await currentConnection(room.id,a,epoch1));assert(await currentConnection(room.id,a,epoch2));assert(!await refreshPresence(room.id,a,epoch1));assert(await refreshPresence(room.id,a,epoch2));evidence.push({exclusiveMatchOwner:true,resumedSeatFenced:true});await release(match.id,lease.token);
for(const count of[1,2,5,8]){const ids=Array.from({length:count},()=>randomUUID());let r=await createRoom(ids[0],'tournament','Player 0',preset(0),false);for(let i=1;i<count;i++)await joinRoom(ids[i],r.code,'Player '+i,preset(i%11));for(const id of ids)await setReady(r.id,id,true);r=await startRoom(r.id,ids[0]);assert.equal(r.entrants.length,8);assert.equal(r.entrants.filter(p=>p.ai).length,8-count);assert.equal(r.rounds[0].length,4);let finished=0;while(r.phase!=='finished'){if(r.phase==='repair'){r.repairUntil=0;await redis().set(key('room:'+r.id),JSON.stringify(r),'EX',3600);r=await advanceRepair(r.id);continue;}const m=currentMatch(r)!,token=await acquire(m.id);assert(token);const configs=matchPlayers(r).map(p=>p.config),sim=new Simulation(configs as any,{practice:false,hazards:false,ai:[false,false],recordVisuals:false});try{sim.finish('Decision',0);r=await finishMatch(r.id,m.id,token.token,sim.result!,sim.bots.map(b=>b.modules));finished++;}finally{sim.dispose();await release(m.id,token.token);}}assert.equal(finished,7);assert.equal(r.rounds.length,3);assert(r.champion);evidence.push({humans:count,aiFill:8-count,completedMatches:finished});}
for(const pair of[[2,0],[10,1],[8,5]] as const){const sim=new Simulation([preset(pair[0]),preset(pair[1])],{practice:true,hazards:true,ai:[false,false],seed:42673,recordVisuals:false,autoUnstick:false});let restored:Simulation|undefined;try{for(let i=0;i<240;i++)sim.step([{...neutral(),left:.25,right:.25,weapon:i===20},neutral()]);const encoded=saveSimulation(sim);restored=await restoreSimulation(encoded);assert.deepEqual(restored.snapshot(),sim.snapshot());for(let i=0;i<120;i++){const commands=[{...neutral(),left:.1,right:.1},neutral()] as any;sim.step(commands);restored.step(commands);assert.equal(sim.fault,undefined);assert.equal(restored.fault,undefined);for(const side of[0,1]){const p=sim.bots[side].chassis.translation(),q=restored.bots[side].chassis.translation();assert(Math.hypot(p.x-q.x,p.y-q.y,p.z-q.z)<.005);assert(Math.abs(sim.bots[side].energy-restored.bots[side].energy)<2);}}const frame=matchFrame(sim,randomUUID(),1,1,'fight',0,[10,11],[4,5]),bytes=encodeFrame(frame),decoded=decodeFrame(bytes);assert.equal(decoded.tick,frame.tick);assert.equal(decoded.bodies.length,frame.bodies.length);assert.equal(decoded.ack[1],11);evidence.push({pair,checkpointBytes:encoded.length,frameBytes:bytes.length,recoveryPoseWithinMm:5});}finally{sim.dispose();restored?.dispose();}}
assert.throws(()=>validateInput({type:'input',match:'x',seq:1,left:NaN,right:0,actions:[]}));assert.throws(()=>validateInput({type:'input',match:'x',seq:1,left:2,right:0,actions:[]}));assert.throws(()=>validateInput({type:'input',match:'x',seq:1,left:0,right:0,actions:[{id:1,kind:'weapon'},{id:1,kind:'weapon'}]}));evidence.push({invalidControlsRejected:true,duplicateActionsRejected:true});
writeFileSync('browser-evidence/online-core.json',JSON.stringify({source:process.env.GITHUB_SHA,evidence},null,2));console.log(JSON.stringify(evidence,null,2));await closeStore();
