import assert from 'node:assert/strict';
import {mkdirSync,writeFileSync} from 'node:fs';
import {impactEnergy,normalKineticEnergy} from '../src/impact-energy';
import {WallDamage,WALL_DAMAGE} from '../src/wall-damage';
import {fractureLines} from '../src/wall-fracture';
import {WallCrackVisual} from '../src/wall-cracks';
import {initializePhysics,Simulation,neutral} from '../src/sim';
import {preset,bodyOrigin,identity,v,add,isSpinner,weaponAxis,mul,RULES} from '../src/model';
mkdirSync('browser-evidence',{recursive:true});
const slow=normalKineticEnergy(113.2,113.2,2),fast=normalKineticEnergy(113.2,113.2,4);assert.equal(fast,slow*4);assert.equal(normalKineticEnergy(113.2,0,2),226.4);
const stationary=impactEnergy({impulse:50,closing:10,translationClosing:0,translationBudget:0,spinSpeed:10,spinWork:50}),moving=impactEnergy({impulse:50,closing:14,translationClosing:4,translationBudget:100,spinSpeed:10,spinWork:50});assert.equal(stationary.total,50);assert.equal(moving.translation,100);assert.equal(moving.total,150);assert(moving.total<=moving.solved);
for(let speed=0;speed<=20;speed++)for(let impulse=0;impulse<=1000;impulse+=50){const e=impactEnergy({impulse,closing:20+speed,translationClosing:speed,translationBudget:normalKineticEnergy(113.2,113.2,speed),spinSpeed:20,spinWork:1000});assert(e.total<=e.solved+1e-8);assert(e.translation<=normalKineticEnergy(113.2,113.2,speed)+1e-8);assert.equal(e.total,e.translation+e.rotation+e.other);}
const wall=new WallDamage(),patterns=[];for(const[energy,tick]of[[250,0],[2000,100],[8000,200],[30000,300]]){assert(wall.impact('north',v(tick/100,2,-7),energy,100,tick,v(4,1,-8)));const crack=wall.cracks.at(-1)!;patterns.push(crack.pattern);const lines=fractureLines(crack);assert(lines.length<=WALL_DAMAGE.maxSegments);assert.deepEqual(lines,fractureLines(JSON.parse(JSON.stringify(crack))));assert.notDeepEqual(lines,fractureLines({...crack,seed:crack.seed!+1}));}assert.deepEqual(patterns,['hairline','starburst','branching','fracture']);assert(fractureLines(wall.cracks[3]).length>fractureLines(wall.cracks[0]).length);
const visual=new WallCrackVisual();visual.update(wall.cracks);assert(visual.geometry.drawRange.count>0);for(let tick=400;tick<6000;tick+=100)wall.impact('east',v(7,3,tick%500/100),30000,300,tick);assert.equal(wall.cracks.length,48);visual.update(wall.cracks);assert(visual.geometry.drawRange.count<=48*72*2);const positions=visual.geometry.getAttribute('position');for(let i=0;i<visual.geometry.drawRange.count;i++){assert(Number.isFinite(positions.getX(i)));assert(Number.isFinite(positions.getY(i)));assert(Number.isFinite(positions.getZ(i)));assert(positions.getY(i)>=.35&&positions.getY(i)<=RULES.wallHeight);}visual.geometry.dispose();(visual.material as any).dispose();
await initializePhysics();
function pose(s:Simulation,id:number,p:ReturnType<typeof v>){const bot=s.bots[id];for(const[key,body]of bot.bodies){body.setTranslation(add(p,bodyOrigin(bot.compiled.config,key)),true);body.setRotation(identity,true);body.setLinvel(v(),true);body.setAngvel(v(),true);}s.world.propagateModifiedBodyPositionsToColliders();}
const impacts=[];
for(const speed of[2,5]){const s=new Simulation([preset(0),preset(10)],{practice:true,hazards:false,ai:[false,false],autoUnstick:false});try{s.world.gravity=v();pose(s,0,v(0,3,1.8));pose(s,1,v(0,3,.1));const b=s.bots[0],w=b.compiled.config.weapon;assert(isSpinner(w));b.energy=0;b.weaponOn=false;b.rotor!.setAngvel(mul(weaponAxis(w),w.rpm*Math.PI/30),true);for(const body of b.bodies.values())body.setLinvel(v(0,0,-speed),true);for(let tick=0;tick<300;tick++){s.step();if(s.events.some(e=>e.attacker===0&&e.translationEnergy!>0))break;}assert.equal(s.fault,undefined);const e=s.events.find(e=>e.attacker===0&&e.translationEnergy!>0);if(!e)console.log(JSON.stringify({speed,positions:s.bots.map(b=>b.chassis.translation()),events:s.events.map(e=>({attacker:e.attacker,cause:e.cause,energy:e.energy,motion:e.translationEnergy,rotation:e.rotationalEnergy,robotSpeed:e.robotSpeed}))}));assert(e,'Moving spinner must record translation energy.');assert(Math.abs((e.translationEnergy??0)+(e.rotationalEnergy??0)+(e.otherContactEnergy??0)-e.energy)<.001);assert(e.robotSpeed![0]>0);impacts.push({speed,translationJ:e.translationEnergy,rotationJ:e.rotationalEnergy,energyJ:e.energy,hp:e.allocations.reduce((n,a)=>n+a.hp,0)});}finally{s.dispose();}}
const seeded=[];for(const pair of[[0,10],[2,9],[7,8]] as const){const s=new Simulation([preset(pair[0]),preset(pair[1])],{practice:true,hazards:true,ai:[true,true],seed:528710+pair[0],autoUnstick:false,recordVisuals:false});try{for(let tick=0;tick<7200;tick++)s.step();assert.equal(s.fault,undefined);assert(s.bots.every(b=>Number.isFinite(b.rpm)&&b.energy>=0));assert(s.events.some(e=>e.allocations.some(a=>a.hp>0)));seeded.push({robots:pair,ticks:s.tick,events:s.events.length});}finally{s.dispose();}}
writeFileSync('browser-evidence/polish-physics.json',JSON.stringify({status:'passed',speedSquared:true,finiteSolvedBudget:true,realRapierImpacts:impacts,seeded,patterns,replayDeterministic:true,boundedWallGeometry:true},null,2));console.log('PASS motion energy, real Rapier impacts, seeded fights, and deterministic wall fractures');
