import assert from 'node:assert/strict';
import {writeFileSync,readFileSync} from 'node:fs';
import {RULES,flipEnergy,SLOTS,MATERIALS,preset,compile,parseConfig,copy,canonical,encodeBuild,decodeBuild,v,add,sub,mul,length,dot,rotate,axisQ,quatMul,identity,type BotConfig,type Slot} from '../src/model';
import {initializePhysics,Simulation,RAPIER,FixedClock,neutral,panelLoss,assignPoints,Tournament,repairQuote,workLimitedTorque,type Command} from '../src/sim';
import {collisionCases} from './collision';

type Check={name:string,gate:string,status:'passed'|'failed',detail:unknown,ms:number};
const filter=process.env.CRA_TEST_FILTER;const checks:Check[]=filter?JSON.parse(readFileSync('docs/test-results.json','utf8')).checks.filter((c:Check)=>!c.name.includes(filter)):[],started=performance.now();
async function check(gate:string,name:string,fn:()=>unknown|Promise<unknown>){if(filter&&!name.includes(filter))return;const t=performance.now();try{const detail=await fn();checks.push({name,gate,status:'passed',detail,ms:performance.now()-t});console.log('PASS',gate,name,JSON.stringify(detail??''));}catch(e){checks.push({name,gate,status:'failed',detail:e instanceof Error?e.stack:String(e),ms:performance.now()-t});console.log('FAIL',gate,name,e instanceof Error?e.message:String(e));}writeFileSync('docs/test-results.json',JSON.stringify({date:new Date().toISOString(),settings:RULES,checks,elapsedMs:performance.now()-started},null,2));}
const make=(a=0,b=1,opt:any={})=>new Simulation([preset(a),preset(b)],{hazards:false,practice:true,ai:[false,false],...opt});
function position(s:Simulation,id:number,x:number,y:number,z:number){const b=s.bots[id],d=sub(v(x,y,z),b.chassis.translation());for(const body of b.bodies.values())body.setTranslation(add(body.translation(),d),true);}
function run(s:Simulation,ticks:number,commands?:(tick:number)=>[Command,Command]){for(let n=0;n<ticks&&!s.result&&!s.fault;n++)s.step(commands?.(n));assert.equal(s.fault,undefined);}
await initializePhysics();

await check('G02','Three legal presets; part mass equals physics mass',()=>{const out=[];for(let i=0;i<3;i++){const c=compile(preset(i));assert.deepEqual(c.errors,[]);const s=make(i,0),m=s.totalMass(s.bots[0]);assert(Math.abs(m-c.mass)<.0001);assert.equal(SLOTS.length,12);out.push({name:c.config.identity.name,mass:c.mass,physicsMass:m,parts:c.parts.length,spinup:c.spinup});s.dispose();}return out;});
await check('G02','Armour, battery, magnets and absent slots affect physical totals',()=>{const base=preset(0),c=compile(base),battery=copy(base),magnet=copy(base),armour=copy(base);battery.battery.capacityWh+=180;magnet.drive.magnet+=80;armour.armour.find(a=>a.mount==='top')!.thickness=0;assert(Math.abs(compile(battery).mass-c.mass-1)<1e-8);assert(Math.abs(compile(magnet).mass-c.mass-1)<1e-8);const absent=compile(armour);assert.equal(absent.modules.armour_top.present,false);assert(!absent.parts.some(p=>p.module==='armour_top'));return{batteryDelta:1,magnetDelta:1,removedTopMass:c.mass-absent.mass};});

await check('G03','Tick-stamped inputs at 30, 60 and 144 render FPS',()=>{const snapshots=[];for(const fps of[30,60,144]){const s=make(0,2),clock=new FixedClock();for(let frame=0;frame<fps*3;frame++)clock.advance(1/fps,()=>{const tick=s.tick;const cmd={left:tick<240?.5:tick<480?-.25:0,right:tick<240?.5:tick<480?.25:0,weapon:tick===1,selfRight:false};s.step([cmd,neutral()]);});assert.equal(s.tick,3*RULES.hz);snapshots.push(JSON.stringify(s.snapshot()));s.dispose();}assert.equal(snapshots[0],snapshots[1]);assert.equal(snapshots[0],snapshots[2]);return{ticks:3*RULES.hz,frameRates:[30,60,144],identical:true};});
await check('G03','Manual pause freezes time; frame hitches resume with bounded fixed steps',()=>{const s=make(),c=new FixedClock();run(s,240);const state=JSON.stringify(s.snapshot());c.pause();for(let i=0;i<100;i++)c.advance(.02,()=>s.step());assert.equal(JSON.stringify(s.snapshot()),state);c.resume();const before=s.tick;assert.equal(c.advance(.8,()=>s.step()),RULES.maxSteps);assert.equal(c.paused,false);assert.equal(s.tick-before,RULES.maxSteps);for(let i=0;i<3;i++)c.advance(.12,()=>s.step());assert.equal(c.paused,false);assert(c.accumulator<RULES.dt);s.dispose();return{pauseStable:true,hitchDoesNotPause:true,maxSteps:RULES.maxSteps};});
await check('G03','Airborne wheels and magnets do not translate the chassis horizontally',()=>{const s=make();position(s,0,0,4,0);const b=s.bots[0],x=b.chassis.translation().x,z=b.chassis.translation().z;run(s,80,()=>[{left:1,right:1,weapon:false,selfRight:false},neutral()]);assert(!b.grounded);const d=Math.hypot(b.chassis.translation().x-x,b.chassis.translation().z-z);assert(d<.008);assert(b.chassis.translation().y>3);s.dispose();return{horizontalDrift:d};});

await check('G04','200 isolated hits and 200 near misses, unchanged high-speed cases',()=>{const result=collisionCases(RULES.hz,RULES.ccdSubsteps);assert.equal(result.hitPass,200);assert.equal(result.nearPass,200);assert.equal(result.failures.length,0);return{hz:result.hz,hits:result.hitPass,nearMisses:result.nearPass,file:`contact-cases-${RULES.hz}hz.json`};});

await check('G05','Free-space momentum and total kinetic energy in 24 impacts',()=>{const out=[];for(let i=0;i<24;i++){const world=new RAPIER.World(v());world.timestep=RULES.dt;world.numSolverIterations=RULES.solverIterations;world.maxCcdSubsteps=1;const bodies=[];for(let j=0;j<2;j++){const body=world.createRigidBody(RAPIER.RigidBodyDesc.dynamic().setTranslation(j?.8:-.8,j?.04:0,0).setLinvel(j?-1:2+i*.1,0,0).setAngvel(v(.3*j,.2*(i%3),.3)).setCcdEnabled(true));world.createCollider(RAPIER.ColliderDesc.cuboid(.25,.20,.23).setMass(j?45+i:60).setFriction(.3).setRestitution(.1).setContactSkin(.001),body);bodies.push(body);}const momentum=()=>bodies.reduce((s,b)=>add(s,mul(b.linvel(),b.mass())),v());const energy=()=>bodies.reduce((s,b)=>{const I=b.principalInertia(),q=quatMul(b.rotation(),b.principalInertiaLocalFrame()),local=rotate(b.angvel(),{x:-q.x,y:-q.y,z:-q.z,w:q.w});return s+.5*b.mass()*dot(b.linvel(),b.linvel())+.5*(I.x*local.x**2+I.y*local.y**2+I.z*local.z**2);},0);const p0=momentum(),e0=energy();for(let n=0;n<360;n++)world.step();const p1=momentum(),e1=energy(),momentumError=length(sub(p1,p0))/length(p0),energyRatio=e1/e0;assert(momentumError<=.01);assert(energyRatio<=1.02);out.push({case:i,momentumError,energyRatio});world.free();}writeFileSync('docs/momentum-cases.json',JSON.stringify(out,null,2));return{cases:24,maxMomentumError:Math.max(...out.map(x=>x.momentumError)),maxEnergyRatio:Math.max(...out.map(x=>x.energyRatio))};});

await check('G06','10 kJ removes exactly 80 of 400 HP from the reference steel panel',()=>{assert.equal(panelLoss(10000,125,400),80);const s=make();s.bots[1].modules.armour_front={id:'armour_front',present:true,max:400,hp:400,material:'hardox',functional:true};s.damage(1,'armour_front',10000);assert.equal(s.bots[1].modules.armour_front.hp,320);assert.equal(s.bots[1].modules.chassis.hp,1800);s.damage(1,'armour_front',45000);assert.equal(s.bots[1].modules.armour_front.hp,0);assert(Math.abs(s.bots[1].modules.chassis.hp-(1800-5000/70))<1e-6);s.dispose();return{before:400,after:320,lossPercent:20,excessRouting:true};});
await check('G06','Drive failures disable traction; protected weapons survive until structural KO',()=>{const s=make(0,1,{practice:false});const b=s.bots[0];s.damage(0,'drive_left',1e9);s.damage(0,'drive_right',1e9);assert(!b.modules.drive_left.functional&&!b.modules.drive_right.functional);s.step();assert.equal(s.result,undefined);s.damage(0,'weapon_actuator',1e9);b.command.weapon=true;s.step();assert(b.modules.weapon_actuator.functional);assert.notEqual(b.actuatorTorque,0);s.damage(0,'battery',1e9);assert(!s.powered(b));s.damage(0,'chassis',1e9);s.step();assert.equal(s.result?.reason,'Structural KO');assert.equal(s.result?.winner,1);s.dispose();return{driveFailure:true,actuatorProtected:true,batteryFailure:true,structuralKO:true};});
await check('G06','Detached armour transfers mass and carries parent point velocity',()=>{const s=make();run(s,60);const b=s.bots[0],before=s.totalMass(b);s.damage(0,'armour_left',1e7);run(s,1);const after=s.totalMass(b),debrisMass=s.debris.reduce((n,d)=>n+d.body.mass(),0);assert(Math.abs(before-after-debrisMass)<.0001);assert(s.debris.length===1);const groups=s.debris[0].body.collider(0).collisionGroups();assert.equal(groups,(8<<16)|1);s.dispose();return{before,after,debrisMass,noCombatantCollision:true};});
await check('G06','Battery never increases through reverse drive or braking',()=>{const s=make();const b=s.bots[0];let previous=b.energy;run(s,1000,t=>{const throttle=t<300?.9:t<700?-.9:0;assert(b.energy<=previous+1e-9);previous=b.energy;return[{left:throttle,right:throttle,weapon:t===0,selfRight:false},neutral()];});b.energy=.001;run(s,10,()=>[{left:1,right:1,weapon:false,selfRight:false},neutral()]);assert.equal(b.energy,0);s.dispose();return{nonIncreasing:true,minimum:0};});

await check('G07','Physical flipper overturns an equal-mass target within its work allowance',()=>{const f=preset(2),target=preset(0),mass=compile(f).mass;target.weapon={type:'none'};Object.assign(target.chassis,{length:.64,width:.58,height:.16,clearance:.018});Object.assign(target.drive,{layout:4,radius:.10,width:.075});let low=.004,high=.020;for(let i=0;i<35;i++){target.chassis.thickness=(low+high)/2;if(compile(target).mass>mass)high=target.chassis.thickness;else low=target.chassis.thickness;}const s=new Simulation([f,target],{practice:true,hazards:false,ai:[false,false]});assert(Math.abs(s.totalMass(s.bots[0])-s.totalMass(s.bots[1]))<.001,'The target fixture must start at equal mass');position(s,0,-.7,s.bots[0].chassis.translation().y,0);position(s,1,.7,s.bots[1].chassis.translation().y,0);s.bots[1].energy=0;let maxHeight=0,minUp=1;run(s,1500,t=>{const b=s.bots[1];maxHeight=Math.max(maxHeight,b.chassis.translation().y);minUp=Math.min(minUp,s.axis(b,v(0,1,0)).y);return[{left:t<450?.3:0,right:t<450?.3:0,weapon:t===450,selfRight:false},neutral()];});assert(maxHeight>.35);assert(minUp<-.7);assert(s.bots[0].flipWork<=flipEnergy(s.bots[0].compiled.config)+.001);assert.equal(s.bots[0].charges,f.weapon.type==='flipper'?f.weapon.charges:0);const out={mass,maxHeight,minUp,work:s.bots[0].flipWork,charges:s.bots[0].charges};s.dispose();return out;});
await check('G07','Missed flips consume charges, cooldown rejects duplicates, work remains bounded',()=>{const c=preset(2);c.chassis.profile='standard';const s=new Simulation([c,c],{practice:true,hazards:false,ai:[false,false]}),b=s.bots[0];assert(s.requestFire(b));assert.equal(b.charges,7);assert(!s.requestFire(b));run(s,400);assert(b.flipWork<=RULES.flipJoules+.001);b.charges=0;assert(!s.requestFire(b));b.charges=1;s.damage(0,'weapon_actuator',1e7);assert(!s.requestFire(b));for(const remaining of[0,.001,1,100,3000]){const limited=workLimitedTorque(2600,5,1,.001+remaining);assert(limited.work<=remaining+.001001);}s.dispose();return{missedShotCostsOne:true,rejectedDuplicates:true};});
await check('G07','Travel records agree with recorded positions and pause does not sample',()=>{const s=make();run(s,60);const b=s.bots[0];const event={id:999};(s as any).openTravel(0,event,'Post-impact travel');b.chassis.setLinvel(v(2,.4,0),true);run(s,240);const t=s.tracking.get(0)??s.travels.at(-1)!;const exact=Math.hypot(t.final.x-t.origin.x,t.final.z-t.origin.z);assert(Math.abs(t.horizontal-exact)<1e-9);assert(t.path>=t.horizontal-.00001);const old=JSON.stringify(t);const clock=new FixedClock();clock.pause();for(let i=0;i<30;i++)clock.advance(.016,()=>s.step());assert.equal(JSON.stringify(t),old);(s as any).openTravel(0,{id:1000},'Post-impact travel');s.closeTravel(0,'New impact');assert.equal(s.travels.at(-1)?.reason,'New impact');s.dispose();return{horizontal:t.horizontal,exact,max:t.maxHorizontal,path:t.path,pauseStable:true};});

await check('G08','Disabled from rest counts out after 10 seconds; simultaneous failures decide once',()=>{const s=make(0,1,{practice:false});s.bots[0].energy=0;s.bots[1].energy=0;run(s,10*RULES.hz);assert.equal(s.result?.reason,'Double stoppage');assert.equal(s.result?.tick,10*RULES.hz);const json=JSON.stringify(s.result);s.step();assert.equal(JSON.stringify(s.result),json);s.dispose();const last=make(0,1,{practice:false});last.tick=RULES.matchTicks-1;last.damage(0,'chassis',1e7);last.step();assert.equal(last.result?.reason,'Structural KO');assert.equal(last.result?.winner,1);last.dispose();return{countoutTicks:10*RULES.hz,lastTickTerminalFirst:true};});
await check('G08','All category decisions allocate exactly 11 integer points',()=>{for(let i=0;i<1000;i++){const a=[(i%7)/7,(i%13)/13,(i%17)/17],b=[((i+3)%7)/7,((i+4)%13)/13,((i+5)%17)/17],x=assignPoints([a,b],i%2);assert.equal(x.scores.flat().reduce((s,n)=>s+n,0),11);assert(x.scores.flat().every(Number.isInteger));}const tied=assignPoints([[0,0,0],[0,0,0]],0);assert.equal(tied.ties.length,3);return{cases:1000,ties:tied};});
await check('G08','Carried damage is excluded from new match damage',()=>{const s=make();s.bots[0].modules.chassis.hp=1300;s.bots[0].startHP.chassis=1300;assert.equal(s.normalizedDamage(s.bots[0]),0);s.damage(0,'chassis',7000);assert(s.normalizedDamage(s.bots[0])>0);s.dispose();return{carriedChassisLoss:500,newLossOnly:true};});

await check('G10','50 malformed builds are rejected and canonical Unicode links round-trip',()=>{const mutations:((c:any)=>void)[]=[c=>c.schemaVersion=1,c=>c.schemaVersion=3,c=>c.identity.name='x'.repeat(25),c=>c.identity.primary='red',c=>c.identity.secondary='#fff',c=>c.chassis.length=-1,c=>c.chassis.width=Infinity,c=>c.chassis.height=NaN,c=>c.chassis.thickness=.001,c=>c.chassis.material='iron',c=>c.chassis.clearance=0,c=>c.weapon.type='laser_cannon',c=>c.weapon.teeth=13,c=>c.weapon.teeth=1.2,c=>c.weapon.radius=-1,c=>c.weapon.innerRadius=-.1,c=>c.weapon.innerRadius=.34,c=>c.weapon.rpm=0,c=>c.weapon.ratio=-1,c=>c.weapon.mount.x=100,c=>c.drive.layout=8,c=>c.drive.radius=.001,c=>c.drive.magnet=401,c=>c.battery.capacityWh=99,c=>c.armour[1].mount='front'];let rejected=0;for(let i=0;i<50;i++){const c=copy(preset(0));mutations[i%mutations.length](c);assert.throws(()=>parseConfig(c));rejected++;}assert.throws(()=>decodeBuild('A'.repeat(16385)));assert.throws(()=>decodeBuild('%garbage'));const c=preset(0);c.identity.name='鋼鉄 🤖 <test>';const d=decodeBuild(encodeBuild(c));assert.equal(canonical(c),canonical(d));assert.equal(encodeBuild(c),encodeBuild(d));const poison=JSON.parse(canonical(c));poison.identity.__proto__={polluted:true};assert.throws(()=>parseConfig(poison));return{malformedRejected:rejected,unicodeRoundTrip:true,encodedLimit:16384,prototypeRejected:true};});
await check('G10','Numeric limits, envelopes, mount interference and speed are enforced',()=>{const base=preset(0);const settings:{path:string,low:number,high:number}[]=[{path:'chassis.length',low:.2,high:1.2},{path:'chassis.width',low:.22,high:1.3},{path:'chassis.height',low:.08,high:.45},{path:'chassis.thickness',low:.004,high:.02},{path:'chassis.clearance',low:.003,high:.65},{path:'drive.radius',low:.05,high:.6},{path:'drive.magnet',low:0,high:400},{path:'battery.capacityWh',low:100,high:1000},{path:'weapon.radius',low:.1,high:.85}];let cases=0;for(const setting of settings)for(const side of['low','high'] as const){const [a,b]=setting.path.split('.'),c:any=copy(base);c[a][b]=setting[side];assert.doesNotThrow(()=>parseConfig(c));c[a][b]+=side==='low'?-.00001:.00001;assert.throws(()=>parseConfig(c));cases+=2;}const speed=copy(base);if(speed.weapon.type==='horizontal_bar')speed.weapon.rpm=12000;assert(compile(speed).errors.some(e=>e.field==='weapon.rpm'));const overlap=copy(base);if(overlap.weapon.type!=='none')overlap.weapon.mount=v(0,0,0);assert(compile(overlap).errors.some(e=>e.field==='weapon.mount'));const wide=copy(base);wide.chassis.length=1.2;if(wide.weapon.type==='horizontal_bar'){wide.weapon.radius=.85;wide.weapon.mount=v(0,.15,1);}assert(compile(wide).errors.some(e=>e.field==='envelope'));return{boundaryAssertions:cases,speed:true,overlap:true,envelope:true};});

await check('G11','Repair budget, replacements, absent slots and atomic staging',()=>{const s=make(),modules=copy(s.bots[0].modules);modules.chassis.hp=800;modules.drive_left.hp=0;assert.throws(()=>repairQuote(modules,[{module:'chassis',kind:'repair',amount:901}]));assert.throws(()=>repairQuote(modules,[{module:'drive_left',kind:'repair',amount:1}]));assert.throws(()=>repairQuote(modules,[{module:'self_right',kind:'replace',amount:0}]));const original=JSON.stringify(modules),q=repairQuote(modules,[{module:'drive_left',kind:'replace',amount:0},{module:'chassis',kind:'repair',amount:400}]);assert.equal(q.cost,900);assert.equal(q.remaining,0);assert.equal(q.after.drive_left.hp,400);assert(q.after.drive_left.functional);assert.equal(q.after.chassis.hp,1200);assert.equal(JSON.stringify(modules),original);assert.equal(q.after.battery.hp,modules.battery.hp);s.dispose();return{budget:900,cost:q.cost,unrelatedModulesUnchanged:true,atomic:true};});

await check('G09','20 seeded AI matches finish with unchanged physics across difficulties',()=>{const results=[];for(let n=0;n<20;n++){const a=n%3,b=(Math.floor(n/3)+1)%3,s=make(a,b,{practice:false,hazards:n%2===0,ai:[true,true],difficulty:(['easy','medium','hard'] as const)[n%3],seed:4200+n});run(s,RULES.matchTicks);assert(s.result,'AI match did not end');assert(s.bots.every(b=>b.energy>=0&&b.charges>=0));const result={seed:4200+n,a,b,winner:s.result.winner,reason:s.result.reason,ticks:s.tick,impacts:s.events.length,charges:s.bots.map(b=>b.charges),maxFlipWork:Math.max(...s.bots.map(b=>b.flipWork))};assert(s.bots.every(bot=>bot.flipWork<=flipEnergy(bot.compiled.config)+.001));results.push(result);s.dispose();if(n%4===3)console.log('AI progress',n+1,'/ 20');}writeFileSync('docs/ai-matches.json',JSON.stringify(results,null,2));return{matches:20,completed:results.length,reasons:results.reduce((m,r)=>(m[r.reason]=(m[r.reason]??0)+1,m),{} as Record<string,number>)};});

await check('G12','Ten worlds release resources and replay snapshots remain bounded',()=>{const memory=[];for(let n=0;n<10;n++){const s=make(n%3,(n+1)%3);run(s,900);assert.equal(s.frames.length,180);const live=JSON.stringify(s.snapshot());for(let j=0;j<50;j++){const proxies=copy(s.frames.slice(-60));for(const f of proxies){f.transforms[0].p.x+=10;}assert.equal(JSON.stringify(s.snapshot()),live);}assert.equal(s.frames.length,180);s.dispose();assert.equal(s.meta.size,0);assert.equal(s.bodyIds.size,0);assert.equal(s.frames.length,0);assert.equal(s.episodes.size,0);memory.push(process.memoryUsage().heapUsed);}return{matches:10,replayCopyTransitions:500,frameRing:180,retainedGameCollections:0,heapSamples:memory};});

const failures=checks.filter(c=>c.status==='failed');console.log(JSON.stringify({passed:checks.length-failures.length,failed:failures.length,seconds:(performance.now()-started)/1000,failures:failures.map(f=>f.name)},null,2));process.exitCode=failures.length?1:0;
