import assert from 'node:assert/strict';import {mkdirSync,writeFileSync} from 'node:fs';
import {Tournament,Simulation,initializePhysics} from '../src/sim';import {preset,copy} from '../src/model';
await initializePhysics();const reports=[];
for(const seed of[7189,71319,83102]){const cup=new Tournament(preset(9),false,seed),other=new Tournament(preset(9),false,seed);assert.throws(()=>cup.quickResolveComputerMatches(),/Finish your fight/);
 for(let round=0;round<3;round++){for(const t of[cup,other]){const sim=new Simulation(t.playerConfigs(),{practice:false,hazards:false,ai:[false,false],recordVisuals:false,condition:t.condition,allowDamaged:!!t.condition});try{sim.bots[0].modules.chassis.hp-=100;sim.finish('Judges’ decision',0);t.recordPlayer(sim.result!,sim.bots[0].modules);}finally{sim.dispose();}}
  const condition=copy(cup.condition),modules=copy(cup.repairModules);if(round===0){cup.matches[0][1].winner=cup.matches[0][1].b;cup.matches[0][1].reason='Completed physical result';other.matches[0][1].winner=other.matches[0][1].b;other.matches[0][1].reason='Completed physical result';}
  const start=performance.now(),resolved=cup.quickResolveComputerMatches();other.quickResolveComputerMatches();assert(performance.now()-start<100);assert.deepEqual(cup.condition,condition);assert.deepEqual(cup.repairModules,modules);assert.equal(cup.quickResolveComputerMatches(),0);assert(cup.matches[round].every(m=>m.winner));assert.deepEqual(cup.matches[round].map(m=>m.winner!.name),other.matches[round].map(m=>m.winner!.name));if(round===0)assert.equal(cup.matches[0][1].reason,'Completed physical result');reports.push({seed,round,resolved,conditionPreserved:true,seededResults:true});cup.advance();other.advance();
 }assert(cup.champion?.player);assert.equal(cup.condition?.chassis,900);cup.dispose();other.dispose();}
const loss=new Tournament(preset(0),false,7431),sim=new Simulation(loss.playerConfigs(),{hazards:false,ai:[false,false],recordVisuals:false});sim.finish('Judges’ decision',1);loss.recordPlayer(sim.result!,sim.bots[0].modules);assert(loss.eliminated);sim.dispose();loss.dispose();
mkdirSync('browser-evidence',{recursive:true});writeFileSync('browser-evidence/tournament-direct.json',JSON.stringify({source:process.env.GITHUB_SHA,reports},null,2));console.log('PASS seeded immediate AI resolution, completed results, player gating, damage carryover, and champion');
