import assert from 'node:assert/strict';
import {writeFileSync} from 'node:fs';
import {Simulation,initializePhysics,neutral} from '../src/sim';
import {preset,RULES,SLOTS,bodyOrigin,axisQ,rotate,add,v,identity,dot,length,sub,isSpinner,type Vec,type Quat} from '../src/model';
import {LANDING,landingEnergy} from '../src/landing-impact';
import {HUGE_HANDLING} from '../src/huge-handling';
await initializePhysics();
const results:any[]=[];
async function test(name:string,fn:()=>unknown){if(process.env.CASE&&!name.includes(process.env.CASE))return;try{const detail=await fn();results.push({name,status:'passed',detail});console.log('PASS',name,JSON.stringify(detail));}catch(e){results.push({name,status:'failed',error:String(e)});process.exitCode=1;console.log('FAIL',name,String(e));}writeFileSync('docs/traction-landing-results.json',JSON.stringify({date:new Date().toISOString(),results},null,2)+'\n');}
function make(index=7){return new Simulation([preset(index),preset(0)],{practice:true,hazards:false,ai:[false,false],autoUnstick:false});}
function pose(s:Simulation,id:number,p:Vec,q:Quat=identity,velocity=v()){const b=s.bots[id];for(const[key,body]of b.bodies){body.setRotation(q,true);body.setTranslation(add(p,rotate(bodyOrigin(b.compiled.config,key),q)),true);body.setLinvel(velocity,true);body.setAngvel(v(),true);}s.world.propagateModifiedBodyPositionsToColliders();}
const lost=(s:Simulation,id=0)=>SLOTS.reduce((sum,k)=>sum+s.bots[id].startHP[k]-s.bots[id].modules[k].hp,0);
await test('Landing energy scales with mass and speed squared without adding gravity twice',()=>{const a=landingEnergy(100,Math.sqrt(2*9.81*2),2),heavy=landingEnergy(200,a.speed,2),fast=landingEnergy(100,a.speed*2,2);assert(Math.abs(a.kinetic-1962)<1e-8);assert.equal(heavy.kinetic/a.kinetic,2);assert.equal(fast.kinetic/a.kinetic,4);assert(Math.abs(a.gravity-a.kinetic)<1e-8);assert.equal(fast.gravity,1962);assert.equal(a.kinetic,a.gravity+a.otherMotion);return{twoMetreJ:a.kinetic,doubleMassJ:heavy.kinetic,doubleSpeedJ:fast.kinetic,cushionJ:a.absorbed};});
await test('Real drops use one whole-robot budget and higher falls cause more damage',()=>{const rows=[];for(const height of[.06,.5,1,2]){const s=make(0);try{pose(s,0,v(-3, .14+height,2));pose(s,1,v(5,.14,-4));for(let t=0;t<650;t++)s.step();assert.equal(s.fault,undefined);const falls=s.events.filter(e=>e.target===0&&e.cause==='landing');for(const e of falls){assert(e.energy<=e.fallKineticJ!+.001);assert(e.allocations.reduce((n,a)=>n+a.energy,0)<=e.fallKineticJ!-e.fallAbsorbedJ!+.001);assert(Math.abs(e.fallMassKg!-s.totalMass(s.bots[0]))<.001);assert(Math.abs(e.fallKineticJ!-.5*e.fallMassKg!*e.fallSpeed!**2)<1e-5);assert.equal(e.attacker,null);}if(height<.1){assert.equal(falls.length,0);assert(lost(s)<.01);}else{assert.equal(falls.length,1);assert(falls[0].fallHeight!>height-.18);assert(lost(s)>0);assert(s.bots[0].modules.chassis.hp<1200);}rows.push({height,fallEvents:falls.length,hpLost:lost(s),mass:falls[0]?.fallMassKg,measuredDrop:falls[0]?.fallHeight,impactSpeed:falls[0]?.fallSpeed,energy:falls[0]?.energy,budget:falls[0]?.fallKineticJ});}finally{s.dispose();}}assert(rows[2].hpLost>rows[1].hpLost);assert(rows[3].hpLost>rows[2].hpLost);return rows;});
await test('Downward launch speed raises landing damage but lateral speed does not become fall energy',()=>{const rows=[];for(const velocity of[v(),v(0,-5,0),v(3,0,0)]){const s=make(0);try{pose(s,0,v(-3,1.14,1),identity,velocity);pose(s,1,v(5,.14,-4));for(let t=0;t<400;t++)s.step();assert.equal(s.fault,undefined);const e=s.events.find(e=>e.cause==='landing'&&e.target===0)!;assert(e);rows.push({velocity,energy:e.fallKineticJ!,gravity:e.fallGravityJ!,hp:lost(s)});}finally{s.dispose();}}assert(rows[1].energy>rows[0].energy*1.9);assert(Math.abs(rows[2].energy/rows[0].energy-1)<.04);return rows;});
await test('A heavier version of the same robot receives more landing energy and damage',()=>{const rows=[];for(const stock of[false,true]){const c=preset(0);if(!stock)c.chassis.equipmentMassKg=0;const s=new Simulation([c,preset(0)],{practice:true,hazards:false,ai:[false,false],autoUnstick:false});try{pose(s,0,v(-3,1.14,2));pose(s,1,v(5,.14,-4));for(let t=0;t<450;t++)s.step();const e=s.events.find(e=>e.cause==='landing'&&e.target===0)!;assert(e);assert.equal(s.fault,undefined);rows.push({mass:e.fallMassKg!,energy:e.fallKineticJ!,hp:lost(s)});}finally{s.dispose();}}assert(rows[1].mass>rows[0].mass);assert(rows[1].hp>rows[0].hp);assert(Math.abs(rows[1].energy/rows[0].energy-rows[1].mass/rows[0].mass)<.04);return rows;});
await test('A shelf landing uses the shelf height and produces one event',()=>{const s=make(0);try{pose(s,0,v(0,1.70,-5.85));pose(s,1,v(5,.14,3));for(let t=0;t<250;t++)s.step();assert.equal(s.fault,undefined);const falls=s.events.filter(e=>e.cause==='landing'&&e.target===0);assert.equal(falls.length,1);const e=falls[0];assert(Math.abs(e.point.y-.32)<.03);assert(e.fallHeight!>1.15&&e.fallHeight!<1.4);assert(e.energy<=e.fallKineticJ!);return{surfaceHeight:e.point.y,dropHeight:e.fallHeight,energy:e.energy,hp:lost(s)};}finally{s.dispose();}});
await test('All eleven resting robots avoid repeated fall damage',()=>{const rows=[];for(let i=0;i<11;i++){const s=make(i);try{for(let t=0;t<360;t++)s.step();assert.equal(s.fault,undefined);assert.equal(s.events.filter(e=>e.cause==='landing').length,0);assert(lost(s)<.01,s.bots[0].compiled.config.identity.name);rows.push({bot:s.bots[0].compiled.config.identity.name,damage:lost(s)});}finally{s.dispose();}}return rows;});
await test('HUGE stays level and controls turn speed with its blade running',()=>{const s=make();try{pose(s,0,v(0,.49,2));pose(s,1,v(5,.14,-4));const b=s.bots[0];b.weaponOn=true;assert(isSpinner(b.compiled.config.weapon));b.rotor!.setAngvel(v(b.compiled.config.weapon.rpm*Math.PI/30,0,0),true);let maxTilt=0,maxYaw=0,forward=0,reverse=0;for(let t=0;t<1800;t++){const phase=Math.floor(t/360),left=phase===0?.65:phase===1?-.65:phase===2?1:phase===3?-1:0,right=phase===2?-1:phase===3?1:left;s.step([{...neutral(),left,right},neutral()]);if(t>50){maxTilt=Math.max(maxTilt,Math.acos(Math.min(1,Math.abs(s.axis(b,v(0,1,0)).y)))*180/Math.PI);maxYaw=Math.max(maxYaw,Math.abs(b.chassis.angvel().y));}const speed=dot(b.chassis.linvel(),s.forward(b));forward=Math.max(forward,speed);reverse=Math.max(reverse,-speed);}assert.equal(s.fault,undefined);assert(Math.abs(b.colliders.get('wheel_-1_0_contact')!.friction()-HUGE_HANDLING.friction)<1e-5);assert(maxTilt<20,JSON.stringify({maxTilt,maxYaw}));assert(maxYaw<3.5,JSON.stringify({maxTilt,maxYaw}));assert(forward>1.5&&reverse>1.5);assert(Math.abs(b.chassis.angvel().y)<.2);return{friction:HUGE_HANDLING.friction,maxTiltDegrees:maxTilt,maxYawRadPerSecond:maxYaw,forwardMps:forward,reverseMps:reverse,finalYaw:b.chassis.angvel().y};}finally{s.dispose();}});
await test('HUGE returns from both supported sides without persistent spinning',()=>{const rows=[];for(const side of[-1,1]){const s=make();try{pose(s,0,v(0,.83,2),axisQ(v(0,0,1),side*Math.PI/2));pose(s,1,v(5,.14,-4));const b=s.bots[0];b.weaponOn=true;assert(isSpinner(b.compiled.config.weapon));b.rotor!.setAngvel(rotate(v(b.compiled.config.weapon.rpm*Math.PI/30,0,0),axisQ(v(0,0,1),side*Math.PI/2)),true);let recovered=-1,maxYaw=0,sideSpinSeconds=0;for(let t=0;t<5*RULES.hz;t++){s.step([{...neutral(),left:.4,right:.4},neutral()]);if(recovered<0&&Math.abs(s.axis(b,v(1,0,0)).y)<.15&&b.chassis.translation().y<.58)recovered=t/RULES.hz;maxYaw=Math.max(maxYaw,Math.abs(b.chassis.angvel().y));if(Math.abs(s.axis(b,v(1,0,0)).y)>.65&&Math.abs(b.chassis.angvel().y)>2)sideSpinSeconds+=RULES.dt;}assert.equal(s.fault,undefined);assert(recovered>=0&&recovered<1.5,JSON.stringify({side,recovered,axle:s.axis(b,v(1,0,0)),p:b.chassis.translation()}));assert(Math.abs(s.axis(b,v(1,0,0)).y)<.15);assert(maxYaw<8);assert(sideSpinSeconds<.35);assert(Math.abs(b.chassis.angvel().y)<.2);rows.push({side,recoveredSeconds:recovered,maxYawRadPerSecond:maxYaw,sideSpinSeconds});}finally{s.dispose();}}return rows;});
await test('HUGE support correction adds no torque in free flight',()=>{const s=make();try{pose(s,0,v(0,3,2),axisQ(v(0,0,1),.6));const b=s.bots[0];b.grounded=true;b.chassis.resetTorques(false);(s as any).stabilizeChassis(b);assert.equal(length(b.chassis.userTorque()),0);return{unsupportedCorrectionTorque:0};}finally{s.dispose();}});
