import assert from 'node:assert/strict';
import {writeFileSync} from 'node:fs';
import {Simulation,initializePhysics} from '../src/sim';
import {RULES,preset,v,add,bodyOrigin,identity} from '../src/model';
import {WallDamage,WALL_DAMAGE,type WallName} from '../src/wall-damage';
import {WallCrackVisual} from '../src/wall-cracks';
await initializePhysics();const results:any[]=[];
async function test(name:string,run:()=>unknown){try{const detail=await run();results.push({name,status:'passed',detail});console.log('PASS',name,JSON.stringify(detail));}catch(e){results.push({name,status:'failed',error:String(e)});process.exitCode=1;console.log('FAIL',name,String(e));}writeFileSync('docs/wall-cracks-results.json',JSON.stringify(results,null,2));}
function pose(s:Simulation,p:ReturnType<typeof v>){for(const[key,body]of s.bots[0].bodies){body.setTranslation(add(p,bodyOrigin(preset(0),key)),true);body.setRotation(identity,true);body.setLinvel(v(),true);body.setAngvel(v(),true);}s.world.propagateModifiedBodyPositionsToColliders();}
await test('Strong airborne contacts crack all four walls while slow contacts do not',()=>{
 const rows=[];for(const wall of ['east','west','north','south'] as WallName[])for(const speed of[.3,12]){const s=new Simulation([preset(0),preset(1)],{practice:true,hazards:false,ai:[false,false],autoUnstick:false});try{const axis=wall==='east'||wall==='west'?'x':'z',side=wall==='east'||wall==='south'?1:-1,p=v(0,2,0);p[axis]=side*6.3;pose(s,p);s.world.gravity=v();let touched=false;for(const body of s.bots[0].bodies.values()){const velocity=v();velocity[axis]=speed*side;body.setLinvel(velocity,true);}for(let i=0;i<(speed<1?1200:100);i++){s.step();touched ||=s.bots[0].wall;assert(!s.outOfArena(s.bots[0]));}assert(touched,wall+' must make actual contact');assert(!s.fault);const cracks=s.wallDamage.cracks.filter(c=>c.wall===wall);if(speed===12)assert(cracks.length>0,wall);else assert.equal(cracks.length,0);rows.push({wall,speed,cracks:cracks.length});}finally{s.dispose();}}return rows;
});
await test('Cracks use bounded immutable snapshots and cannot remove wall colliders',()=>{
 const s=new Simulation([preset(0),preset(1)],{practice:true,hazards:false,ai:[false,false]});try{const count=s.world.colliders.len(),d=s.wallDamage;assert(!d.impact('east',v(7,2,0),199,100,0));assert(!d.impact('east',v(7,2,0),2000,19,0));assert(d.impact('east',v(7,2,0),2000,100,0));s.capture();const old=s.frames.at(-1)!.wallCracks!;assert(!d.impact('east',v(7,2,0),2000,100,1));for(let i=1;i<200;i++)d.impact('east',v(7,2,0),2000+i*10,100,i*60);assert.equal(old.length,1);assert.equal(d.cracks.length,48);assert.equal(s.world.colliders.len(),count);assert.equal(new WallDamage().cracks.length,0);return{maxCracks:48,colliders:count,minEnergyJ:200,minImpulseNs:20};}finally{s.dispose();}
});
await test('Cracks use one fixed buffer, stay on panels and rewind with replay snapshots',()=>{
 const d=new WallDamage(),visual=new WallCrackVisual();try{for(let i=0;i<60;i++)d.impact((['north','south','east','west'] as WallName[])[i%4],v(7.3,i%2?7.29:.36,7.3),4000,100,i*60);visual.update(d.cracks);const attribute=visual.geometry.getAttribute('position'),array=attribute.array;assert.equal(visual.geometry.drawRange.count,48*48);for(let i=0;i<visual.geometry.drawRange.count;i++){assert(Number.isFinite(attribute.getX(i)));assert(attribute.getY(i)>=.349&&attribute.getY(i)<=RULES.wallHeight);assert(Math.abs(attribute.getX(i))<=RULES.floor/2);assert(Math.abs(attribute.getZ(i))<=RULES.floor/2);}visual.update([]);assert.equal(visual.geometry.drawRange.count,0);assert(!visual.visible);visual.update(d.cracks);assert.equal(visual.geometry.getAttribute('position').array,array);return{drawCalls:1,bufferBytes:array.byteLength,segments:48*24};}finally{visual.geometry.dispose();(visual.material as any).dispose();}
});
await test('All eleven airborne robots remain inside all four walls at 150 metres per second',()=>{
 let cases=0;for(let index=0;index<11;index++)for(const axis of['x','z'] as const)for(const side of[-1,1]){const s=new Simulation([preset(index),preset(0)],{practice:true,hazards:false,ai:[false,false],autoUnstick:false});try{const b=s.bots[0];for(const[key,body]of b.bodies){const p=v(0,6.4,0);p[axis]=side*5.6;body.setTranslation(add(p,bodyOrigin(b.compiled.config,key)),true);body.setRotation(identity,true);const velocity=v();velocity[axis]=side*150;body.setLinvel(velocity,true);body.setAngvel(v(),true);}s.world.propagateModifiedBodyPositionsToColliders();for(let tick=0;tick<60;tick++){s.step();assert(!s.outOfArena(b),JSON.stringify({index,axis,side,tick,p:b.chassis.translation()}));}assert(!s.fault);cases++;}finally{s.dispose();}}return{cases,speedMps:150,startHeightM:6.4};
});
await test('Swept wall guard blocks an assembly whose centre has entered the wall thickness',()=>{
 const s=new Simulation([preset(0),preset(1)],{practice:true,hazards:false,ai:[false,false]});try{pose(s,v(RULES.floor/2+.1,2,2));const b=s.bots[0];for(const body of b.bodies.values()){s.pre.set(body.handle,{p:{...body.translation()},com:{...body.worldCom()},q:{...body.rotation()},lin:v(100,0,0),ang:v()});body.setTranslation(add(body.translation(),v(.5,0,0)),true);body.setLinvel(v(100,0,0),true);}s.world.propagateModifiedBodyPositionsToColliders();(s as any).containArena();assert(!s.outOfArena(b));assert(b.chassis.translation().x<RULES.floor/2);assert.equal(b.chassis.linvel().x,0);return{contained:true};}finally{s.dispose();}
});
