import assert from 'node:assert/strict';
import {mkdirSync,writeFileSync} from 'node:fs';
import {pathToFileURL} from 'node:url';
import {preset,compile,isSpinner,rotate,add,v,bodyOrigin,axisQ,weaponAxis,mul} from '../src/model';
import {Simulation,initializePhysics,neutral} from '../src/sim';
import {rpmPresentation,robotSilhouette} from '../src/rpm-presentation';
import {rotorMotion,updateRotorMotion} from '../src/combat-visuals';
import {sparkParticle,sparkTint,writeSparkTrail,SPARK_TRAIL_FLOATS} from '../src/impact-sparks';
import * as THREE from 'three';
mkdirSync('browser-evidence',{recursive:true});
const baseline=await import(pathToFileURL(process.env.BASELINE_ROOT+'/src/model.ts').href),oldSim=await import(pathToFileURL(process.env.BASELINE_ROOT+'/src/sim.ts').href);
const config=preset(6),old=baseline.preset(6),built=compile(config,true),oldBuilt=baseline.compile(old,true);assert.deepEqual(config.drive,old.drive);assert.deepEqual(config.weapon,old.weapon);assert(Math.abs(built.mass-oldBuilt.mass)<1e-7);assert.equal(built.parts.filter(p=>p.tooth!==undefined).length,6);assert.equal(new Set(built.parts.filter(p=>p.body.startsWith('wheel_')).map(p=>p.body)).size,4);
const vertices=(p:any)=>p.shape.kind==='hull'?Array.from({length:p.shape.vertices.length/3},(_,i)=>v(...p.shape.vertices.slice(i*3,i*3+3) as [number,number,number])):p.shape.kind==='box'?[-1,1].flatMap(x=>[-1,1].flatMap(y=>[-1,1].map(z=>v(x*p.shape.size.x/2,y*p.shape.size.y/2,z*p.shape.size.z/2)))):Array.from({length:48},(_,i)=>v(Math.cos(i*Math.PI/12)*p.shape.radius,(i<24?-1:1)*p.shape.width/2,Math.sin(i*Math.PI/12)*p.shape.radius));
const tipFloor=(model:any,c:any)=>Math.min(...model.parts.filter((p:any)=>p.tooth!==undefined).flatMap((p:any)=>vertices(p).map(point=>c.chassis.height/2+c.chassis.clearance+c.weapon.mount.y+add(p.position,rotate(point,p.rotation)).y)));
const floor=tipFloor(built,config),oldFloor=tipFloor(oldBuilt,old);assert(floor>.09&&floor<oldFloor-.01,{floor,oldFloor}.toString());
await initializePhysics();const clearance=new Simulation([config,preset(0)],{practice:true,hazards:false,ai:[false,false],autoUnstick:false});try{const b=clearance.bots[0],origin=v(0,config.chassis.height/2+config.chassis.clearance,0);for(const[key,body]of b.bodies){body.setTranslation(add(origin,bodyOrigin(config,key)),true);body.setRotation({x:0,y:0,z:0,w:1},true);}const rotor=[...b.colliders].filter(([id])=>b.compiled.parts.find(p=>p.id===id)?.body==='rotor').map(([,c])=>c),wheels=[...b.colliders].filter(([id])=>id.startsWith('wheel_')).map(([,c])=>c);for(let yaw=0;yaw<120;yaw++){b.rotor!.setRotation(axisQ(v(0,1,0),yaw*Math.PI/60),true);clearance.world.propagateModifiedBodyPositionsToColliders();for(const r of rotor)for(const w of wheels)assert.equal(r.intersectsShape(w.shape,w.translation(),w.rotation()),false,JSON.stringify({yaw,rotor:[...b.colliders].find(([,c])=>c.handle===r.handle)?.[0],wheel:[...b.colliders].find(([,c])=>c.handle===w.handle)?.[0],rotorPosition:r.translation(),wheelPosition:w.translation()}));}}finally{clearance.dispose();}
async function mobility(module:any,model:any){await module.initializePhysics();const s=new module.Simulation([model.preset(6),model.preset(0)],{practice:true,hazards:false,ai:[false,false],autoUnstick:false,recordVisuals:false});try{const b=s.bots[0];for(let i=0;i<160;i++)s.step();const origin={...b.chassis.translation()};for(let i=0;i<720;i++)s.step([{...module.neutral(),left:.7,right:.7},module.neutral()]);const end=b.chassis.translation(),speed=Math.hypot(b.chassis.linvel().x,b.chassis.linvel().z),distance=Math.hypot(end.x-origin.x,end.z-origin.z);for(let i=0;i<320;i++)s.step([{...module.neutral(),left:.7,right:-.7},module.neutral()]);assert.equal(s.fault,undefined);return{speed,distance,turn:Math.abs(b.chassis.angvel().y)};}finally{s.dispose();}}
const before=await mobility(oldSim,baseline),after=await mobility({Simulation,initializePhysics,neutral},{preset});for(const key of ['speed','distance','turn'] as const)assert(Math.abs(after[key]-before[key])/Math.max(.1,before[key])<.12,JSON.stringify({before,after,key}));
for(const ratio of [0,.25,.5,.79,.8,.9,1]){const p=rpmPresentation(ratio);assert.equal(p.nearMax,ratio>=.8);assert(/^#[0-9a-f]{6}$/.test(p.color));}assert(rpmPresentation(1).motion>rpmPresentation(.8).motion);assert(rpmPresentation(1).period<rpmPresentation(.8).period);assert.equal(new Set(Array.from({length:11},(_,i)=>robotSilhouette(preset(i).chassis.profile))).size,11);
const exposures=[];for(let i=0;i<11;i++){const c=preset(i);if(!isSpinner(c.weapon))continue;const root=rotorMotion(c),rotor=new THREE.Group();rotor.add(root);updateRotorMotion(rotor,c.weapon.rpm,1,false,1);assert(root.visible);if(i===6)assert(!root.userData.enhancedExposure);else if(i===8)assert(root.userData.sawbladeExposure);else{assert(root.userData.enhancedExposure);const mesh=root.children[0].children[0] as THREE.Mesh,g=mesh.geometry,p=g.getAttribute('position'),buffer=p.array,forward=Array.from(p.array);updateRotorMotion(rotor,c.weapon.rpm,2,false,-1);assert.notDeepEqual(Array.from(p.array),forward);assert.equal(p.array,buffer);for(const n of p.array)assert(Number.isFinite(n));}updateRotorMotion(rotor,c.weapon.rpm,2,true,1);assert.equal(root.visible,false);root.traverse(o=>{if(o instanceof THREE.Mesh){o.geometry.dispose();(o.material as THREE.Material).dispose();}});exposures.push(c.chassis.profile);}
const palettes=[0,40,100,250].map(hp=>new Set(Array.from({length:128},(_,i)=>JSON.stringify(sparkTint(hp,i,25)))).size);assert.deepEqual(palettes,[2,4,6,8]);const a=sparkParticle(10000,v(1,1,0),2,11,0),b=sparkParticle(10000,v(1,1,0),2,11,250);assert.deepEqual(a.velocity,b.velocity);assert.equal(a.life,b.life);assert.notDeepEqual(a.color,b.color);const positions=new Float32Array(SPARK_TRAIL_FLOATS),colors=new Float32Array(SPARK_TRAIL_FLOATS);writeSparkTrail(positions,colors,0,0,1,0,1,2,3,.04,.9,true,b.color);assert([...positions,...colors].every(Number.isFinite));
for(const pair of [[6,0],[1,9],[5,7]]){const s=new Simulation([preset(pair[0]),preset(pair[1])],{practice:true,hazards:true,ai:[true,true],seed:68110+pair[0],recordVisuals:false});try{for(let i=0;i<4800;i++)s.step();assert.equal(s.fault,undefined);assert(s.bots.every(b=>Number.isFinite(b.rpm)&&b.energy>=0));}finally{s.dispose();}}
writeFileSync('browser-evidence/weapon-effects.json',JSON.stringify({status:'passed',source:process.env.GITHUB_SHA,whyachi:{floorClearance:floor,oldFloorClearance:oldFloor,mass:built.mass,originalMass:oldBuilt.mass,rpm:(config.weapon as any).rpm,drive:config.drive,before,after,ownWheelSweepSamples:120},exposures,palettes},null,2));console.log('PASS cage clearance, original mobility, angular exposure, RPM presentation, and damage colors');
