import {gzipSync,gunzipSync} from 'node:zlib';
import {Simulation,RAPIER,initializePhysics,type Bot} from '../src/sim';
import {rng} from '../src/model';
const omit=new Set(['world','queue','bots','hazards','debris','random','highlights','hitReadouts','wallDamage']);
function encode(value:any):any{if(value instanceof Map)return{$map:[...value].map(([k,v])=>[encode(k),encode(v)])};if(value instanceof Set)return{$set:[...value].map(encode)};if(ArrayBuffer.isView(value))return{$bytes:Buffer.from(value.buffer,value.byteOffset,value.byteLength).toString('base64')};if(Array.isArray(value))return value.map(encode);if(value&&typeof value==='object')return Object.fromEntries(Object.entries(value).filter(([,v])=>typeof v!=='function').map(([k,v])=>[k,encode(v)]));return value;}
function decode(value:any):any{if(value?.$map)return new Map(value.$map.map(([k,v]:any[])=>[decode(k),decode(v)]));if(value?.$set)return new Set(value.$set.map(decode));if(value?.$bytes)return new Uint8Array(Buffer.from(value.$bytes,'base64'));if(Array.isArray(value))return value.map(decode);if(value&&typeof value==='object')return Object.fromEntries(Object.entries(value).map(([k,v])=>[k,decode(v)]));return value;}
function botState(bot:Bot){const skip=new Set(['chassis','rotor','arm','roll','bodies','colliders','joints']);return{data:encode(Object.fromEntries(Object.entries(bot).filter(([k])=>!skip.has(k)))),bodies:[...bot.bodies].map(([name,b])=>[name,b.handle]),colliders:[...bot.colliders].map(([name,c])=>[name,c.handle]),joints:[...bot.joints].map(([name,j])=>[name,j.handle]),chassis:bot.chassis.handle,rotor:bot.rotor?.handle,arm:bot.arm?.handle,roll:bot.roll?.handle};}
export function saveSimulation(sim:Simulation):string{const s=sim as any;const data={version:1,physics:Buffer.from(sim.world.takeSnapshot()).toString('base64'),global:encode(Object.fromEntries(Object.entries(sim).filter(([k,v])=>!omit.has(k)&&typeof v!=='function'))),rng:s.random.getState(),bots:sim.bots.map(botState),hazards:sim.hazards.map(h=>({...encode(Object.fromEntries(Object.entries(h).filter(([k])=>!['body','anchor'].includes(k)))),body:h.body.handle,anchor:h.anchor.handle})),debris:sim.debris.map(d=>({id:d.id,part:encode(d.part),body:d.body.handle})),highlights:encode(s.highlights),hitReadouts:encode(s.hitReadouts),wallDamage:encode(s.wallDamage)};return gzipSync(Buffer.from(JSON.stringify(data))).toString('base64');}
export async function restoreSimulation(encoded:string):Promise<Simulation>{await initializePhysics();const data=JSON.parse(gunzipSync(Buffer.from(encoded,'base64')).toString('utf8'));if(data.version!==1||!data.bots||data.bots.length!==2)throw Error('Invalid physics checkpoint.');const global=decode(data.global),configs=data.bots.map((b:any)=>decode(b.data).compiled.config),sim=new Simulation(configs as any,{...global.options,recordVisuals:false,seed:global.seed});sim.queue.free();sim.world.free();const world=RAPIER.World.restoreSnapshot(new Uint8Array(Buffer.from(data.physics,'base64')));if(!world)throw Error('Physics checkpoint restore failed.');Object.assign(sim,global);sim.world=world;sim.queue=new RAPIER.EventQueue(true);const s=sim as any;s.random=rng(global.seed);s.random.setState(data.rng);sim.bots=data.bots.map((saved:any)=>{const bot=decode(saved.data);bot.bodies=new Map(saved.bodies.map(([name,handle]:any[])=>[name,world.getRigidBody(handle)]));bot.colliders=new Map(saved.colliders.map(([name,handle]:any[])=>[name,world.getCollider(handle)]));bot.joints=new Map(saved.joints.map(([name,handle]:any[])=>[name,world.getImpulseJoint(handle)]));for(const key of['chassis','rotor','arm','roll'])bot[key]=saved[key]===undefined?undefined:world.getRigidBody(saved[key]);return bot;});sim.hazards=data.hazards.map((saved:any)=>({...decode(saved),body:world.getRigidBody(saved.body),anchor:world.getRigidBody(saved.anchor)}));sim.debris=data.debris.map((saved:any)=>({id:saved.id,part:decode(saved.part),body:world.getRigidBody(saved.body)}));Object.assign(s.highlights,decode(data.highlights));Object.assign(s.hitReadouts,decode(data.hitReadouts));Object.assign(s.wallDamage,decode(data.wallDamage));s.disposed=false;return sim;}
