import {performance} from 'node:perf_hooks';
import {Simulation,initializePhysics,neutral,type Command} from '../src/sim';
import {RULES,copy} from '../src/model';
import {encodeFrame,validateInput,ROOM_LIMITS,type OnlineRoom,type OnlineInput,type InputAction} from '../src/online/protocol';
import {redis,key,acquire,renew,release,checkpoint,publishFrame,present} from './store';
import {currentMatch,matchPlayers,finishMatch} from './rooms';
import {saveSimulation,restoreSimulation} from './checkpoint';
import {matchFrame} from './frames';
type InputState={seq:number,left:number,right:number,time:number,actionAck:number,queued:InputAction[]};
export class MatchEngine{
 room:OnlineRoom;match:string;token:string;epoch:number;sim!:Simulation;serial=0;countdown=3;started=false;stopped=false;inputs:InputState[]=[0,1].map(()=>({seq:0,left:0,right:0,time:0,actionAck:0,queued:[]}));lastFrame=0;lastCheckpoint=0;lastRenew=0;lastPresence=0;missing=[0,0];private previous=0;private accumulator=0;private loop?:ReturnType<typeof setInterval>;private saving=false;private renewing=false;private publishing=false;private finishing=false;
 constructor(room:OnlineRoom,lease:{token:string,epoch:number},readonly onDone:(room:OnlineRoom)=>void){this.room=room;this.match=currentMatch(room)!.id;this.token=lease.token;this.epoch=lease.epoch;}
 static async claim(room:OnlineRoom,onDone:(room:OnlineRoom)=>void){const m=currentMatch(room);if(!m||m.status!=='active')return undefined;const lease=await acquire(m.id);if(!lease)return undefined;const engine=new MatchEngine(room,lease,onDone);try{await engine.initialize();return engine;}catch(e){await release(m.id,lease.token);throw e;}}
 private async initialize(){await initializePhysics();const saved=await redis().get(key('checkpoint:'+this.match));if(saved){const data=JSON.parse(saved);if(data.match!==this.match)throw Error('Checkpoint match identity mismatch.');this.sim=await restoreSimulation(data.sim);this.countdown=data.countdown;this.started=data.started;this.inputs=data.inputs;this.serial=data.serial;for(const input of this.inputs){input.left=0;input.right=0;input.time=0;}}else{const players=matchPlayers(this.room);this.sim=new Simulation(players.map(p=>p.config) as any,{seed:currentMatch(this.room)!.seed,practice:false,hazards:this.room.hazards,ai:players.map(p=>p.ai) as [boolean,boolean],difficulty:this.room.difficulty,recordVisuals:false,autoUnstick:false,conditionBySide:players.map(p=>p.condition) as any});}this.previous=performance.now();this.lastRenew=Date.now();this.loop=setInterval(()=>this.advance(),4);await this.sendFrame();}
 receive(guest:string,payload:unknown){const input=validateInput(payload),players=matchPlayers(this.room),side=players.findIndex(p=>p.id===guest&&!p.ai);if(side<0||input.match!==this.match)return;const state=this.inputs[side];if(input.seq<=state.seq)return;state.seq=input.seq;state.left=input.left;state.right=input.right;state.time=Date.now();const seen=new Set(state.queued.map(a=>a.id));for(const action of input.actions)if(action.id>state.actionAck&&!seen.has(action.id)){state.queued.push(action);seen.add(action.id);}state.queued.sort((a,b)=>a.id-b.id);if(state.queued.length>64)throw Error('Too many pending actions.');}
 private advance(){if(this.stopped||this.finishing)return;const now=performance.now(),elapsed=Math.min(.1,(now-this.previous)/1000);this.previous=now;try{if(!this.started){this.countdown=Math.max(0,this.countdown-elapsed);if(this.countdown===0)this.started=true;}else{this.accumulator+=elapsed;let steps=0;while(this.accumulator>=RULES.dt&&steps++<RULES.maxSteps&&!this.sim.result&&!this.sim.fault){const commands=this.inputs.map((input,side)=>{const c=neutral(),fresh=Date.now()-input.time<ROOM_LIMITS.inputExpiryMs;if(fresh){c.left=input.left;c.right=input.right;}const action=input.queued.shift();if(action){input.actionAck=action.id;if(action.kind==='recover')this.sim.manualUnstick(side);else c[action.kind==='weapon'?'weapon':'selfRight']=true;}return c;}) as [Command,Command];this.sim.step(commands);this.accumulator-=RULES.dt;}if(steps>RULES.maxSteps)this.accumulator=Math.min(this.accumulator,RULES.dt*RULES.maxSteps);}
  const wall=Date.now();if(wall-this.lastRenew>1500&&!this.renewing){this.renewing=true;this.lastRenew=wall;void renew(this.match,this.token).then(ok=>{if(!ok)void this.stop(false);}).catch(()=>void this.stop(false)).finally(()=>this.renewing=false);}if(wall-this.lastPresence>1000){this.lastPresence=wall;void this.observeConnections().catch(()=>{});}if(wall-this.lastCheckpoint>2000&&!this.saving){this.lastCheckpoint=wall;void this.save().catch(()=>void this.stop(false));}if(wall-this.lastFrame>=1000/30&&!this.publishing){this.lastFrame=wall;void this.sendFrame().catch(()=>{});}if(this.sim.fault)void this.fail(this.sim.fault);else if(this.sim.result)void this.finish();
 }catch(e){void this.fail(e instanceof Error?e.message:'Match execution failed.');}}
 private async observeConnections(){if(this.stopped||!this.started||this.sim.result)return;const players=matchPlayers(this.room);for(const[side,p]of players.entries()){if(p.ai)continue;if(await present(this.room.id,p.id))this.missing[side]=0;else{this.missing[side]||=Date.now();if(Date.now()-this.missing[side]>ROOM_LIMITS.reconnectMs){this.sim.finish('Disconnect forfeit',(1-side) as 0|1);break;}}}}
 async sendFrame(){if(this.stopped)return;this.publishing=true;try{const frame=matchFrame(this.sim,this.match,this.epoch,++this.serial,this.sim.result?'finished':this.started?'fight':'countdown',this.countdown,this.inputs.map(i=>i.seq),this.inputs.map(i=>i.actionAck));await publishFrame(this.room.id,this.match,this.token,encodeFrame(frame));}finally{this.publishing=false;}}
 async save(){if(this.saving||this.stopped)return;this.saving=true;try{const data=JSON.stringify({match:this.match,sim:saveSimulation(this.sim),countdown:this.countdown,started:this.started,inputs:copy(this.inputs),serial:this.serial});if(!await checkpoint(this.match,this.token,data))await this.stop(false);}finally{this.saving=false;}}
 private async finish(){if(this.finishing||this.stopped)return;this.finishing=true;try{await this.sendFrame();await this.save();const room=await finishMatch(this.room.id,this.match,this.token,this.sim.result!,this.sim.bots.map(b=>b.modules));await this.stop(false);this.onDone(room);}catch{this.finishing=false;}}
 private async fail(reason:string){if(this.finishing||this.stopped)return;this.finishing=true;try{await this.save();}finally{await this.stop(false);}}
 async stop(save=true){if(this.stopped)return;if(save)await this.save();this.stopped=true;if(this.loop)clearInterval(this.loop);this.sim?.dispose();await release(this.match,this.token);}
}
