import {SLOTS,batteryPosition,copy} from '../src/model';
import {Simulation,type VisualFrame} from '../src/sim';
import type {OnlineFrame,BodyPose} from '../src/online/protocol';
function pose(id:string,body:any):BodyPose{return{id,p:{...body.translation()},q:{...body.rotation()},v:{...body.linvel()},w:{...body.angvel()}};}
export function matchFrame(sim:Simulation,match:string,epoch:number,serial:number,phase:OnlineFrame['phase'],countdown:number,ack:number[],actionAck:number[]):OnlineFrame{
 const bodies:BodyPose[]=[];for(const b of sim.bots)for(const[id,body]of b.bodies)bodies.push(pose('b'+b.id+':'+id,body));for(const h of sim.hazards)bodies.push(pose('hazard_'+h.id,h.body));for(const d of sim.debris)bodies.push(pose(d.id,d.body));const hits=(sim as any).hitReadouts.update(sim.events,sim.tick);
 const visual:VisualFrame={tick:sim.tick,transforms:bodies.map(({id,p,q})=>({id,p,q})),wallCracks:copy(sim.wallDamage.cracks),health:sim.bots.map(b=>SLOTS.map(s=>b.modules[s].max?b.modules[s].hp/b.modules[s].max:0)),rpm:sim.bots.map(b=>b.rpm),tracks:sim.bots.map(b=>b.trackPhase??[0,0]),speeds:sim.bots.map(b=>Math.hypot(...Object.values(b.chassis.linvel()))),directions:sim.bots.map(b=>Math.sign(sim.omega(b))||b.spinDirection),fires:sim.bots.map(b=>sim.batteryFireSeconds(b)),firePoints:sim.bots.map(b=>b.batteryFire?.localPoint??batteryPosition(b.compiled.config)),hits:copy(hits),effects:sim.events.filter(e=>sim.tick-e.tick<240&&e.cause!=='crush'&&e.cause!=='battery fire').map(e=>({id:e.id,tick:e.tick,p:e.point,energy:e.energy,direction:e.sparkDirection}))};
 return{match,epoch,serial,tick:sim.tick,serverTime:Date.now(),phase,countdown,configs:sim.bots.map(b=>b.compiled.config) as OnlineFrame['configs'],bodies,bots:sim.bots.map(b=>({energy:b.energy,charges:b.charges,rpm:b.rpm,weaponOn:b.weaponOn,weaponWatts:b.weaponWatts,actuatorTorque:b.actuatorTorque,grounded:b.grounded,flipStart:b.flipStart,flipAngle:b.flipAngle,flipWork:b.flipWork,lastFire:b.lastFire,rollStart:b.rollStart,count:b.count,modules:copy(b.modules),partIds:[...b.colliders.keys()],driveSign:b.driveSign,spinDirection:b.spinDirection,trackPhase:b.trackPhase,batteryFire:copy(b.batteryFire)})),hazards:sim.hazards.map(h=>({id:h.id,phase:h.phase,cycle:h.cycle})),debris:sim.debris.map(d=>({id:d.id,part:d.part,body:pose(d.id,d.body)})),visual,result:sim.result,ack:[...ack],actionAck:[...actionAck],flipHints:sim.bots.map(b=>sim.flipOpportunity(b)),physicsMs:sim.physicsMs};
}
