import {createServer,type IncomingMessage,type ServerResponse} from 'node:http';
import {randomBytes,randomUUID} from 'node:crypto';
import {WebSocketServer,WebSocket} from 'ws';
import {ONLINE_PROTOCOL,ROOM_LIMITS,type OnlineRoom} from '../src/online/protocol';
import {redis,key,channel,digest,loadRoom,claimConnection,currentConnection,refreshPresence,instanceId} from './store';
import {createRoom,joinRoom,setReady,startRoom,repairPlayer,advanceRepair,currentMatch,leaveRoom,transferHost} from './rooms';
import {MatchEngine} from './engine';
export type Peer={socket:WebSocket,guest:string,room?:string,epoch?:string,alive:boolean,lastPong:number,lastPing:number,opened:number,requests:number,rateAt:number,roomCache?:OnlineRoom,checkUntil?:number,check?:Promise<boolean>};
export class OnlineGateway{
 readonly peers=new Set<Peer>();readonly rooms=new Map<string,Set<Peer>>();readonly engines=new Map<string,MatchEngine>();private subscriber=redis().duplicate();private claiming=new Set<string>();private claimTasks=new Map<string,Promise<void>>();private subscriptionCounts=new Map<string,number>();private timer?:ReturnType<typeof setInterval>;private closing=false;
 constructor(){this.subscriber.on('error',()=>{});this.subscriber.on('message',(ch,message)=>void this.message(ch,message).catch(()=>{}));this.timer=setInterval(()=>void this.housekeeping(),1000);}
 async attach(socket:WebSocket,guest:string){const peer:Peer={socket,guest,alive:true,lastPong:Date.now(),lastPing:0,opened:Date.now(),requests:0,rateAt:Date.now()};this.peers.add(peer);this.send(peer,{type:'welcome',protocol:ONLINE_PROTOCOL,guest});socket.on('pong',()=>{peer.alive=true;peer.lastPong=Date.now();});socket.on('message',(data,isBinary)=>{if(isBinary){socket.close(1003,'Controls require JSON.');return;}void this.receive(peer,data.toString()).catch(e=>this.send(peer,{type:'error',message:e instanceof Error?e.message:'Room request failed.'}));});socket.on('close',()=>void this.detach(peer).catch(()=>{}));socket.on('error',()=>{});}
 private send(peer:Peer,value:unknown){if(peer.socket.readyState===WebSocket.OPEN&&peer.socket.bufferedAmount<256*1024)peer.socket.send(JSON.stringify(value));}
 private async validConnection(peer:Peer){if(!peer.room||!peer.epoch)return false;if(Date.now()<(peer.checkUntil??0))return true;if(!peer.check)peer.check=currentConnection(peer.room,peer.guest,peer.epoch).then(ok=>{if(ok)peer.checkUntil=Date.now()+250;return ok;}).finally(()=>peer.check=undefined);return peer.check;}
 private async receive(peer:Peer,text:string){if(text.length>32768)throw Error('The room request is too large.');const now=Date.now();if(now-peer.rateAt>1000){peer.rateAt=now;peer.requests=0;}if(++peer.requests>100)throw Error('Too many room requests.');const value=JSON.parse(text);if(!value||typeof value.type!=='string')throw Error('Invalid room request.');if(value.type==='ping'){if(peer.room&&peer.epoch)await refreshPresence(peer.room,peer.guest,peer.epoch);this.send(peer,{type:'pong',at:value.at,serverTime:now});return;}
  if(value.type==='create'){const room=await createRoom(peer.guest,value.mode,value.name,value.config,value.hazards);await this.enter(peer,room);return;}if(value.type==='join'){const room=await joinRoom(peer.guest,value.code,value.name,value.config,value.expectedId);await this.enter(peer,room);return;}if(!peer.room||!peer.epoch||!await this.validConnection(peer))throw Error('This seat moved to another connection.');
  if(value.type==='ready'){const {room}=await setReady(peer.room,peer.guest,value.ready,value.config).then(room=>({room}));this.send(peer,{type:'room',room,you:peer.guest});return;}if(value.type==='start'){const room=await startRoom(peer.room,peer.guest);this.send(peer,{type:'room',room,you:peer.guest});await this.claim(room);return;}if(value.type==='repair'){const room=await repairPlayer(peer.room,peer.guest,value.orders);this.send(peer,{type:'room',room,you:peer.guest});return;}if(value.type==='leave'){const id=peer.room;await leaveRoom(id,peer.guest);await this.exit(peer);return;}if(value.type==='input'){const room=peer.roomCache,match=room&&currentMatch(room);if(!room||!match||match.id!==value.match||!room.entrants.some(p=>p.id===peer.guest&&(p.id===match.a||p.id===match.b)&&!p.ai))throw Error('You do not control a robot in this match.');const engine=this.engines.get(peer.room);if(engine&&!engine.stopped)engine.receive(peer.guest,value);else{await redis().set(key('input:'+value.match+':'+peer.guest),JSON.stringify({input:value,at:Date.now()}),'EX',30);await redis().publish(channel(peer.room),'i:'+JSON.stringify({guest:peer.guest,input:value,from:instanceId}));}return;}throw Error('Unsupported room request.');
 }
 private async enter(peer:Peer,room:OnlineRoom){await this.exit(peer);peer.room=room.id;peer.roomCache=room;peer.checkUntil=0;peer.epoch=await claimConnection(room.id,peer.guest);const members=this.rooms.get(room.id)??new Set<Peer>();members.add(peer);this.rooms.set(room.id,members);if(!this.subscriptionCounts.has(room.id)){await this.subscriber.subscribe(channel(room.id));this.subscriptionCounts.set(room.id,1);}this.send(peer,{type:'room',room,you:peer.guest});const match=currentMatch(room);if(match){const frame=await redis().get(key('frame:'+match.id));if(frame&&peer.socket.readyState===WebSocket.OPEN)peer.socket.send(Buffer.from(frame,'base64'));}await this.claim(room);}
 private async exit(peer:Peer){if(!peer.room)return;if(this.closing){peer.room=undefined;peer.epoch=undefined;return;}const id=peer.room,set=this.rooms.get(id);set?.delete(peer);if(!set?.size){this.rooms.delete(id);this.subscriptionCounts.delete(id);await this.subscriber.unsubscribe(channel(id));const engine=this.engines.get(id);if(engine){this.engines.delete(id);await engine.stop(true);}}peer.room=undefined;peer.epoch=undefined;}
 private async detach(peer:Peer){this.peers.delete(peer);await this.exit(peer);}
 private async message(ch:string,message:string){if(this.closing)return;const roomId=[...this.rooms.keys()].find(id=>channel(id)===ch);if(!roomId)return;const members=this.rooms.get(roomId)!;if(message.startsWith('r:')){const room=JSON.parse(message.slice(2)) as OnlineRoom;for(const peer of members){peer.roomCache=room;this.send(peer,{type:'room',room,you:peer.guest});}await this.claim(room);}else if(message.startsWith('s:')){const bytes=Buffer.from(message.slice(2),'base64');for(const peer of members)if(peer.socket.readyState===WebSocket.OPEN&&peer.socket.bufferedAmount<128*1024)peer.socket.send(bytes);}else if(message.startsWith('i:')){const value=JSON.parse(message.slice(2));this.engines.get(roomId)?.receive(value.guest,value.input);}}
 private async claim(room:OnlineRoom){if(this.engines.get(room.id)?.stopped)this.engines.delete(room.id);if(this.closing||this.engines.has(room.id)||this.claiming.has(room.id)||!['countdown','fight'].includes(room.phase)||!this.rooms.has(room.id))return;if(this.engines.size>=1)return;this.claiming.add(room.id);const work=(async()=>{const engine=await MatchEngine.claim(room,next=>{this.engines.delete(room.id);void this.claim(next).catch(()=>{});});if(engine){if(this.closing||!this.rooms.has(room.id))await engine.stop(true);else this.engines.set(room.id,engine);}})();this.claimTasks.set(room.id,work);try{await work;}finally{this.claiming.delete(room.id);this.claimTasks.delete(room.id);}}
 private async housekeeping(){if(this.closing)return;const now=Date.now();for(const peer of this.peers){if(peer.socket.readyState!==WebSocket.OPEN)continue;if(now-peer.opened>ROOM_LIMITS.connectionRenewMs){this.send(peer,{type:'renew'});continue;}if(now-peer.lastPong>15000){peer.socket.terminate();continue;}if(now-peer.lastPing>5000){peer.lastPing=now;peer.socket.ping();}if(peer.room&&peer.epoch)void refreshPresence(peer.room,peer.guest,peer.epoch).then(ok=>{if(!ok)peer.socket.close(4002,'This seat resumed elsewhere.');}).catch(()=>{});}for(const id of this.rooms.keys()){try{let room=await loadRoom(id);if(!room)continue;if(room.phase==='repair')room=await advanceRepair(id);if(room.phase==='lobby'&&now%10000<1200)room=await transferHost(id);await this.claim(room);}catch{}}}
 async stop(){this.closing=true;if(this.timer)clearInterval(this.timer);await Promise.allSettled([...this.claimTasks.values()]);for(const engine of this.engines.values())await engine.stop(true);this.engines.clear();for(const peer of this.peers)peer.socket.terminate();this.peers.clear();this.rooms.clear();await this.subscriber.quit();}
}
function allowed(req:IncomingMessage){const origin=req.headers.origin;if(!origin)return req.headers['sec-fetch-site']==='same-origin'||process.env.ONLINE_LOCAL_TEST==='1';try{const u=new URL(origin),host=String(req.headers['x-forwarded-host']??req.headers.host??'');return u.host===host||['https://bbots-tjh87.vercel.app','https://combat-robot-arena-live.vercel.app',...(process.env.ONLINE_ALLOWED_ORIGINS??'').split(',')].includes(origin);}catch{return false;}}
async function session(req:IncomingMessage,res:ServerResponse){if(!allowed(req)){res.writeHead(403);res.end('Origin denied.');return;}let token=String(req.headers.cookie??'').split(';').map(v=>v.trim()).find(v=>v.startsWith('cra_online='))?.slice(11),guest=token?await redis().get(key('guest:'+digest(token))):null;if(!guest){token=randomBytes(32).toString('base64url');guest=randomUUID();await redis().set(key('guest:'+digest(token)),guest,'EX',604800);const secure=req.headers['x-forwarded-proto']==='https'||process.env.VERCEL==='1';res.setHeader('Set-Cookie','cra_online='+token+'; Path=/api/online; HttpOnly; SameSite=Lax; Max-Age=604800'+(secure?'; Secure':''));}const ticket=randomBytes(32).toString('base64url');await redis().set(key('ticket:'+digest(ticket)),guest,'EX',900);res.setHeader('Cache-Control','no-store');res.setHeader('Content-Type','application/json');res.end(JSON.stringify({protocol:ONLINE_PROTOCOL,guest,ticket}));}
export function createOnlineServer(){const gateway=new OnlineGateway(),server=createServer((req,res)=>{res.setHeader('Cache-Control','no-store');const url=new URL(req.url??'/', 'http://localhost');if(url.searchParams.has('session')){void session(req,res).catch(()=>{res.writeHead(503);res.end('Online setup is temporarily unavailable.');});return;}void redis().ping().then(()=>{res.setHeader('Content-Type','application/json');res.end(JSON.stringify({status:'ready',protocol:ONLINE_PROTOCOL,roomDigits:4,maxTournamentUsers:8,sharedState:true}));}).catch(()=>{res.writeHead(503);res.end('Online room store unavailable.');});}),wss=new WebSocketServer({noServer:true,maxPayload:32768,handleProtocols:protocols=>protocols.has('arena.v1')?'arena.v1':false});server.on('upgrade',(req,socket,head)=>{void(async()=>{if(!allowed(req)){socket.destroy();return;}const protocols=String(req.headers['sec-websocket-protocol']??'').split(',').map(s=>s.trim()),ticket=protocols.find(v=>v.startsWith('ticket.'))?.slice(7),guest=ticket?await redis().get(key('ticket:'+digest(ticket))):null;if(!guest){socket.write('HTTP/1.1 401 Unauthorized\r\n\r\n');socket.destroy();return;}wss.handleUpgrade(req,socket,head,ws=>void gateway.attach(ws,guest));})().catch(()=>socket.destroy());});return{server,gateway};}
