import {randomUUID,randomInt} from 'node:crypto';
import {parseConfig,compile,preset,copy,RULES,SLOTS,rng,type BotConfig,type Module,type Slot} from '../src/model';
import {repairQuote,type RepairOrder,type Result} from '../src/sim';
import {ROOM_LIMITS,validRoomCode,type OnlineRoom,type RoomMode,type RoomPlayer,type RoomMatch} from '../src/online/protocol';
import {reserve,findRoom,mutate,present} from './store';
export function playerName(value:unknown){if(typeof value!=='string'||!value.trim()||[...value.trim()].length>24||/[\u0000-\u001f\u007f]/.test(value))throw Error('Use a name with 1 to 24 visible characters.');return value.trim();}
export function legalBuild(value:unknown){const c=parseConfig(value),errors=compile(c).errors;if(errors.length)throw Error(errors.map(e=>e.message).join(' '));return c;}
export async function createRoom(guest:string,mode:RoomMode,name:unknown,config:unknown,hazards=true){if(!['duel','tournament'].includes(mode))throw Error('Choose 1 vs 1 or tournament.');const now=Date.now(),player:RoomPlayer={id:guest,name:playerName(name),config:legalBuild(config),ready:false,ai:false};return reserve({id:randomUUID(),host:guest,mode,phase:'lobby',players:[player],entrants:[],rounds:[],round:0,current:0,version:1,seed:randomInt(1,0x7fffffff),hazards:Boolean(hazards),difficulty:'medium',created:now,updated:now});}
export async function joinRoom(guest:string,code:unknown,name:unknown,config:unknown,expectedId?:string){if(!validRoomCode(code))throw Error('Enter a four-digit room number.');const existing=await findRoom(code);if(!existing||expectedId&&existing.id!==expectedId)throw Error('This room expired or the number changed.');return(await mutate(existing.id,room=>{const player=room.players.find(p=>p.id===guest);if(player)return;if(room.phase!=='lobby')throw Error('This room already started.');if(room.players.length>=ROOM_LIMITS[room.mode])throw Error('This room is full.');room.players.push({id:guest,name:playerName(name),config:legalBuild(config),ready:false,ai:false});})).room;}
export async function setReady(roomId:string,guest:string,ready:boolean,config?:unknown){return(await mutate(roomId,room=>{if(room.phase!=='lobby')throw Error('Robot choices are locked for this tournament.');const player=room.players.find(p=>p.id===guest);if(!player)throw Error('You are not in this room.');if(config!==undefined)player.config=legalBuild(config);player.ready=Boolean(ready);})).room;}
function pairs(players:RoomPlayer[],seed:number){const random=rng(seed),list=[...players];for(let i=list.length-1;i>0;i--){const j=Math.floor(random()*(i+1));[list[i],list[j]]=[list[j],list[i]];}const out:RoomMatch[]=[];for(let i=0;i<list.length;i+=2)out.push({id:randomUUID(),a:list[i].id,b:list[i+1].id,status:'pending',seed:seed+i});return out;}
export async function startRoom(id:string,guest:string){return(await mutate(id,room=>{if(room.host!==guest)throw Error('Only the room host can start.');if(room.phase!=='lobby')throw Error('This room already started.');if(room.mode==='duel'&&room.players.length!==2)throw Error('Wait for the second player.');if(room.players.some(p=>!p.ready))throw Error('Every joined player must be ready.');room.entrants=copy(room.players);const random=rng(room.seed);while(room.entrants.length<(room.mode==='duel'?2:8)){const c=preset(Math.floor(random()*11));room.entrants.push({id:randomUUID(),name:c.identity.name+' AI',config:c,ready:true,ai:true});}room.rounds=[room.mode==='duel'?[{id:randomUUID(),a:room.entrants[0].id,b:room.entrants[1].id,status:'pending',seed:room.seed}]:pairs(room.entrants,room.seed)];room.round=0;room.current=0;room.rounds[0][0].status='active';room.phase='countdown';})).room;}
export function currentMatch(room:OnlineRoom){return room.rounds[room.round]?.[room.current];}
export function matchPlayers(room:OnlineRoom){const match=currentMatch(room);if(!match)throw Error('No active match.');return[room.entrants.find(p=>p.id===match.a)!,room.entrants.find(p=>p.id===match.b)!] as [RoomPlayer,RoomPlayer];}
export async function finishMatch(id:string,matchId:string,token:string,result:Result,modules:Record<Slot,Module>[]){return(await mutate(id,room=>{const match=currentMatch(room);if(!match||match.id!==matchId||match.status==='finished')return;if(match.status!=='active')throw Error('This match is not active.');match.status='finished';match.result=result;match.winner=result.winner===0?match.a:match.b;for(const[p,side]of matchPlayers(room).map((p,i)=>[p,i] as const)){p.modules=copy(modules[side]);p.condition=Object.fromEntries(SLOTS.map(s=>[s,p.modules![s].hp])) as Record<Slot,number>;p.repairDone=false;}const round=room.rounds[room.round];if(room.current+1<round.length){room.current++;round[room.current].status='active';room.phase='countdown';}else if(room.mode==='duel'||room.round===2){room.phase='finished';room.champion=match.winner;}else{room.phase='repair';room.repairUntil=Date.now()+ROOM_LIMITS.repairMs;}}, {match:matchId,token})).room;}
export function autoRepair(modules:Record<Slot,Module>){let remaining=RULES.repair;const orders:RepairOrder[]=[];for(const slot of['chassis','drive_left','drive_right','battery','weapon_actuator','weapon','armour_front','armour_top','armour_left','armour_right','armour_rear','self_right'] as Slot[]){const m=modules[slot];if(!m.present)continue;const missing=m.max-m.hp;if(missing<=0)continue;if(m.hp<=0){const cost=Math.ceil(missing+100);if(cost<=remaining){orders.push({module:slot,kind:'replace',amount:0});remaining-=cost;}}else{const amount=Math.min(Math.floor(missing),remaining);if(amount>0){orders.push({module:slot,kind:'repair',amount});remaining-=amount;}}}return repairQuote(modules,orders);}
export async function repairPlayer(id:string,guest:string,orders?:RepairOrder[]){return(await mutate(id,room=>{if(room.phase!=='repair')throw Error('No repair window is open.');const winners=room.rounds[room.round].map(m=>m.winner),p=room.entrants.find(p=>p.id===guest&&winners.includes(p.id));if(!p?.modules||p.repairDone)throw Error('No repair purchase is available.');const quote=orders?repairQuote(p.modules,orders):autoRepair(p.modules);p.modules=quote.after;p.condition=Object.fromEntries(SLOTS.map(s=>[s,p.modules![s].hp])) as Record<Slot,number>;p.repairDone=true;})).room;}
export async function advanceRepair(id:string){return(await mutate(id,room=>{if(room.phase!=='repair')return;const winners=room.rounds[room.round].map(m=>room.entrants.find(p=>p.id===m.winner)!);if(Date.now()<(room.repairUntil??0)&&winners.some(p=>!p.ai&&!p.repairDone))return;for(const p of winners)if(!p.repairDone&&p.modules){const q=autoRepair(p.modules);p.modules=q.after;p.condition=Object.fromEntries(SLOTS.map(s=>[s,q.after[s].hp])) as Record<Slot,number>;p.repairDone=true;}room.round++;room.current=0;room.rounds.push(pairs(winners,room.seed+room.round*101));room.rounds[room.round][0].status='active';room.phase='countdown';room.repairUntil=undefined;})).room;}
export async function transferHost(id:string){return(await mutate(id,async room=>{if(await present(id,room.host))return;for(const p of room.players)if(await present(id,p.id)){room.host=p.id;break;}})).room;}
export async function leaveRoom(id:string,guest:string){return(await mutate(id,room=>{if(room.phase!=='lobby')return;room.players=room.players.filter(p=>p.id!==guest);if(room.host===guest&&room.players.length)room.host=room.players[0].id;})).room;}

export async function retryRoom(id:string,guest:string){return(await mutate(id,room=>{if(room.host!==guest)throw Error('Only the room host can resume the saved fight.');if(room.phase!=='recovering')throw Error('This fight does not need a restart.');room.phase='countdown';delete room.error;})).room;}
