import Redis from 'ioredis';
import {randomUUID,randomInt,createHash} from 'node:crypto';
import type {OnlineRoom} from '../src/online/protocol';
import {ROOM_LIMITS} from '../src/online/protocol';
export const instanceId=randomUUID();
const prefix='cra:online:1:'+(process.env.ONLINE_NAMESPACE??(process.env.VERCEL_ENV==='preview'?'preview:'+process.env.VERCEL_GIT_COMMIT_REF:'production'))+':';
let connection:Redis|undefined;
export function redis(){if(!connection){const value=process.env.REDIS_URL??process.env.KV_URL??process.env.ONLINE_REDIS_URL;if(!value)throw Error('The online room store is not configured.');const url=new URL(value);connection=new Redis(value,{tls:url.hostname.endsWith('upstash.io')?{}:undefined,connectTimeout:10000,maxRetriesPerRequest:2,enableReadyCheck:true,retryStrategy:n=>Math.min(2000,n*100)});connection.on('error',()=>{});}return connection;}
export function key(name:string){return prefix+name;}
export function channel(room:string){return key('events:'+room);}
export function digest(value:string){return createHash('sha256').update(value).digest('hex');}
export async function reserve(room:Omit<OnlineRoom,'code'>):Promise<OnlineRoom>{for(let i=0;i<128;i++){const code=String(randomInt(1000,10000)),record={...room,code},result=await redis().eval("if redis.call('exists',KEYS[1])==1 then return 0 end redis.call('set',KEYS[1],ARGV[1],'EX',ARGV[3]);redis.call('set',KEYS[2],ARGV[2],'EX',ARGV[3]);return 1",2,key('code:'+code),key('room:'+room.id),room.id,JSON.stringify(record),ROOM_LIMITS.ttlSeconds);if(result===1)return record;}throw Error('Room numbers are busy. Try again.');}
export async function findRoom(code:string){const id=await redis().get(key('code:'+code));return id?loadRoom(id):undefined;}
export async function loadRoom(id:string):Promise<OnlineRoom|undefined>{const data=await redis().get(key('room:'+id));return data?JSON.parse(data):undefined;}
export async function mutate<T>(id:string,fn:(room:OnlineRoom)=>T|Promise<T>,fence?:{match:string,token:string}):Promise<{room:OnlineRoom,value:T}>{const token=randomUUID(),lock=key('lock:'+id);for(let i=0;i<40;i++){if(await redis().set(lock,token,'PX',5000,'NX')){try{const room=await loadRoom(id);if(!room)throw Error('This room expired.');const value=await fn(room);room.version++;room.updated=Date.now();const lease=fence?key('lease:'+fence.match):lock,expected=fence?.token??token,ok=await redis().eval("if redis.call('get',KEYS[1])~=ARGV[1] or redis.call('get',KEYS[5])~=ARGV[5] then return 0 end redis.call('set',KEYS[2],ARGV[2],'EX',ARGV[3]);redis.call('set',KEYS[3],ARGV[4],'EX',ARGV[3]);redis.call('publish',KEYS[4],'r:'..ARGV[2]);return 1",5,lock,key('room:'+id),key('code:'+room.code),channel(id),lease,token,JSON.stringify(room),ROOM_LIMITS.ttlSeconds,id,expected);if(ok!==1)throw Error('Room ownership changed. Retry the action.');return{room,value};}finally{await redis().eval("if redis.call('get',KEYS[1])==ARGV[1] then return redis.call('del',KEYS[1]) end return 0",1,lock,token);}}await new Promise(r=>setTimeout(r,15+randomInt(20)));}throw Error('The room is busy. Retry the action.');}
export async function acquire(match:string){const token=instanceId+':'+randomUUID();if(!await redis().set(key('lease:'+match),token,'PX',7000,'NX'))return undefined;const epoch=await redis().incr(key('epoch:'+match));await redis().expire(key('epoch:'+match),ROOM_LIMITS.ttlSeconds);return{token,epoch};}
export async function renew(match:string,token:string){return await redis().eval("if redis.call('get',KEYS[1])~=ARGV[1] then return 0 end redis.call('pexpire',KEYS[1],7000);return 1",1,key('lease:'+match),token)===1;}
export async function release(match:string,token:string){await redis().eval("if redis.call('get',KEYS[1])==ARGV[1] then return redis.call('del',KEYS[1]) end return 0",1,key('lease:'+match),token);}
export async function checkpoint(match:string,token:string,data:string){return await redis().eval("if redis.call('get',KEYS[1])~=ARGV[1] then return 0 end redis.call('set',KEYS[2],ARGV[2],'EX',ARGV[3]);return 1",2,key('lease:'+match),key('checkpoint:'+match),token,data,ROOM_LIMITS.ttlSeconds)===1;}
export async function publishFrame(room:string,match:string,token:string,frame:Uint8Array){const data=Buffer.from(frame).toString('base64');return await redis().eval("if redis.call('get',KEYS[1])~=ARGV[1] then return 0 end redis.call('set',KEYS[2],ARGV[2],'EX',ARGV[3]);redis.call('publish',KEYS[4],'s:'..ARGV[2]);return 1",4,key('lease:'+match),key('frame:'+match),key('room:'+room),channel(room),token,data,ROOM_LIMITS.ttlSeconds)===1;}
export async function presence(room:string,guest:string,epoch:string){await redis().set(key('presence:'+room+':'+guest),epoch,'PX',15000);}
export async function present(room:string,guest:string){return Boolean(await redis().get(key('presence:'+room+':'+guest)));}
export async function claimConnection(room:string,guest:string){const epoch=randomUUID();await presence(room,guest,epoch);return epoch;}
export async function currentConnection(room:string,guest:string,epoch:string){return await redis().get(key('presence:'+room+':'+guest))===epoch;}
export async function closeStore(){await connection?.quit();connection=undefined;}
