import {ONLINE_PROTOCOL,ROOM_LIMITS,decodeFrame,type OnlineRoom,type OnlineFrame,type InputAction,type OnlineInput} from './protocol';
import type {BotConfig} from '../model';
export type ConnectionState='connecting'|'connected'|'reconnecting'|'closed';
export class RoomConnection{
 socket?:WebSocket;guest='';room?:OnlineRoom;state:ConnectionState='closed';ping=0;offset=0;private samples:number[]=[];private reconnectTimer?:ReturnType<typeof setTimeout>;private heartbeat?:ReturnType<typeof setInterval>;private attempts=0;private stopped=false;private renewInProgress=false;private opened=0;private pending:unknown[]=[];
 onRoom:(room:OnlineRoom)=>void=()=>{};onFrame:(frame:OnlineFrame)=>void=()=>{};onState:(state:ConnectionState)=>void=()=>{};onError:(message:string)=>void=()=>{};
 constructor(readonly config:()=>BotConfig,readonly name:()=>string,readonly endpoint='/api/online'){}
 private change(state:ConnectionState){this.state=state;this.onState(state);}
 async connect(){if(this.stopped)return;this.change(this.attempts?'reconnecting':'connecting');try{const response=await fetch(this.endpoint+'?session=1',{credentials:'same-origin',cache:'no-store'});if(!response.ok)throw Error('The online service is unavailable.');const session=await response.json();if(session.protocol!==ONLINE_PROTOCOL)throw Error('Refresh the game to update online support.');const url=new URL(this.endpoint,location.href);url.protocol=url.protocol==='https:'?'wss:':'ws:';const socket=new WebSocket(url,['arena.v1','ticket.'+session.ticket]);socket.binaryType='arraybuffer';let welcomed=false;socket.onopen=()=>{this.opened=Date.now();this.guest=session.guest;};socket.onmessage=event=>{if(this.socket&&socket!==this.socket&&welcomed)return;if(typeof event.data!=='string'){try{const frame=decodeFrame(new Uint8Array(event.data));this.onFrame(frame);}catch(e){this.onError(e instanceof Error?e.message:'Invalid online state.');}return;}const message=JSON.parse(event.data);if(message.type==='welcome'){welcomed=true;const old=this.socket;this.socket=socket;this.guest=message.guest;this.attempts=0;this.renewInProgress=false;this.change('connected');old?.close(1000,'Connection renewed.');if(this.heartbeat)clearInterval(this.heartbeat);this.heartbeat=setInterval(()=>this.send({type:'ping',at:Date.now()}),3000);if(this.room)this.send({type:'join',code:this.room.code,expectedId:this.room.id,name:this.name(),config:this.config()});else{const saved=this.saved();if(saved)this.send({type:'join',code:saved.code,expectedId:saved.id,name:this.name(),config:this.config()});}for(const value of this.pending.splice(0))this.send(value);}else if(message.type==='room'){this.room=message.room;localStorage.setItem('cra.online.room',JSON.stringify({id:this.room!.id,code:this.room!.code}));this.onRoom(this.room!);}else if(message.type==='pong'){const rtt=Date.now()-message.at;if(rtt>=0&&rtt<5000){this.ping=rtt;this.samples.push(message.serverTime-message.at-rtt/2);this.samples=this.samples.slice(-9);this.offset=[...this.samples].sort((a,b)=>a-b)[Math.floor(this.samples.length/2)];}}else if(message.type==='renew'){if(!this.renewInProgress){this.renewInProgress=true;void this.connect();}}else if(message.type==='error'){this.onError(message.message);if(/expired|number changed/.test(message.message)){localStorage.removeItem('cra.online.room');this.room=undefined;}}};socket.onclose=()=>{if(this.stopped||this.socket&&this.socket!==socket)return;if(this.heartbeat)clearInterval(this.heartbeat);this.change('reconnecting');clearTimeout(this.reconnectTimer);this.reconnectTimer=setTimeout(()=>void this.connect(),Math.min(5000,250*2**Math.min(this.attempts++,5))+Math.random()*150);};socket.onerror=()=>{};}catch(e){this.onError(e instanceof Error?e.message:'Connection failed.');this.change('reconnecting');clearTimeout(this.reconnectTimer);this.reconnectTimer=setTimeout(()=>void this.connect(),Math.min(5000,500*2**Math.min(this.attempts++,4)));}}
 send(value:unknown){if(this.socket?.readyState===WebSocket.OPEN&&this.socket.bufferedAmount<64*1024)this.socket.send(JSON.stringify(value));}
 request(value:unknown){if(this.state==='connected')this.send(value);else this.pending.push(value);}
 create(mode:'duel'|'tournament',hazards:boolean){this.request({type:'create',mode,name:this.name(),config:this.config(),hazards});}
 join(code:string){this.request({type:'join',code,name:this.name(),config:this.config()});}
 leave(){this.send({type:'leave'});this.room=undefined;localStorage.removeItem('cra.online.room');}
 stop(){this.stopped=true;clearTimeout(this.reconnectTimer);if(this.heartbeat)clearInterval(this.heartbeat);this.socket?.close(1000,'Online view closed.');this.change('closed');}
 private saved(){try{const value=JSON.parse(localStorage.getItem('cra.online.room')??'null');return value&&typeof value.id==='string'&&/^[1-9]\d{3}$/.test(value.code)?value:undefined;}catch{return undefined;}}
}
