import {Simulation,initializePhysics,neutral,RAPIER,type Command} from '../sim';
import {RULES} from '../model';
import {applyReplica} from './replica';
import type {OnlineFrame,BodyPose} from './protocol';
let sim:Simulation|undefined,frame:OnlineFrame|undefined,side=0,target=0,history:{seq:number,tick:number,command:Command}[]=[],latest=neutral(),running=false;
const ready=initializePhysics();
self.onmessage=event=>{void handle(event.data).catch(()=>{sim?.dispose();sim=undefined;postMessage({type:'prediction-error'});});};
async function handle(message:any){await ready;if(message.type==='dispose'){sim?.dispose();sim=undefined;close();return;}if(message.type==='frame'){const next=message.frame as OnlineFrame;side=message.side;if(!sim||frame?.match!==next.match){sim?.dispose();sim=new Simulation(next.configs,{practice:true,hazards:message.hazards,ai:[false,false],recordVisuals:false,autoUnstick:false,prediction:true,predictionSide:side});history=[];}frame=next;side=message.side;applyReplica(sim,next);sim.result=undefined;for(const b of sim.bots)if(b.id!==side)for(const body of b.bodies.values())body.setBodyType(RAPIER.RigidBodyType.KinematicVelocityBased,true);history=history.filter(h=>h.seq>next.ack[side]);target=Math.max(next.tick,Math.min(next.tick+36,message.targetTick));latest=history.at(-1)?.command??neutral();run();}else if(message.type==='input'){if(!sim||!frame)return;latest=message.command;history.push({seq:message.seq,tick:message.tick,command:message.command});history=history.slice(-120);target=Math.max(target,Math.min(frame.tick+60,message.tick));run();}}
function run(){if(running||!sim||!frame||frame.phase!=='fight')return;running=true;try{let steps=0;while(sim.tick<target&&steps++<48){const next=[...history].reverse().find(h=>h.tick<=sim!.tick),command=next?.command??latest,commands:[Command,Command]=[neutral(),neutral()];commands[side]={...command,weapon:false,selfRight:false};sim.step(commands);if(sim.fault)throw Error(sim.fault);}const poses:BodyPose[]=[];for(const[id,body]of sim.bots[side].bodies)poses.push({id:'b'+side+':'+id,p:{...body.translation()},q:{...body.rotation()},v:{...body.linvel()},w:{...body.angvel()}});postMessage({type:'prediction',match:frame.match,tick:sim.tick,poses});}finally{running=false;}}
