import {PREDICTION_LIMITS} from './prediction-policy';
import {Simulation,initializePhysics,neutral,RAPIER,type Command} from '../sim';
import {RULES} from '../model';
import {applyReplica} from './replica';
import type {OnlineFrame,BodyPose} from './protocol';
let sim:Simulation|undefined,frame:OnlineFrame|undefined,side=0,target=0,history:{seq:number,tick:number,command:Command}[]=[],latest=neutral(),running=false,job=0;
const ready=initializePhysics();
self.onmessage=event=>{void handle(event.data).catch(()=>{sim?.dispose();sim=undefined;postMessage({type:'prediction-error'});});};
async function handle(message:any){await ready;if(message.type==='dispose'){sim?.dispose();sim=undefined;close();return;}if(message.type==='frame'){const next=message.frame as OnlineFrame;side=message.side;if(!sim||frame?.match!==next.match||frame?.epoch!==next.epoch){sim?.dispose();sim=new Simulation(next.configs,{practice:true,hazards:message.hazards,ai:[false,false],recordVisuals:false,autoUnstick:false,prediction:true,predictionSide:side});history=[];}frame=next;side=message.side;job=message.job??0;applyReplica(sim,next);sim.result=undefined;for(const b of sim.bots)if(b.id!==side)for(const body of b.bodies.values())body.setBodyType(RAPIER.RigidBodyType.KinematicVelocityBased,true);history=history.filter(h=>h.seq>next.ack[side]);if(message.input&&message.input.seq>next.ack[side]&&!history.some(h=>h.seq===message.input.seq))history.push(message.input);history=history.slice(-120);target=Math.max(next.tick,Math.min(next.tick+PREDICTION_LIMITS.leadTicks,message.targetTick));latest=history.at(-1)?.command??message.input?.command??neutral();run();}else if(message.type==='input'){if(!sim||!frame)return;latest=message.command;history.push({seq:message.seq,tick:message.tick,command:message.command});history=history.slice(-120);target=Math.max(target,Math.min(frame.tick+PREDICTION_LIMITS.leadTicks,message.tick));run();}}
function run(){if(running||!sim||!frame||frame.phase!=='fight')return;running=true;try{let steps=0;while(sim.tick<target&&steps++<PREDICTION_LIMITS.leadTicks){const next=[...history].reverse().find(h=>h.tick<=sim!.tick),command=next?.command??latest,commands:[Command,Command]=[neutral(),neutral()];commands[side]={...command,weapon:false,selfRight:false};sim.step(commands);if(sim.fault)throw Error(sim.fault);}const poses:BodyPose[]=[];for(const[id,body]of sim.bots[side].bodies)poses.push({id:'b'+side+':'+id,p:{...body.translation()},q:{...body.rotation()},v:{...body.linvel()},w:{...body.angvel()}});postMessage({type:'prediction',match:frame.match,epoch:frame.epoch,serial:frame.serial,sourceTick:frame.tick,tick:sim.tick,job,poses});}finally{running=false;}}
