import {Simulation,RAPIER,colliderDesc,type Bot} from '../sim';
import {copy,v,identity} from '../model';
import type {OnlineFrame,BodyPose} from './protocol';
export function applyReplica(sim:Simulation,frame:OnlineFrame,poses:BodyPose[]=frame.bodies){
 sim.tick=frame.tick;sim.result=frame.result;sim.fault=undefined;sim.physicsMs=frame.physicsMs;sim.wallDamage.cracks=frame.visual.wallCracks??[];
 for(const[side,state]of frame.bots.entries()){const b=sim.bots[side];Object.assign(b,{energy:state.energy,charges:state.charges,rpm:state.rpm,weaponOn:state.weaponOn,weaponWatts:state.weaponWatts,actuatorTorque:state.actuatorTorque,grounded:state.grounded,flipStart:state.flipStart,flipAngle:state.flipAngle,flipWork:state.flipWork,lastFire:state.lastFire,rollStart:state.rollStart,count:state.count,driveSign:state.driveSign,spinDirection:state.spinDirection,trackPhase:state.trackPhase,batteryFire:state.batteryFire});b.modules=copy(state.modules);const present=new Set(state.partIds);for(const[id,col]of b.colliders)if(!present.has(id)){if(col.isValid())sim.world.removeCollider(col,true);sim.meta.delete(col.handle);b.colliders.delete(id);}}
 const poseMap=new Map(poses.map(p=>[p.id,p]));for(const b of sim.bots)for(const[id,body]of b.bodies){const p=poseMap.get('b'+b.id+':'+id);if(p){body.setTranslation(p.p,true);body.setRotation(p.q,true);body.setLinvel(p.v,true);body.setAngvel(p.w,true);}}
 for(const h of sim.hazards){const p=poseMap.get('hazard_'+h.id);if(p){h.body.setTranslation(p.p,true);h.body.setRotation(p.q,true);h.body.setLinvel(p.v,true);h.body.setAngvel(p.w,true);}const state=frame.hazards.find(s=>s.id===h.id);if(state){h.phase=state.phase as typeof h.phase;h.cycle=state.cycle;}}
 const alive=new Set(frame.debris.map(d=>d.id));for(const d of [...sim.debris])if(!alive.has(d.id)){sim.world.removeRigidBody(d.body);sim.debris.splice(sim.debris.indexOf(d),1);}for(const d of frame.debris){let item=sim.debris.find(p=>p.id===d.id);if(!item){const part=copy(d.part) as any,body=sim.world.createRigidBody(RAPIER.RigidBodyDesc.dynamic());sim.world.createCollider(colliderDesc({...part,position:v(),rotation:identity}),body);item={id:d.id,part,body};sim.debris.push(item);}const p=poseMap.get(d.id)??d.body;item.body.setTranslation(p.p,true);item.body.setRotation(p.q,true);item.body.setLinvel(p.v,true);item.body.setAngvel(p.w,true);}
 sim.world.propagateModifiedBodyPositionsToColliders();
}
export function blendPoses(a:OnlineFrame,b:OnlineFrame,t:number):BodyPose[]{const previous=new Map(a.bodies.map(p=>[p.id,p]));return b.bodies.map(p=>{const old=previous.get(p.id);if(!old)return p;const mix=(x:number,y:number)=>x+(y-x)*t;let q={x:mix(old.q.x,p.q.x),y:mix(old.q.y,p.q.y),z:mix(old.q.z,p.q.z),w:mix(old.q.w,p.q.w)};const dot=old.q.x*p.q.x+old.q.y*p.q.y+old.q.z*p.q.z+old.q.w*p.q.w;if(dot<0)q={x:mix(old.q.x,-p.q.x),y:mix(old.q.y,-p.q.y),z:mix(old.q.z,-p.q.z),w:mix(old.q.w,-p.q.w)};const length=Math.hypot(q.x,q.y,q.z,q.w)||1;return{id:p.id,p:{x:mix(old.p.x,p.p.x),y:mix(old.p.y,p.p.y),z:mix(old.p.z,p.p.z)},q:{x:q.x/length,y:q.y/length,z:q.z/length,w:q.w/length},v:p.v,w:p.w};});}
