import{preset,compile,copy,ROSTER,MATERIALS,MOTORS,RULES,isSpinner,isHorizontal,componentProfile,componentConfig,bodyOrigin,rotate,add,v,identity,axisQ,type BotConfig,type Part,type Vec,type ComponentKind}from'./model';
export type KitKind=ComponentKind|'chassis';
export function scratchBuild():BotConfig{const c=preset(0);c.identity={name:'My robot',primary:'#387da2',secondary:'#ffb76e'};c.chassis={profile:'standard',form:'box',length:.45,width:.40,height:.14,material:'aluminium7075',thickness:.004,wedgeAngle:25,clearance:.03,equipmentMassKg:0};c.weapon={type:'none'};c.drive={layout:4,radius:.075,width:.045,material:'rubber',motor:'drive48',ratio:14,magnet:0,traction:'wheels'};c.armour=c.armour.map(p=>({...p,material:'aluminium7075',thickness:.002}));c.battery={pack:'P48',capacityWh:100};c.selfRight={type:'none'};c.components={};c.attachments=[];return c;}
export function installKit(input:BotConfig,kind:KitKind,index:number){const c=copy(input),donor=preset(index),profile=donor.chassis.profile!;c.components??={};if(kind==='chassis'){c.chassis=copy(donor.chassis);c.chassis.equipmentMassKg=0;}else{c.components[kind]=profile;if(kind==='weapon')c.weapon=copy(donor.weapon);else if(kind==='drive')c.drive=copy(donor.drive);else if(kind==='battery')c.battery=copy(donor.battery);else if(kind==='armour')c.armour=copy(donor.armour);else c.selfRight=copy(donor.selfRight);}return c;}
const templates=new Map<number,ReturnType<typeof compile>>();export function templateParts(index:number){let model=templates.get(index);if(!model){model=compile(preset(index),true);templates.set(index,model);}return model.parts;}
export function partKit(p:Part):KitKind|undefined{if(p.body.startsWith('wheel_')||p.module.startsWith('drive_'))return'drive';if(p.module==='weapon'||p.module==='weapon_actuator'||p.body==='rotor'||p.body==='weapon_arm'||p.body.startsWith('ground_fork_'))return'weapon';if(p.module==='self_right'||p.body==='self_right')return'selfRight';if(p.module==='battery')return'battery';return undefined;}
export function addStructuralPart(input:BotConfig,index:number,id:string){const p=templateParts(index).find(p=>p.id===id);if(!p)throw Error('The part does not exist.');const kit=partKit(p);if(kit)return installKit(input,kit,index);const c=copy(input);c.attachments??=[];if(c.attachments.length>=32)throw Error('Use at most 32 structural parts.');const uid='p'+Date.now().toString(36)+'_'+c.attachments.length;c.attachments.push({id:uid,template:index,part:id,mount:copy(p.position),rotation:copy(p.rotation)});return c;}
export function localVertices(p:Part):Vec[]{const shape=p.shape;if(shape.kind==='hull')return Array.from({length:shape.vertices.length/3},(_,i)=>v(...shape.vertices.slice(i*3,i*3+3) as [number,number,number]));if(shape.kind==='box')return[-1,1].flatMap(x=>[-1,1].flatMap(y=>[-1,1].map(z=>v(x*shape.size.x/2,y*shape.size.y/2,z*shape.size.z/2))));return Array.from({length:48},(_,i)=>v(Math.cos(i*Math.PI/12)*shape.radius,(i<24?-1:1)*shape.width/2,Math.sin(i*Math.PI/12)*shape.radius));}
export function partDimensions(p:Part){const points=localVertices(p).map(point=>add(p.position,rotate(point,p.rotation))),lo=v(),hi=v();for(const k of['x','y','z'] as const){lo[k]=Math.min(...points.map(p=>p[k]));hi[k]=Math.max(...points.map(p=>p[k]));}return v(hi.x-lo.x,hi.y-lo.y,hi.z-lo.z);}
export type BuildIssue={severity:'error'|'warning',field:string,message:string};
export function inspectBuild(c:BotConfig){let model;try{model=compile(c,true);}catch(e){return{model:undefined,issues:[{severity:'error',field:'build',message:e instanceof Error?e.message:'The build contains invalid data.'}] as BuildIssue[]};}const issues:BuildIssue[]=model.errors.map(e=>({...e,severity:'error'}));const originY=c.chassis.height/2+c.chassis.clearance;const addIssue=(severity:BuildIssue['severity'],field:string,message:string)=>{if(!issues.some(i=>i.message===message))issues.push({severity,field,message});};if(c.weapon.type==='none')addIssue('warning','weapon.type','No active weapon is installed. This robot can enter Practice but cannot enter a competitive fight.');
let frameLow=Infinity,weaponLow=Infinity;for(const p of model.parts){if(!p.collides)continue;const points=localVertices(p).map(point=>add(p.position,rotate(point,p.rotation))),origin=p.body.startsWith('wheel_')?v():bodyOrigin(c,p.body);if(p.body==='chassis'&&!p.module.startsWith('drive_'))frameLow=Math.min(frameLow,...points.map(p=>originY+p.y));if(p.body==='rotor'&&isSpinner(c.weapon)){const w=c.weapon;for(let step=0;step<24;step++){const q=axisQ(isHorizontal(w)?v(0,1,0):v(1,0,0),step*Math.PI/12);weaponLow=Math.min(weaponLow,...points.map(point=>originY+origin.y+rotate(point,q).y));}}}
if(frameLow<-.003)addIssue('error','chassis.clearance','The frame extends below the floor. Not all wheels can touch the floor. Raise chassis clearance or move the obstructing part.');if(weaponLow<-.002)addIssue('error','weapon.mount','The spinning weapon will hit the floor. Reduce its radius or raise its mount.');if(c.drive.layout>2&&c.chassis.length-2*c.drive.radius-.015<2*c.drive.radius+.006&&componentProfile(c,'drive')!=='hypershock')addIssue('warning','drive.radius','The wheel spacing is tight. Check adjacent wheels and choose a longer frame or smaller wheels.');const axleY=c.drive.radius-originY;if(Math.abs(axleY)>c.chassis.height/2+.05)addIssue('warning','chassis.clearance','The wheel axles are outside the frame height. Adjust chassis clearance or wheel radius before a physical fit test.');
for(const p of model.parts)if(!Number.isFinite(p.mass)||!Object.values(p.position).every(Number.isFinite)||!Object.values(p.rotation).every(Number.isFinite))addIssue('error','build','A part has invalid mass or coordinates. Restore its dimensions.');return{model,issues};}
export function componentStats(c:BotConfig){const model=compile(c,true),driveRPM=48*MOTORS[c.drive.motor].kv/c.drive.ratio,driveSpeed=driveRPM*Math.PI/30*c.drive.radius;return{model,driveRPM,driveSpeed,weaponRPM:isSpinner(c.weapon)?c.weapon.rpm:0,tipSpeed:model.tip,parts:model.parts.map(p=>({part:p,dimensions:partDimensions(p),mass:p.mass,material:p.material,source:p.module==='weapon'||p.module==='weapon_actuator'?componentProfile(c,'weapon'):p.module.startsWith('drive_')?componentProfile(c,'drive'):c.chassis.profile??'standard'}))};}
