import{RULES,clamp,type Vec}from'./model';import{hitTier,damageNumber,roundedDamage,HIT_BUBBLE_MARKUP,type HitReadout}from'./hit-readouts';
type Projector={width:number,height:number,projectCombatPoint:(p:Vec)=>{x:number,y:number,visible:boolean}};
type Bodies={bots:{chassis:{translation:()=>Vec}}[]};
const sizes=new WeakMap<HTMLElement,{key:string,width:number,height:number}>();
export function presentHitReadouts(container:HTMLElement,readouts:readonly HitReadout[],tick:number,renderer:Projector,sim:Bodies,reduced=false){
 const hits=readouts.filter(h=>roundedDamage(h.hp)>1&&tick-h.tick<RULES.hz*1.3),keys=new Set(hits.map(h=>h.key));for(const child of Array.from(container.children))if(!keys.has((child as HTMLElement).dataset.key??''))child.remove();
 for(const hit of hits){let el=Array.from(container.children).find(e=>(e as HTMLElement).dataset.key===hit.key) as HTMLElement|undefined;if(!el){el=document.createElement('span');el.dataset.key=hit.key;el.className='hit-number p'+(hit.bot+1);el.innerHTML=HIT_BUBBLE_MARKUP;container.appendChild(el);}const contact=renderer.projectCombatPoint(hit.point),position=sim.bots[hit.bot]?.chassis.translation(),fallback=position?renderer.projectCombatPoint(position):undefined,point=contact.visible?contact:fallback,age=Math.max(0,(tick-hit.tick)/RULES.hz),tier=hitTier(roundedDamage(hit.hp)),flare=reduced?0:Math.max(0,1-age/.24),label=damageNumber(hit.hp),hp=el.querySelector('.hit-hp')!;if(hp.textContent!==label)hp.textContent=label;el.dataset.tier=String(tier);el.dataset.reduced=String(reduced);el.classList.remove('hidden');
 const drift=hit.bot===0?-1:1,bounce=reduced?0:Math.sin(age*18)*Math.exp(-age*7),sway=reduced?0:drift*(12+9*tier)*(1-Math.exp(-age*3));el.style.setProperty('--hit-wobble',bounce*5+'deg');el.style.setProperty('--hit-spread',String(reduced?1:1+Math.min(age,.5)*.6));el.style.setProperty('--hit-flare',String(flare));el.style.setProperty('--hit-pop',String(1+flare*(.04+tier*.05)+bounce*.09));el.style.setProperty('--hit-glow',([0,2,4,7,10,14,20][tier]*(.65+.35*flare))+'px');
 const width=renderer.width||container.clientWidth,height=renderer.height||container.clientHeight,key=[tier,label,width,height,window.devicePixelRatio].join('/');let size=sizes.get(el);if(size?.key!==key){size={key,width:el.offsetWidth,height:el.offsetHeight};sizes.set(el,size);}const mx=Math.min(42,(size.width/2+42)/Math.max(1,width)*100),my=Math.min(40,(size.height/2+70)/Math.max(1,height)*100);el.style.left=clamp(Number.isFinite(point?.x)?point!.x:(hit.bot?75:25),mx,100-mx)+'%';el.style.top=clamp(Number.isFinite(point?.y)?point!.y:55,my,100-my)+'%';el.style.transform='translate(calc(-50% + '+sway+'px), '+(-16-(reduced?0:age*52)-bounce*8)+'px)';el.style.opacity=String(Math.min(1,(1.3-age)*2.5));
 }
}
