export const CAMERA_MODES=['tactical','chase','pov'] as const;
export const CAMERA_LABELS={tactical:'Tactical',chase:'Third person',pov:'Robot POV'};
export function nextCamera(mode:typeof CAMERA_MODES[number]){return CAMERA_MODES[(CAMERA_MODES.indexOf(mode)+1)%CAMERA_MODES.length];}
import {clamp} from './model';
import {neutral,type Command} from './sim';
export const ACTIONS=['forward','reverse','left','right','weapon','selfRight','camera','unstick'] as const;
export type Action=typeof ACTIONS[number];
export type Assignment='keyboard'|'pad0'|'pad1';
export type Preferences={quality:'low'|'medium'|'high',adaptive:boolean,master:number,sfx:number,replays:boolean,autoUnstick:boolean,captions:boolean,reduced:boolean,inset:boolean,cameraMode:'tactical'|'pov'|'chase',deadzone:number,steering:'arcade'|'tank',controls:[Record<Action,string>,Record<Action,string>],assignments:[Assignment,Assignment],debug:boolean};
export const defaults=():Preferences=>({quality:'medium',adaptive:true,master:.65,sfx:.8,replays:false,autoUnstick:true,captions:true,reduced:matchMedia('(prefers-reduced-motion: reduce)').matches,inset:false,cameraMode:'chase',deadzone:.15,steering:'arcade',controls:[{forward:'ArrowUp',reverse:'ArrowDown',left:'ArrowLeft',right:'ArrowRight',weapon:'Space',selfRight:'KeyQ',camera:'KeyE',unstick:'KeyR'},{forward:'KeyI',reverse:'KeyK',left:'KeyJ',right:'KeyL',weapon:'Enter',selfRight:'KeyU',camera:'KeyO',unstick:'KeyP'}],assignments:['keyboard','keyboard'],debug:false});
export function loadPreferences():Preferences{const d=defaults();try{const raw=JSON.parse(localStorage.getItem('cra.preferences')??'null');if(!raw||typeof raw!=='object')return d;for(const k of ['replays','captions','reduced','inset','debug','autoUnstick','adaptive'] as const)if(typeof raw[k]==='boolean')d[k]=raw[k];for(const k of ['master','sfx','deadzone'] as const)if(typeof raw[k]==='number'&&Number.isFinite(raw[k]))d[k]=clamp(raw[k],k==='deadzone'?.05:0,k==='deadzone'?.45:1);if(['tactical','pov','chase'].includes(raw.cameraMode))d.cameraMode=raw.cameraMode;if(['low','medium','high'].includes(raw.quality))d.quality=raw.quality;if(['arcade','tank'].includes(raw.steering))d.steering=raw.steering;if(Array.isArray(raw.controls)&&raw.controls.length===2){for(let p=0;p<2;p++)for(const a of ACTIONS)if(typeof raw.controls[p]?.[a]==='string'&&/^(Key[A-Z]|Digit[0-9]|Arrow(Up|Down|Left|Right)|Space|Enter|Shift(Left|Right)|Control(Left|Right)|Bracket(Left|Right)|Comma|Period|Slash|Semicolon|Quote)$/.test(raw.controls[p][a]))d.controls[p][a]=raw.controls[p][a];}const old=d.controls[0];if(old.forward==='KeyW'&&old.reverse==='KeyS'&&old.left==='KeyA'&&old.right==='KeyD'&&!d.controls.flatMap(c=>Object.values(c)).some(k=>k.startsWith('Arrow')))Object.assign(old,{forward:'ArrowUp',reverse:'ArrowDown',left:'ArrowLeft',right:'ArrowRight'});const used=new Set(d.controls.flatMap(c=>Object.values(c)).filter(k=>k!=='KeyV'));for(let player=0;player<2;player++)for(const action of ACTIONS)if(d.controls[player][action]==='KeyV'){const choices=[defaults().controls[player][action],...'ABCDEFGHIJKLMNOPQRSTUVWXYZ'.split('').filter(k=>k!=='V').map(k=>'Key'+k)];const replacement=choices.find(k=>!used.has(k))!;d.controls[player][action]=replacement;used.add(replacement);}const keys=d.controls.flatMap(c=>Object.values(c));if(new Set(keys).size!==keys.length)d.controls=defaults().controls;if(Array.isArray(raw.assignments))for(let i=0;i<2;i++)if(['keyboard','pad0','pad1'].includes(raw.assignments[i]))d.assignments[i]=raw.assignments[i];return d;}catch{return d;}}
export function savePreferences(p:Preferences){try{localStorage.setItem('cra.preferences',JSON.stringify(p));}catch{/* Preferences remain usable in memory. */}}
export const keyLabel=(code:string)=>({ArrowUp:'↑',ArrowDown:'↓',ArrowLeft:'←',ArrowRight:'→'} as Record<string,string>)[code]??code.replace(/^Key/,'').replace(/^Digit/,'').replace('Arrow','').replace('Space','SPACE').replace('Enter','ENTER');
export function gamepads():readonly (Gamepad|null)[]{try{return navigator.getGamepads?.()??[];}catch{return [];}}
export class Input{
 held=new Set<string>();edges=new Set<string>();padPrevious=[[] as boolean[],[] as boolean[]];connected=new Set<number>();remap?:{player:number,action:Action};onRemap?:(message?:string)=>void;
 constructor(public prefs:Preferences,readonly active:()=>boolean,readonly pause:(reason:string)=>void,readonly camera:()=>void,readonly recover:()=>void=()=>{},readonly thirdPerson:()=>void=camera){
 window.addEventListener('keydown',this.keydown);window.addEventListener('keyup',this.keyup);window.addEventListener('blur',this.blur);document.addEventListener('visibilitychange',this.visibility);window.addEventListener('gamepaddisconnected',this.disconnect);
 }
 editing(e:KeyboardEvent){return e.target instanceof HTMLInputElement||e.target instanceof HTMLTextAreaElement||e.target instanceof HTMLSelectElement||(e.target instanceof HTMLElement&&e.target.isContentEditable);}
 keydown=(e:KeyboardEvent)=>{if(this.remap){e.preventDefault();if(e.code==='Escape'){this.remap=undefined;this.onRemap?.();return;}if(!/^(Key[A-Z]|Digit[0-9]|Arrow(Up|Down|Left|Right)|Space|Enter|Shift(Left|Right)|Control(Left|Right)|Bracket(Left|Right)|Comma|Period|Slash|Semicolon|Quote)$/.test(e.code)){this.onRemap?.('Choose a letter, number, arrow, or control key.');return;}if(e.code==='KeyV'){this.onRemap?.('V switches third person. Choose another key.');return;}const {player,action}=this.remap;const conflict=this.prefs.controls.some((c,i)=>ACTIONS.some(a=>(i!==player||a!==action)&&c[a]===e.code));if(conflict){this.onRemap?.('That key is already assigned.');return;}this.prefs.controls[player][action]=e.code;savePreferences(this.prefs);this.remap=undefined;this.onRemap?.();return;}
 if(this.editing(e))return;if(e.code==='KeyV'&&this.active()){e.preventDefault();if(!e.repeat&&!this.held.has(e.code)){this.held.add(e.code);this.thirdPerson();}return;}if(e.code==='Escape'&&this.active()){e.preventDefault();this.pause('Paused');return;}if(!this.active())return;if(this.prefs.controls.some(c=>c.unstick===e.code)){e.preventDefault();if(!e.repeat&&!this.held.has(e.code)){this.recover();this.held.add(e.code);}return;}if(this.prefs.controls.some(c=>Object.values(c).includes(e.code))){e.preventDefault();if(!this.held.has(e.code)&&!e.repeat)this.edges.add(e.code);this.held.add(e.code);}};
 keyup=(e:KeyboardEvent)=>{this.held.delete(e.code);};
 blur=()=>{this.clear();if(this.active())this.pause('Focus left the arena.');};
 visibility=()=>{if(document.hidden){this.clear();if(this.active())this.pause('The tab is hidden.');}};
 disconnect=(e:GamepadEvent)=>{this.connected.delete(e.gamepad.index);if(this.prefs.assignments.includes(('pad'+e.gamepad.index) as Assignment)&&this.active())this.pause('Controller disconnected. Reconnect it, then resume.');this.clear();};
 clear(){this.held.clear();this.edges.clear();const pads=gamepads();this.connected.clear();this.padPrevious=this.prefs.assignments.map(a=>{const pad=a==='keyboard'?undefined:pads[Number(a.slice(3))];if(pad?.connected)this.connected.add(pad.index??Number(a.slice(3)));return pad?.buttons.map(b=>b.pressed)??[];});}
 assignmentIssue(local:boolean){const list=local?this.prefs.assignments:[this.prefs.assignments[0]];if(local&&list[0]===list[1]&&list[0]!=='keyboard')return 'Assign a different gamepad to each player.';const pads=gamepads();for(const a of list)if(a!=='keyboard'&&!pads[Number(a.slice(3))]?.connected)return `${a==='pad0'?'Gamepad 1':'Gamepad 2'} is not connected. Press a controller button.`;return '';}
 sample(player:number):Command{const a=this.prefs.assignments[player];if(a==='keyboard'){const keys=this.prefs.controls[player],down=(k:Action)=>this.held.has(keys[k])?1:0;let left:number,right:number;if(this.prefs.steering==='tank'){left=down('forward')-down('reverse');right=down('left')-down('right');}else{const forward=down('forward')-down('reverse'),turn=down('right')-down('left');left=clamp(forward+turn*.7,-1,1);right=clamp(forward-turn*.7,-1,1);}const cmd={left,right,weapon:this.edges.delete(keys.weapon),selfRight:this.edges.delete(keys.selfRight)};if(this.edges.delete(keys.camera))this.camera();return cmd;}
 const index=Number(a.slice(3)),pad=gamepads()[index];if(!pad?.connected){if(this.connected.delete(index)&&this.active())this.pause('Controller disconnected. Reconnect it, then resume.');return neutral();}this.connected.add(index);const dz=this.prefs.deadzone,axis=(i:number)=>{const x=pad.axes[i]??0;return Math.abs(x)<=dz?0:Math.sign(x)*(Math.abs(x)-dz)/(1-dz);},pressed=pad.buttons.map(x=>x.pressed),prev=this.padPrevious[player],edge=(i:number)=>!!pressed[i]&&!prev[i];if(edge(9)){this.pause('Paused');return neutral();}if(edge(3))this.camera();let left:number,right:number;if(this.prefs.steering==='tank'){left=-axis(1);right=-axis(3);}else{const f=-axis(1),turn=axis(0)*.7;left=clamp(f+turn,-1,1);right=clamp(f-turn,-1,1);}const cmd={left,right,weapon:edge(0),selfRight:edge(1)};this.padPrevious[player]=pressed;return cmd;
 }
 dispose(){window.removeEventListener('keydown',this.keydown);window.removeEventListener('keyup',this.keyup);window.removeEventListener('blur',this.blur);document.removeEventListener('visibilitychange',this.visibility);window.removeEventListener('gamepaddisconnected',this.disconnect);}
}
