import {ROBOT_PORTRAITS} from './robot-portraits';
import {victoryConfetti} from './result-view';
import type {Tournament,Entry} from './sim';
import type {OnlineRoom} from './online/protocol';
import type {BotConfig} from './model';
export type CupEntry={key:string,name:string,config:BotConfig,player:boolean};
export type CupMatch={a:string,b:string,winner?:string,reason?:string};
export type CupModel={entries:CupEntry[],rounds:CupMatch[][],round:number,hazards:boolean,champion?:string};
export const cupEscape=(v:unknown)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
export const CUP_TROPHY='<svg viewBox="0 0 64 64" fill="none" aria-hidden="true"><path d="M20 10h24v13c0 12-6 19-12 19S20 35 20 23V10Z" stroke="currentColor" stroke-width="3"/><path d="M20 15H9v7c0 8 6 12 15 12m20-19h11v7c0 8-6 12-15 12M32 42v11m-11 3h22M23 10l4-6 5 5 5-5 4 6" stroke="currentColor" stroke-width="3" stroke-linecap="round"/><path d="m32 18 2.5 5 5.5.8-4 4 .9 5.4-4.9-2.6-4.9 2.6.9-5.4-4-4 5.5-.8 2.5-5Z" fill="currentColor"/></svg>';
export function cupPortrait(config:BotConfig){const fallback:Record<string,string>={drum:'minotaur',flipper:'hydra',crusher:'quantum',vertical_disc:'hypershock',shell_spinner:'gigabyte',horizontal_cage:'whyachi',hammer_saw:'sawblaze',vertical_bar:'deep_six'};return ROBOT_PORTRAITS[config.chassis.profile??'']??ROBOT_PORTRAITS[fallback[config.weapon.type]??'tombstone'];}
export function offlineCup(t:Tournament):CupModel{const key=(e:Entry)=>'e'+t.entries.indexOf(e);return{entries:t.entries.map(e=>({key:key(e),name:e.name,config:e.config,player:e.player})),rounds:t.matches.map(r=>r.map(m=>({a:key(m.a),b:key(m.b),winner:m.winner?key(m.winner):undefined,reason:m.reason}))),round:t.round,hazards:t.hazards,champion:t.champion?key(t.champion):undefined};}
export function onlineCup(room:OnlineRoom,guest:string):CupModel{return{entries:room.entrants.map(e=>({key:e.id,name:e.config.identity.name,config:e.config,player:e.id===guest})),rounds:room.rounds.map(r=>r.map(m=>({a:m.a,b:m.b,winner:m.winner,reason:m.result?.reason}))),round:room.round,hazards:room.hazards,champion:room.champion};}
export function cupRecords(model:CupModel){const records=new Map(model.entries.map(e=>[e.key,{wins:0,losses:0}]));for(const round of model.rounds)for(const match of round)if(match.winner){const winner=records.get(match.winner),loser=records.get(match.winner===match.a?match.b:match.a);if(winner)winner.wins++;if(loser)loser.losses++;}return records;}
const recordMarkup=(wins:number,losses:number)=>'<span class="cup-record" aria-label="'+wins+' wins and '+losses+' losses"><b>'+wins+' W</b><i>'+losses+' L</i></span>';
export function cupChampion(model:CupModel,reduced:boolean,key=model.champion){const entry=model.entries.find(e=>e.key===key);if(!entry)return '';const record=cupRecords(model).get(entry.key)!;return '<section class="cup-champion" data-champion="'+cupEscape(entry.key)+'"><div class="cup-champion-rays" aria-hidden="true"></div><div class="cup-champion-emblem">'+CUP_TROPHY+'</div><div class="cup-champion-copy"><span class="cup-eyebrow">THE FOUNDRY CROWN</span><h2>Overall champion</h2><strong>'+cupEscape(entry.name)+'</strong>'+recordMarkup(record.wins,record.losses)+'<p>Three rounds. One machine at the summit.</p></div><div class="cup-champion-photo"><img src="'+cupPortrait(entry.config)+'" alt="'+cupEscape(entry.name)+'" width="240" height="160">'+victoryConfetti(reduced)+'</div></section>';}
export function cupRoundVictory(t:Tournament,reduced:boolean){const model=offlineCup(t),match=t.matches[t.round].find(m=>m.a.player||m.b.player);if(!match?.winner?.player)return '';if(t.round===2)return cupChampion(model,reduced,'e'+t.entries.indexOf(match.winner));const entry=model.entries[0],record=cupRecords(model).get(entry.key)!;return '<section class="cup-victory-banner"><span class="cup-medal">'+CUP_TROPHY+'</span><div><span class="cup-eyebrow">ROUND '+(t.round+1)+' CONQUERED</span><strong>'+cupEscape(entry.name)+' advances</strong><small>900 repair points · Your next challenge is ready</small></div>'+recordMarkup(record.wins,record.losses)+victoryConfetti(reduced)+'</section>';}
export function cupIntro(config:BotConfig){return '<div class="cup-intro-art"><div class="cup-intro-trophy">'+CUP_TROPHY+'</div><img src="'+cupPortrait(config)+'" alt="'+cupEscape(config.identity.name)+'" width="250" height="160"><span>YOUR CONTENDER</span><strong>'+cupEscape(config.identity.name)+'</strong></div><div class="cup-intro-facts"><span><b>8</b> contenders</span><span><b>3</b> wins to the crown</span><span><b>900</b> repair points per win</span></div>';}
export function renderCupBracket(host:HTMLElement,model:CupModel,reduced:boolean){
 const signature=JSON.stringify({entries:model.entries.map(e=>[e.key,e.name,e.config.chassis.profile]),rounds:model.rounds,round:model.round,champion:model.champion,reduced});
 if(host.dataset.cupSignature!==signature){host.dataset.cupSignature=signature;host.dataset.reduced=String(reduced);const records=cupRecords(model);
  const entryRow=(key:string|undefined,r:number,m:number,slot:number,match?:CupMatch)=>{const entry=model.entries.find(e=>e.key===key),record=key?records.get(key):undefined,state=match?.winner?(match.winner===key?'won':'lost'):'pending';if(!entry)return '<div class="cup-entry cup-empty" data-r="'+r+'" data-m="'+m+'" data-slot="'+slot+'"><span class="cup-empty-icon">◇</span><span>Awaiting contender</span></div>';return '<div class="cup-entry '+state+(entry.player?' is-player':'')+'" data-r="'+r+'" data-m="'+m+'" data-slot="'+slot+'" data-entry="'+cupEscape(entry.key)+'"><div class="cup-entry-photo"><img src="'+cupPortrait(entry.config)+'" alt="" width="56" height="44"></div><div class="cup-entry-body"><strong>'+cupEscape(entry.name)+'</strong>'+recordMarkup(record?.wins??0,record?.losses??0)+'</div><span class="cup-result-badge" aria-label="'+(state==='won'?'Winner':state==='lost'?'Eliminated':entry.player?'Your robot':'Pending')+'">'+(entry.player?'YOU '+(state==='won'?'★':state==='lost'?'×':''):state==='won'?'★':state==='lost'?'×':'·')+'</span></div>';};
  host.innerHTML='<div class="cup-map"><svg class="cup-connectors" aria-hidden="true"></svg>'+['Quarterfinals','Semifinals','Final'].map((name,r)=>'<section class="cup-stage"><header><span>0'+(r+1)+'</span><h3>'+name+'</h3><small>'+(r===0?'8 contenders':r===1?'4 contenders':'The crown')+'</small></header><div class="cup-stage-matches">'+Array.from({length:2**(2-r)},(_,index)=>{const match=model.rounds[r]?.[index],row=r===0?index*2+1:r===1?index*4+2:4;return '<article class="cup-match" data-match-r="'+r+'" data-match-i="'+index+'" style="grid-row:'+row+' / span 2" data-state="'+(match?.winner?'complete':r===model.round?'active':'future')+'">'+entryRow(match?.a,r,index,0,match)+entryRow(match?.b,r,index,1,match)+'<div class="cup-match-footer">'+(match?.reason==='Quick bracket result'?'QUICK RESULT':match?.winner?cupEscape(match.reason??'COMPLETE'):r===model.round?'ROUND '+(r+1):'NEXT STAGE')+'</div></article>';}).join('')+'</div></section>').join('')+'</div>';
 }
 watchCupLayout(host,model);drawCupConnections(host,model);
}
export function drawCupConnections(host:HTMLElement,model:CupModel){const map=host.querySelector<HTMLElement>('.cup-map'),svg=host.querySelector<SVGSVGElement>('.cup-connectors');if(!map||!svg)return;const rect=svg.getBoundingClientRect(),width=svg.clientWidth,height=svg.clientHeight;if(!width||!height||!rect.width||!rect.height)return;const sx=rect.width/width,sy=rect.height/height,paths:string[]=[];const curve=(x:number,y:number,tx:number,ty:number)=>'M '+x+' '+y+' C '+((x+tx)/2)+' '+y+' '+((x+tx)/2)+' '+ty+' '+tx+' '+ty;
 for(let r=0;r<2;r++)for(let index=0;index<2**(2-r);index++){const match=model.rounds[r]?.[index],winnerTarget=match?.winner?Array.from(map.querySelectorAll<HTMLElement>('[data-r="'+(r+1)+'"][data-entry]')).find(row=>row.dataset.entry===match.winner):undefined,target=winnerTarget??map.querySelector<HTMLElement>('[data-r="'+(r+1)+'"][data-m="'+Math.floor(index/2)+'"][data-slot="'+index%2+'"]');if(!target)continue;const to=target.getBoundingClientRect(),tx=(to.left-rect.left)/sx-3,ty=(to.top-rect.top+to.height/2)/sy;
  for(const slot of[0,1]){const row=map.querySelector<HTMLElement>('[data-r="'+r+'"][data-m="'+index+'"][data-slot="'+slot+'"]');if(!row)continue;const box=row.getBoundingClientRect(),x=(box.right-rect.left)/sx+3,y=(box.top-rect.top+box.height/2)/sy,key=slot===0?match?.a:match?.b,state=match?.winner?(match.winner===key?'win':'loss'):'pending',endX=state==='loss'?x+(tx-x)*.6:tx,endY=state==='loss'?y+(slot?14:-14):ty;paths.push('<path data-source="'+r+'/'+index+'/'+slot+'" data-target="'+target.dataset.r+'/'+target.dataset.m+'/'+target.dataset.slot+'" class="cup-path '+state+'" d="'+curve(x,y,endX,endY)+'" marker-end="url(#cup-'+state+'-arrow)"/>'+(state==='loss'?'<text class="cup-out-label" x="'+(endX+2)+'" y="'+(endY+3)+'">OUT</text>':''));}
 }
 const content='<defs>'+[['win','#65e7b4'],['loss','#ff7189'],['pending','#50778b']].map(([key,color])=>'<marker id="cup-'+key+'-arrow" viewBox="0 0 10 10" refX="8" refY="5" markerWidth="5" markerHeight="5" orient="auto-start-reverse"><path d="M 1 1 L 9 5 L 1 9" fill="none" stroke="'+color+'" stroke-width="2"/></marker>').join('')+'</defs>'+paths.join('');const signature=width+'/'+height+'/'+content;if(svg.dataset.layout!==signature){svg.dataset.layout=signature;svg.setAttribute('viewBox','0 0 '+width+' '+height);svg.innerHTML=content;}
}
export function compactCup(model:CupModel){const records=cupRecords(model);return '<div class="cup-compact-rounds">'+model.rounds.map((round,r)=>'<section><h3>'+(model.entries.length===2?'Duel':['Quarterfinals','Semifinals','Final'][r])+'</h3>'+round.map(match=>'<div class="cup-compact-match">'+[match.a,match.b].map(key=>{const e=model.entries.find(v=>v.key===key),rec=records.get(key),state=match.winner?(match.winner===key?'won':'lost'):'pending';return '<div class="'+state+(e?.player?' is-player':'')+'"><img src="'+(e?cupPortrait(e.config):'')+'" alt="" width="40" height="30"><span>'+cupEscape(e?.name)+'</span>'+recordMarkup(rec?.wins??0,rec?.losses??0)+'</div>';}).join('')+'</div>').join('')+'</section>').join('')+'</div>';}

const cupLayouts=new WeakMap<HTMLElement,{map:HTMLElement,model:CupModel,observer:ResizeObserver,frame:number,life:number,refresh:()=>void}>();
function watchCupLayout(host:HTMLElement,model:CupModel){
 const map=host.querySelector<HTMLElement>('.cup-map');if(!map)return;const previous=cupLayouts.get(host);if(previous?.map===map){previous.model=model;return;}if(previous){previous.observer.disconnect();cancelAnimationFrame(previous.frame);cancelAnimationFrame(previous.life);window.removeEventListener('resize',previous.refresh);}
 const state={map,model,observer:undefined as unknown as ResizeObserver,frame:0,life:0,refresh:()=>{if(state.frame)return;state.frame=requestAnimationFrame(()=>{state.frame=0;if(host.isConnected)drawCupConnections(host,state.model);});}};
 state.observer=new ResizeObserver(state.refresh);state.observer.observe(map);map.querySelectorAll('.cup-entry').forEach(row=>state.observer.observe(row));window.addEventListener('resize',state.refresh);
 const alive=()=>{if(!host.isConnected){state.observer.disconnect();window.removeEventListener('resize',state.refresh);cancelAnimationFrame(state.frame);cupLayouts.delete(host);return;}state.life=requestAnimationFrame(alive);};state.life=requestAnimationFrame(alive);document.fonts?.ready.then(state.refresh);cupLayouts.set(host,state);state.refresh();
}
