// Reference configurations, checked 2026-09-23. Numbers marked as estimates
// are game settings, never claims of a measured real-world specification.
export const LB_TO_KG=.45359237;
export const LBF_TO_N=4.4482216152605;
export type WeaponReference={massLb?:number;massBasis:'published'|'estimate'|'geometry';rpm?:number;tipMph?:number;speedBasis:'published'|'derived'|'estimate'|'not applicable';configuration:string;note:string;sources:{label:string;url:string}[]};
export const WEAPON_REFERENCES:Record<string,WeaponReference>={
 tombstone:{massLb:70,massBasis:'published',tipMph:250,speedBasis:'derived',configuration:'2019 Ray Billings interview',note:'The Ringer’s original interview with Ray Billings reports a 70 lb bar limited to 250 mph in competition. RPM is calculated for the game radius; interchangeable real bars vary.',sources:[{label:'Ray Billings interview: The Ringer',url:'https://www.theringer.com/2019/06/11/tv/battlebots-season-9-premiere-discovery-science'}]},
 minotaur:{massLb:50,massBasis:'published',rpm:8000,speedBasis:'published',configuration:'2019 designer interview',note:'Stevens interviews lead designer Rodrigo Nogueira: 50 lb drum, 8,000 RPM. The game caps the target to 250 mph for its modeled drum radius.',sources:[{label:'Stevens: designer interview',url:'https://www.stevens.edu/news/stevens-student-returns-battlebots-2019-season'}]},
 hydra:{massBasis:'geometry',speedBasis:'not applicable',configuration:'Hydraulic flipper',note:'No spinning rotor. Moving arm mass is calculated from the game geometry; a reliable separate arm mass was not found. Hydraulic hardware is not a rotating weapon.',sources:[{label:'Team Whyachi',url:'https://whyachi.com/bots/'}]},
 icewave:{massLb:54,massBasis:'published',tipMph:200,speedBasis:'derived',configuration:'Season 6 team modal study (2022)',note:'The team’s joint engineering report specifies a 54 lb blade and 200 mph tips. RPM is calculated for the game radius. The game uses its electric motor approximation.',sources:[{label:'Team Icewave / PCB engineering report',url:'https://www.pcb.com/contentstore/MktgContent/linkeddocuments/technotes/TN-38_ModalTesting_Icewave.pdf'}]},
 hypershock:{massLb:45,massBasis:'published',rpm:6800,speedBasis:'estimate',configuration:'2019 double-disc mass; game speed',note:'Will Bales gave approximately 45 lb for the double-disc spinning assembly in the 2019 team AMA. The 6,800 RPM setting is a game estimate, not a verified team specification.',sources:[{label:'Will Bales: team AMA',url:'https://www.reddit.com/r/battlebots/comments/cspm64/'}]},
 gigabyte:{massLb:120,massBasis:'estimate',tipMph:190,speedBasis:'estimate',configuration:'Game shell configuration',note:'120 lb / 190 mph are game estimates. Accessible official team profiles did not establish exact shell mass and speed. RPM is calculated for the game radius.',sources:[{label:'BattleBots team profile',url:'https://battlebots.com/robot/gigabyte-wcvii/'}]},
 whyachi:{massLb:120,massBasis:'estimate',tipMph:170,speedBasis:'derived',configuration:'2016–2019 team tip-speed reference',note:'Team Whyachi specifies up to 170 mph. RPM is calculated for the game radius. Cage mass is a 120 lb game estimate; the team page does not publish it.',sources:[{label:'Team Whyachi: Son of Whyachi',url:'https://whyachi.com/bots/'}]},
 huge:{massLb:30,massBasis:'published',tipMph:235,speedBasis:'derived',configuration:'Team robot specification',note:'The team specifies 30 lb bars and 220–250 mph depending on bar length. This preset uses the 235 mph midpoint, converted to RPM for the game radius.',sources:[{label:'Team HUGE: robot specifications',url:'https://hugebattlebots.com/about-the-robot'}]},
 sawblaze:{massLb:30,massBasis:'estimate',tipMph:250,speedBasis:'derived',configuration:'2023 builder specification; estimated disc mass',note:'Jamison Go specifies a 16-inch hammer-saw disc and 250 mph tips. RPM follows from that diameter. Disc mass is a 30 lb game estimate, excluding the separate swinging arm.',sources:[{label:'Jamison Go: SawBlaze',url:'https://jamisongo.com/projects/sawblaze/'}]},
 deep_six:{massLb:80,massBasis:'published',rpm:1860,speedBasis:'estimate',configuration:'2021 weapon; game speed',note:'The official team profile states an 80 lb weapon. 1,860 RPM is a game estimate within the modeled blade’s 250 mph limit; exact operating RPM was not confirmed.',sources:[{label:'BattleBots: Deep Six 2021',url:'https://battlebots.com/robot/deep-six-2021/'}]},
 quantum:{massBasis:'geometry',speedBasis:'not applicable',configuration:'Hydraulic crusher',note:'No spinning rotor. Jaw mass is calculated from the game geometry. BattleBots confirms 35,000 lbf; the rear 50,000 lbf rating and two-stage action follow the requested specification.',sources:[{label:'BattleBots: Quantum 2019',url:'https://battlebots.com/robot/quantum-2019/'}]},
};
export function referenceRPM(ref:WeaponReference,radius:number,tipLimit:number){
 const requested=ref.rpm??(ref.tipMph??0)*.44704*30/(Math.PI*radius);
 return Math.floor(Math.min(requested,tipLimit*30/(Math.PI*radius)));
}
export const QUANTUM_HYDRAULICS={frontForce:35000*LBF_TO_N,rearForce:50000*LBF_TO_N,closeSeconds:.30,pressureRiseSeconds:.12,pumpWatts:3500,indentSpeed:.014,cycleJoules:12000} as const;
// Lever-arm force curve: front at full reach, rear at 70% of that reach.
export function quantumBiteForce(reach:number,distanceFromPivot:number){return Math.min(QUANTUM_HYDRAULICS.rearForce,QUANTUM_HYDRAULICS.frontForce*reach/Math.max(reach*.7,distanceFromPivot));}
